-- Simplified invitation signup (DEC-PROD-426, DEC-PROD-427, DEC-PROD-428).
--
-- Redefines invitation_protocol.submit_invitation_acceptance_v2 with an IDENTICAL 7-argument
-- signature so no GRANT or caller changes are required. Later-migration redefinition follows the
-- established precedent set by 20260914120000 and 20260915120000.
--
-- REMOVED (invitation acceptance no longer requires offline recovery codes or friction prompts):
--   1. SELECT INTO set_row FROM "RecoveryCodeSet" ... state='rehearsed'      (was line 1156)
--   2. setup_row."setupState"<>'rehearsed' OR set_row."userId" IS NULL       (was line 1157)
--   3. typed household-name equality and 'I UNDERSTAND ADMIN ACCESS'         (was line 1158)
--   4. rehearsed-set requirement and remainingActiveCount<>9                 (was line 1159)
--
-- WIDENED:
--   5. terminal write now accepts every legitimate pre-acceptance state, including
--      'recovery_generated' -- the mid-rehearsal state. Omitting it would permanently strand users
--      stopped partway through the retired flow. 'accepted' stays excluded so the TERMINAL_FULL
--      replay branch remains the only path for an already-accepted row.
--
-- PRESERVED UNCHANGED: terminal replay idempotency, inviter authority recheck (including
-- owner-only-for-admin), the membership outcome matrix (created / reentered /
-- already_member_same_role / suspended / active_different_role), the Invite pending->accepted CAS
-- raising invitation_operation_conflict, and the deferred occupancy guard.
--
-- Recovery codes remain fully available opt-in from ordinary account settings (DEC-PROD-428);
-- this migration adds no constraint requiring them and removes none of the existing machinery.

CREATE OR REPLACE FUNCTION invitation_protocol.submit_invitation_acceptance_v2(operation_id UUID, review_version INTEGER, review_snapshot_digest TEXT, intent_fingerprint BYTEA, typed_household_name TEXT, nullable_admin_acknowledgement TEXT, request_attestation invitation_protocol.invitation_request_attestation) RETURNS JSONB LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog,invitation_protocol AS $$
DECLARE identity_row invitation_protocol."InvitationOperationIdentity"%ROWTYPE; binding_row invitation_protocol."InvitationOperationBinding"%ROWTYPE; claim_row invitation_protocol."InvitationPresentationClaim"%ROWTYPE; invite_row public."Invite"%ROWTYPE; household_row public."Household"%ROWTYPE; session_row public."Session"%ROWTYPE; user_row public."User"%ROWTYPE; setup_row invitation_protocol."InvitationAccountSetup"%ROWTYPE; set_row public."RecoveryCodeSet"%ROWTYPE; inviter_member public."HouseholdMember"%ROWTYPE; member_row public."HouseholdMember"%ROWTYPE; result_row invitation_protocol."InvitationOperationResult"%ROWTYPE; review JSONB; remainingActiveCount INTEGER; outcome TEXT; membership_id TEXT; review_fields TEXT[]:=ARRAY['household_name','offered_role','capabilities','restrictions','inviter_display_name','masked_recipient','server_utc_expiry','localized_relative_expiry','reentry_state','access_restrictions','attribution_audit_privacy','global_security_boundary','other_membership_boundary','recovery_signin_boundary'];
BEGIN
  PERFORM invitation_protocol.lock_global_security_transition_v1();
  SELECT * INTO identity_row FROM invitation_protocol."InvitationOperationIdentity" WHERE "operationId"=operation_id AND "operationKind"='MEMBERSHIP_ACCEPTANCE' FOR UPDATE; IF identity_row."id" IS NULL OR octet_length(intent_fingerprint)<>32 OR review_version<=0 OR review_snapshot_digest !~ '^[0-9a-f]{64}$' OR (request_attestation).intent_fingerprint IS DISTINCT FROM intent_fingerprint THEN RAISE EXCEPTION 'invitation_submit_invalid'; END IF;
  PERFORM invitation_protocol.lock_invitation_protocol_v2(identity_row."householdId",operation_id); identity_row:=invitation_protocol.reauthorize_invitation_carrier_v2(identity_row."id",operation_id,'MEMBERSHIP_ACCEPTANCE',request_attestation); SELECT * INTO binding_row FROM invitation_protocol."InvitationOperationBinding" WHERE "identityId"=identity_row."id" FOR UPDATE; SELECT * INTO claim_row FROM invitation_protocol."InvitationPresentationClaim" WHERE "identityId"=binding_row."target"::UUID AND "subjectUserId"=(request_attestation).subject_user_id FOR UPDATE; SELECT * INTO invite_row FROM public."Invite" i JOIN invitation_protocol."InvitationLineage" l ON l."sourceInviteId"=i."id" WHERE l."id"=claim_row."lineageId" AND i."status"='pending' AND i."expiresAt">clock_timestamp() FOR UPDATE OF i; SELECT * INTO household_row FROM public."Household" WHERE "id"=identity_row."householdId" AND "deletedAt" IS NULL FOR UPDATE; SELECT * INTO session_row FROM public."Session" WHERE "id"=(request_attestation).ordinary_session_id AND "expiresAt">clock_timestamp() FOR UPDATE; SELECT * INTO user_row FROM public."User" WHERE "id"=session_row."userId" FOR UPDATE; PERFORM 1 FROM invitation_protocol."InvitationRequestAttestation" WHERE "identityId"=identity_row."id" FOR UPDATE;
  SELECT * INTO result_row FROM invitation_protocol."InvitationOperationResult" WHERE "identityId"=identity_row."id" FOR UPDATE; IF identity_row."state"='TERMINAL_FULL' THEN IF result_row."intentFingerprint" IS DISTINCT FROM intent_fingerprint THEN RAISE EXCEPTION 'invitation_operation_conflict'; END IF; RETURN invitation_protocol.invitation_safe_receipt(operation_id,'completed',result_row."outcomeCode"); END IF;
  SELECT * INTO setup_row FROM invitation_protocol."InvitationAccountSetup" WHERE "userId"=user_row."id" FOR UPDATE; review:=invitation_protocol.recompute_invitation_review_snapshot_v2(binding_row."target"::UUID,(request_attestation).ordinary_session_id);
  IF claim_row."identityId" IS NULL OR invite_row."id" IS NULL OR household_row."id" IS NULL OR session_row."id" IS NULL OR user_row."id" IS NULL OR setup_row."userId" IS NULL OR binding_row."openingFingerprint" IS DISTINCT FROM (request_attestation).opening_fingerprint OR identity_row."state"<>'PREPARED' OR review IS NULL OR (review->>'reviewVersion')::INTEGER<>review_version OR review->>'reviewSnapshotDigest'<>review_snapshot_digest OR review->>'lowercase_hex64'<>'true' THEN RAISE EXCEPTION 'stale_review'; END IF;
  -- simplified signup: typed household name and admin acknowledgement no longer required (DEC-PROD-426)
  -- simplified signup: offline recovery codes are optional (DEC-PROD-428); no code-set preconditions
  SELECT * INTO inviter_member FROM public."HouseholdMember" WHERE "householdId"=identity_row."householdId" AND "userId"=invite_row."invitedByUserId" AND "disabledAt" IS NULL AND "deletedAt" IS NULL ORDER BY "createdAt" DESC FOR UPDATE; IF inviter_member."id" IS NULL OR (invite_row."role"='admin' AND inviter_member."role"<>'owner') OR (invite_row."role" IN ('parent','caretaker','read_only') AND inviter_member."role" NOT IN ('owner','admin')) THEN RAISE EXCEPTION 'inviter_authority_lost'; END IF;
  SELECT * INTO member_row FROM public."HouseholdMember" WHERE "householdId"=identity_row."householdId" AND "userId"=user_row."id" ORDER BY "createdAt" DESC FOR UPDATE; IF member_row."id" IS NULL OR member_row."deletedAt" IS NOT NULL THEN membership_id:='hm_'||encode(public.gen_random_bytes(16),'hex'); INSERT INTO public."HouseholdMember"("id","householdId","userId","role","joinedAt","createdAt","updatedAt") VALUES(membership_id,identity_row."householdId",user_row."id",invite_row."role",clock_timestamp(),clock_timestamp(),clock_timestamp()); outcome:=CASE WHEN member_row."id" IS NULL THEN 'created' ELSE 'reentered' END; ELSIF member_row."disabledAt" IS NOT NULL THEN RAISE EXCEPTION 'suspended'; ELSIF member_row."role"<>invite_row."role" THEN RAISE EXCEPTION 'active_different_role'; ELSE membership_id:=member_row."id"; outcome:='already_member_same_role'; END IF;
  UPDATE public."Invite" SET "status"='accepted',"acceptedByUserId"=user_row."id","acceptedAt"=clock_timestamp(),"updatedAt"=clock_timestamp() WHERE "id"=invite_row."id" AND "status"='pending'; IF NOT FOUND THEN RAISE EXCEPTION 'invitation_operation_conflict'; END IF; UPDATE invitation_protocol."InvitationAccountSetup" SET "setupState"='accepted' WHERE "userId"=user_row."id" AND "setupState" IN ('credential_created','credential_existing','recovery_generated','rehearsed'); IF NOT FOUND THEN RAISE EXCEPTION 'stale_review'; END IF; PERFORM invitation_protocol.execute_invitation_domain_transition_v2(identity_row,'membership_acceptance'); PERFORM invitation_protocol.write_invitation_terminal_result_v2(identity_row,intent_fingerprint,'membership_accepted',jsonb_build_object('outcome',outcome)); PERFORM invitation_protocol.write_invitation_audit_v2(identity_row."householdId",identity_row."id",'membership.accept',jsonb_build_object('outcome',outcome),ROW('owner')::invitation_protocol.invitation_owner_private_call_attestation); RETURN invitation_protocol.invitation_safe_receipt(operation_id,'completed','membership_accepted');
END $$;

