import type { SemanticServiceOperationDeclaration } from "@/server/operation-registry/schema";

export const semantic = [{
  kind: "service", id: "activity.create", ownerModule: "src/server/services/activities.ts", exportName: "createActivity",
  axes: {
    carrier_authority_guard: { current: { authority: "source_reviewed", value: "createActivity calls getEffectiveHouseholdContext(), which requires the request's validated membership-episode cookie candidate and does not fall back to another membership", sourceReferences: [{ kind: "symbol", file: "src/server/services/activities.ts", exportName: "createActivity" }] }, target: { authority: "deferred", gateId: "gate.carrier_authority_guard" } },
    caller_controlled_scope: { current: { authority: "source_reviewed", value: "createActivity accepts raw input and passes it unchanged to createActivityForContext with the selected context", sourceReferences: [{ kind: "symbol", file: "src/server/services/activities.ts", exportName: "createActivity" }] }, target: { authority: "deferred", gateId: "gate.caller_controlled_scope" } },
    service_operation_linkage: { current: { authority: "source_reviewed", value: "createActivity directly returns createActivityForContext(raw, ctx)", sourceReferences: [{ kind: "symbol", file: "src/server/services/activities.ts", exportName: "createActivity" }] }, target: { authority: "deferred", gateId: "gate.service_operation_linkage" } },
    permission_commit_reauthorization: { current: { authority: "source_reviewed", value: "createActivity contains no permission or transaction check itself and delegates to createActivityForContext", sourceReferences: [{ kind: "symbol", file: "src/server/services/activities.ts", exportName: "createActivity" }] }, target: { authority: "deferred", gateId: "gate.permission_commit_reauthorization" } },
    tenant_relationship_invariants: { current: { authority: "source_reviewed", value: "createActivity passes the selected context unchanged to createActivityForContext and contains no direct relationship check", sourceReferences: [{ kind: "symbol", file: "src/server/services/activities.ts", exportName: "createActivity" }] }, target: { authority: "deferred", gateId: "gate.tenant_relationship_invariants" } },
    model_reads_writes_effects: { current: { authority: "source_reviewed", value: "createActivity contains no direct Prisma call and returns the result of createActivityForContext", sourceReferences: [{ kind: "symbol", file: "src/server/services/activities.ts", exportName: "createActivity" }] }, target: { authority: "deferred", gateId: "gate.model_and_effects" } },
    variant_specific_outcomes: { current: { authority: "not_applicable", rationale: "createActivity has no declared semantic variant", sourceReferences: [{ kind: "symbol", file: "src/server/services/activities.ts", exportName: "createActivity" }] }, target: { authority: "deferred", gateId: "gate.variant_outcomes" } },
    worker_loop_claim_failure_containment: { current: { authority: "not_applicable", rationale: "createActivity does not contain a worker loop", sourceReferences: [{ kind: "symbol", file: "src/server/services/activities.ts", exportName: "createActivity" }] }, target: { authority: "deferred", gateId: "gate.worker_containment" } },
    browser_immutable_binding_stale_behavior: { current: { authority: "deferred", gateId: "gate.browser_binding_staleness" }, target: { authority: "deferred", gateId: "gate.browser_binding_staleness" } },
    executable_evidence_strength: { current: { authority: "deferred", gateId: "gate.executable_evidence" }, target: { authority: "deferred", gateId: "gate.executable_evidence" } }
  }
}, {
  kind: "service", id: "activity.delete", ownerModule: "src/server/services/activities.ts", exportName: "deleteActivity",
  axes: {
    carrier_authority_guard: { current: { authority: "source_reviewed", value: "deleteActivity calls getEffectiveHouseholdContext(), which requires the request's validated membership-episode cookie candidate and does not fall back to another membership", sourceReferences: [{ kind: "symbol", file: "src/server/services/activities.ts", exportName: "deleteActivity" }] }, target: { authority: "deferred", gateId: "gate.carrier_authority_guard" } },
    caller_controlled_scope: { current: { authority: "source_reviewed", value: "deleteActivity accepts an activity id and optional mutation input parsed by timerMutationInput", sourceReferences: [{ kind: "symbol", file: "src/server/services/activities.ts", exportName: "deleteActivity" }] }, target: { authority: "deferred", gateId: "gate.caller_controlled_scope" } },
    service_operation_linkage: { current: { authority: "source_reviewed", value: "deleteActivity is the exported delete service and handles replay before its mutation transaction", sourceReferences: [{ kind: "symbol", file: "src/server/services/activities.ts", exportName: "deleteActivity" }] }, target: { authority: "deferred", gateId: "gate.service_operation_linkage" } },
    permission_commit_reauthorization: { current: { authority: "source_reviewed", value: "inside its transaction deleteActivity locks the actor and baby and checks own-or-any delete permission before its claimed update", sourceReferences: [{ kind: "symbol", file: "src/server/services/activities.ts", exportName: "deleteActivity" }] }, target: { authority: "deferred", gateId: "gate.permission_commit_reauthorization" } },
    tenant_relationship_invariants: { current: { authority: "source_reviewed", value: "deleteActivity constrains candidate, lock, and update predicates by the locked household id and target baby", sourceReferences: [{ kind: "symbol", file: "src/server/services/activities.ts", exportName: "deleteActivity" }] }, target: { authority: "deferred", gateId: "gate.tenant_relationship_invariants" } },
    model_reads_writes_effects: { current: { authority: "source_reviewed", value: "the source marks ActivityLog deleted with updateMany and records a mutation receipt, audit, and queued activity side effects", sourceReferences: [{ kind: "symbol", file: "src/server/services/activities.ts", exportName: "deleteActivity" }] }, target: { authority: "deferred", gateId: "gate.model_and_effects" } },
    variant_specific_outcomes: { current: { authority: "not_applicable", rationale: "deleteActivity has no declared semantic variant", sourceReferences: [{ kind: "symbol", file: "src/server/services/activities.ts", exportName: "deleteActivity" }] }, target: { authority: "deferred", gateId: "gate.variant_outcomes" } },
    worker_loop_claim_failure_containment: { current: { authority: "not_applicable", rationale: "deleteActivity does not contain a worker loop", sourceReferences: [{ kind: "symbol", file: "src/server/services/activities.ts", exportName: "deleteActivity" }] }, target: { authority: "deferred", gateId: "gate.worker_containment" } },
    browser_immutable_binding_stale_behavior: { current: { authority: "deferred", gateId: "gate.browser_binding_staleness" }, target: { authority: "deferred", gateId: "gate.browser_binding_staleness" } },
    executable_evidence_strength: { current: { authority: "deferred", gateId: "gate.executable_evidence" }, target: { authority: "deferred", gateId: "gate.executable_evidence" } }
  }
}, {
  kind: "service", id: "activity.update", ownerModule: "src/server/services/activities.ts", exportName: "updateActivity",
  axes: {
    carrier_authority_guard: { current: { authority: "source_reviewed", value: "updateActivity calls getEffectiveHouseholdContext(), which requires the request's validated membership-episode cookie candidate and does not fall back to another membership", sourceReferences: [{ kind: "symbol", file: "src/server/services/activities.ts", exportName: "updateActivity" }] }, target: { authority: "deferred", gateId: "gate.carrier_authority_guard" } },
    caller_controlled_scope: { current: { authority: "source_reviewed", value: "updateActivity accepts an activity id and raw input and parses them with activityUpdateSchema", sourceReferences: [{ kind: "symbol", file: "src/server/services/activities.ts", exportName: "updateActivity" }] }, target: { authority: "deferred", gateId: "gate.caller_controlled_scope" } },
    service_operation_linkage: { current: { authority: "source_reviewed", value: "updateActivity is the exported update service and handles replay before its mutation transaction", sourceReferences: [{ kind: "symbol", file: "src/server/services/activities.ts", exportName: "updateActivity" }] }, target: { authority: "deferred", gateId: "gate.service_operation_linkage" } },
    permission_commit_reauthorization: { current: { authority: "source_reviewed", value: "inside its transaction updateActivity locks the actor and baby and checks own-or-any update permission before its claimed update", sourceReferences: [{ kind: "symbol", file: "src/server/services/activities.ts", exportName: "updateActivity" }] }, target: { authority: "deferred", gateId: "gate.permission_commit_reauthorization" } },
    tenant_relationship_invariants: { current: { authority: "source_reviewed", value: "updateActivity constrains ActivityLog lookups and the claimed update by the locked household id and locks the submitted baby", sourceReferences: [{ kind: "symbol", file: "src/server/services/activities.ts", exportName: "updateActivity" }] }, target: { authority: "deferred", gateId: "gate.tenant_relationship_invariants" } },
    model_reads_writes_effects: { current: { authority: "source_reviewed", value: "the source claims ActivityLog by expected updatedAt, replaces the type-specific log, and records a receipt, audit, and queued side effects", sourceReferences: [{ kind: "symbol", file: "src/server/services/activities.ts", exportName: "updateActivity" }] }, target: { authority: "deferred", gateId: "gate.model_and_effects" } },
    variant_specific_outcomes: { current: { authority: "not_applicable", rationale: "updateActivity has no declared semantic variant", sourceReferences: [{ kind: "symbol", file: "src/server/services/activities.ts", exportName: "updateActivity" }] }, target: { authority: "deferred", gateId: "gate.variant_outcomes" } },
    worker_loop_claim_failure_containment: { current: { authority: "not_applicable", rationale: "updateActivity does not contain a worker loop", sourceReferences: [{ kind: "symbol", file: "src/server/services/activities.ts", exportName: "updateActivity" }] }, target: { authority: "deferred", gateId: "gate.worker_containment" } },
    browser_immutable_binding_stale_behavior: { current: { authority: "deferred", gateId: "gate.browser_binding_staleness" }, target: { authority: "deferred", gateId: "gate.browser_binding_staleness" } },
    executable_evidence_strength: { current: { authority: "deferred", gateId: "gate.executable_evidence" }, target: { authority: "deferred", gateId: "gate.executable_evidence" } }
  }
}, {
  kind: "service", id: "activity.undo_last", ownerModule: "src/server/services/activities.ts", exportName: "undoLastActivity",
  axes: {
    carrier_authority_guard: { current: { authority: "source_reviewed", value: "undoLastActivity calls getEffectiveHouseholdContext(), which requires the request's validated membership-episode cookie candidate and does not fall back to another membership", sourceReferences: [{ kind: "symbol", file: "src/server/services/activities.ts", exportName: "undoLastActivity" }] }, target: { authority: "deferred", gateId: "gate.carrier_authority_guard" } },
    caller_controlled_scope: { current: { authority: "source_reviewed", value: "undoLastActivity accepts optional mutation input parsed by timerMutationInput and selects the actor's latest create or delete audit", sourceReferences: [{ kind: "symbol", file: "src/server/services/activities.ts", exportName: "undoLastActivity" }] }, target: { authority: "deferred", gateId: "gate.caller_controlled_scope" } },
    service_operation_linkage: { current: { authority: "source_reviewed", value: "undoLastActivity is the exported undo service and handles replay before its mutation transaction", sourceReferences: [{ kind: "symbol", file: "src/server/services/activities.ts", exportName: "undoLastActivity" }] }, target: { authority: "deferred", gateId: "gate.service_operation_linkage" } },
    permission_commit_reauthorization: { current: { authority: "source_reviewed", value: "inside its transaction undoLastActivity locks the actor, baby, and activity and checks own-or-any delete or update permission before its claimed update", sourceReferences: [{ kind: "symbol", file: "src/server/services/activities.ts", exportName: "undoLastActivity" }] }, target: { authority: "deferred", gateId: "gate.permission_commit_reauthorization" } },
    tenant_relationship_invariants: { current: { authority: "source_reviewed", value: "undoLastActivity constrains the audit, activity lookup, lock, and claimed update by the locked household id", sourceReferences: [{ kind: "symbol", file: "src/server/services/activities.ts", exportName: "undoLastActivity" }] }, target: { authority: "deferred", gateId: "gate.tenant_relationship_invariants" } },
    model_reads_writes_effects: { current: { authority: "source_reviewed", value: "the source toggles ActivityLog deletedAt for the latest eligible create or delete and records a mutation receipt and activity.undo audit", sourceReferences: [{ kind: "symbol", file: "src/server/services/activities.ts", exportName: "undoLastActivity" }] }, target: { authority: "deferred", gateId: "gate.model_and_effects" } },
    variant_specific_outcomes: { current: { authority: "not_applicable", rationale: "undoLastActivity has no declared semantic variant", sourceReferences: [{ kind: "symbol", file: "src/server/services/activities.ts", exportName: "undoLastActivity" }] }, target: { authority: "deferred", gateId: "gate.variant_outcomes" } },
    worker_loop_claim_failure_containment: { current: { authority: "not_applicable", rationale: "undoLastActivity does not contain a worker loop", sourceReferences: [{ kind: "symbol", file: "src/server/services/activities.ts", exportName: "undoLastActivity" }] }, target: { authority: "deferred", gateId: "gate.worker_containment" } },
    browser_immutable_binding_stale_behavior: { current: { authority: "deferred", gateId: "gate.browser_binding_staleness" }, target: { authority: "deferred", gateId: "gate.browser_binding_staleness" } },
    executable_evidence_strength: { current: { authority: "deferred", gateId: "gate.executable_evidence" }, target: { authority: "deferred", gateId: "gate.executable_evidence" } }
  }
}, {
  kind: "service", id: "activity.timer.pause", ownerModule: "src/server/services/activities.ts", exportName: "pauseTimer",
  axes: {
    carrier_authority_guard: { current: { authority: "source_reviewed", value: "pauseTimer calls getEffectiveHouseholdContext(), which requires the request's validated membership-episode cookie candidate and does not fall back to another membership", sourceReferences: [{ kind: "symbol", file: "src/server/services/activities.ts", exportName: "pauseTimer" }] }, target: { authority: "deferred", gateId: "gate.carrier_authority_guard" } },
    caller_controlled_scope: { current: { authority: "source_reviewed", value: "pauseTimer accepts an activity id and optional mutation input parsed for clientMutationId", sourceReferences: [{ kind: "symbol", file: "src/server/services/activities.ts", exportName: "pauseTimer" }] }, target: { authority: "deferred", gateId: "gate.caller_controlled_scope" } },
    service_operation_linkage: { current: { authority: "source_reviewed", value: "pauseTimer is the exported pause service and handles timer replay before its mutation transaction", sourceReferences: [{ kind: "symbol", file: "src/server/services/activities.ts", exportName: "pauseTimer" }] }, target: { authority: "deferred", gateId: "gate.service_operation_linkage" } },
    permission_commit_reauthorization: { current: { authority: "source_reviewed", value: "inside its transaction pauseTimer locks the actor and baby and checks own-or-any update permission before its claimed state transition", sourceReferences: [{ kind: "symbol", file: "src/server/services/activities.ts", exportName: "pauseTimer" }] }, target: { authority: "deferred", gateId: "gate.permission_commit_reauthorization" } },
    tenant_relationship_invariants: { current: { authority: "source_reviewed", value: "pauseTimer constrains its claimed ActivityLog transition by the locked household id and target activity id", sourceReferences: [{ kind: "symbol", file: "src/server/services/activities.ts", exportName: "pauseTimer" }] }, target: { authority: "deferred", gateId: "gate.tenant_relationship_invariants" } },
    model_reads_writes_effects: { current: { authority: "source_reviewed", value: "the source changes a running ActivityLog timer to paused and records a timer.pause receipt and activity.timer.pause audit", sourceReferences: [{ kind: "symbol", file: "src/server/services/activities.ts", exportName: "pauseTimer" }] }, target: { authority: "deferred", gateId: "gate.model_and_effects" } },
    variant_specific_outcomes: { current: { authority: "not_applicable", rationale: "pauseTimer has no declared semantic variant", sourceReferences: [{ kind: "symbol", file: "src/server/services/activities.ts", exportName: "pauseTimer" }] }, target: { authority: "deferred", gateId: "gate.variant_outcomes" } },
    worker_loop_claim_failure_containment: { current: { authority: "not_applicable", rationale: "pauseTimer does not contain a worker loop", sourceReferences: [{ kind: "symbol", file: "src/server/services/activities.ts", exportName: "pauseTimer" }] }, target: { authority: "deferred", gateId: "gate.worker_containment" } },
    browser_immutable_binding_stale_behavior: { current: { authority: "deferred", gateId: "gate.browser_binding_staleness" }, target: { authority: "deferred", gateId: "gate.browser_binding_staleness" } },
    executable_evidence_strength: { current: { authority: "deferred", gateId: "gate.executable_evidence" }, target: { authority: "deferred", gateId: "gate.executable_evidence" } }
  }
}, {
  kind: "service", id: "activity.timer.resume", ownerModule: "src/server/services/activities.ts", exportName: "resumeTimer",
  axes: {
    carrier_authority_guard: { current: { authority: "source_reviewed", value: "resumeTimer calls getEffectiveHouseholdContext(), which requires the request's validated membership-episode cookie candidate and does not fall back to another membership", sourceReferences: [{ kind: "symbol", file: "src/server/services/activities.ts", exportName: "resumeTimer" }] }, target: { authority: "deferred", gateId: "gate.carrier_authority_guard" } },
    caller_controlled_scope: { current: { authority: "source_reviewed", value: "resumeTimer accepts an activity id and optional mutation input parsed for clientMutationId", sourceReferences: [{ kind: "symbol", file: "src/server/services/activities.ts", exportName: "resumeTimer" }] }, target: { authority: "deferred", gateId: "gate.caller_controlled_scope" } },
    service_operation_linkage: { current: { authority: "source_reviewed", value: "resumeTimer is the exported resume service and handles timer replay before its mutation transaction", sourceReferences: [{ kind: "symbol", file: "src/server/services/activities.ts", exportName: "resumeTimer" }] }, target: { authority: "deferred", gateId: "gate.service_operation_linkage" } },
    permission_commit_reauthorization: { current: { authority: "source_reviewed", value: "inside its transaction resumeTimer locks the actor and baby, checks own-or-any update permission, and rejects an inactive baby before its claimed state transition", sourceReferences: [{ kind: "symbol", file: "src/server/services/activities.ts", exportName: "resumeTimer" }] }, target: { authority: "deferred", gateId: "gate.permission_commit_reauthorization" } },
    tenant_relationship_invariants: { current: { authority: "source_reviewed", value: "resumeTimer constrains its claimed ActivityLog transition by the locked household id and target activity id", sourceReferences: [{ kind: "symbol", file: "src/server/services/activities.ts", exportName: "resumeTimer" }] }, target: { authority: "deferred", gateId: "gate.tenant_relationship_invariants" } },
    model_reads_writes_effects: { current: { authority: "source_reviewed", value: "the source changes a paused ActivityLog timer to running and records a timer.resume receipt and activity.timer.resume audit", sourceReferences: [{ kind: "symbol", file: "src/server/services/activities.ts", exportName: "resumeTimer" }] }, target: { authority: "deferred", gateId: "gate.model_and_effects" } },
    variant_specific_outcomes: { current: { authority: "not_applicable", rationale: "resumeTimer has no declared semantic variant", sourceReferences: [{ kind: "symbol", file: "src/server/services/activities.ts", exportName: "resumeTimer" }] }, target: { authority: "deferred", gateId: "gate.variant_outcomes" } },
    worker_loop_claim_failure_containment: { current: { authority: "not_applicable", rationale: "resumeTimer does not contain a worker loop", sourceReferences: [{ kind: "symbol", file: "src/server/services/activities.ts", exportName: "resumeTimer" }] }, target: { authority: "deferred", gateId: "gate.worker_containment" } },
    browser_immutable_binding_stale_behavior: { current: { authority: "deferred", gateId: "gate.browser_binding_staleness" }, target: { authority: "deferred", gateId: "gate.browser_binding_staleness" } },
    executable_evidence_strength: { current: { authority: "deferred", gateId: "gate.executable_evidence" }, target: { authority: "deferred", gateId: "gate.executable_evidence" } }
  }
}, {
  kind: "service", id: "activity.timer.stop", ownerModule: "src/server/services/activities.ts", exportName: "stopTimer",
  axes: {
    carrier_authority_guard: { current: { authority: "source_reviewed", value: "stopTimer calls getEffectiveHouseholdContext(), which requires the request's validated membership-episode cookie candidate and does not fall back to another membership", sourceReferences: [{ kind: "symbol", file: "src/server/services/activities.ts", exportName: "stopTimer" }] }, target: { authority: "deferred", gateId: "gate.carrier_authority_guard" } },
    caller_controlled_scope: { current: { authority: "source_reviewed", value: "stopTimer accepts an activity id and optional mutation input parsed for clientMutationId", sourceReferences: [{ kind: "symbol", file: "src/server/services/activities.ts", exportName: "stopTimer" }] }, target: { authority: "deferred", gateId: "gate.caller_controlled_scope" } },
    service_operation_linkage: { current: { authority: "source_reviewed", value: "stopTimer is the exported stop service and handles timer replay before its mutation transaction", sourceReferences: [{ kind: "symbol", file: "src/server/services/activities.ts", exportName: "stopTimer" }] }, target: { authority: "deferred", gateId: "gate.service_operation_linkage" } },
    permission_commit_reauthorization: { current: { authority: "source_reviewed", value: "inside its transaction stopTimer locks the actor and baby and checks own-or-any update permission before its claimed state transition", sourceReferences: [{ kind: "symbol", file: "src/server/services/activities.ts", exportName: "stopTimer" }] }, target: { authority: "deferred", gateId: "gate.permission_commit_reauthorization" } },
    tenant_relationship_invariants: { current: { authority: "source_reviewed", value: "stopTimer constrains its claimed ActivityLog transition by the locked household id and target activity id", sourceReferences: [{ kind: "symbol", file: "src/server/services/activities.ts", exportName: "stopTimer" }] }, target: { authority: "deferred", gateId: "gate.tenant_relationship_invariants" } },
    model_reads_writes_effects: { current: { authority: "source_reviewed", value: "the source changes a running or paused ActivityLog timer to stopped and records a timer.stop receipt, audit, and queued side effects", sourceReferences: [{ kind: "symbol", file: "src/server/services/activities.ts", exportName: "stopTimer" }] }, target: { authority: "deferred", gateId: "gate.model_and_effects" } },
    variant_specific_outcomes: { current: { authority: "not_applicable", rationale: "stopTimer has no declared semantic variant", sourceReferences: [{ kind: "symbol", file: "src/server/services/activities.ts", exportName: "stopTimer" }] }, target: { authority: "deferred", gateId: "gate.variant_outcomes" } },
    worker_loop_claim_failure_containment: { current: { authority: "not_applicable", rationale: "stopTimer does not contain a worker loop", sourceReferences: [{ kind: "symbol", file: "src/server/services/activities.ts", exportName: "stopTimer" }] }, target: { authority: "deferred", gateId: "gate.worker_containment" } },
    browser_immutable_binding_stale_behavior: { current: { authority: "deferred", gateId: "gate.browser_binding_staleness" }, target: { authority: "deferred", gateId: "gate.browser_binding_staleness" } },
    executable_evidence_strength: { current: { authority: "deferred", gateId: "gate.executable_evidence" }, target: { authority: "deferred", gateId: "gate.executable_evidence" } }
  }
}] as const satisfies readonly SemanticServiceOperationDeclaration[];
