import type { SemanticServiceOperationDeclaration } from "@/server/operation-registry/schema";

export const semantic = [{
  kind: "service", id: "settings.appearance.update", ownerModule: "src/server/services/appearance.ts", exportName: "updateHouseholdAppearance",
  axes: {
    carrier_authority_guard: { current: { authority: "source_reviewed", value: "updateHouseholdAppearance calls getEffectiveHouseholdContext(), which requires the request's validated membership-episode cookie candidate and does not fall back to another membership", sourceReferences: [{ kind: "symbol", file: "src/server/services/appearance.ts", exportName: "updateHouseholdAppearance" }] }, target: { authority: "deferred", gateId: "gate.carrier_authority_guard" } },
    caller_controlled_scope: { current: { authority: "source_reviewed", value: "updateHouseholdAppearance reads accentTheme from raw input and parses it with accentThemeSchema", sourceReferences: [{ kind: "symbol", file: "src/server/services/appearance.ts", exportName: "updateHouseholdAppearance" }] }, target: { authority: "deferred", gateId: "gate.caller_controlled_scope" } },
    service_operation_linkage: { current: { authority: "source_reviewed", value: "updateHouseholdAppearance is the exported appearance update service", sourceReferences: [{ kind: "symbol", file: "src/server/services/appearance.ts", exportName: "updateHouseholdAppearance" }] }, target: { authority: "deferred", gateId: "gate.service_operation_linkage" } },
    permission_commit_reauthorization: { current: { authority: "source_reviewed", value: "updateHouseholdAppearance requires household.manage before its upsert and contains no transaction-local membership recheck", sourceReferences: [{ kind: "symbol", file: "src/server/services/appearance.ts", exportName: "updateHouseholdAppearance" }] }, target: { authority: "deferred", gateId: "gate.permission_commit_reauthorization" } },
    tenant_relationship_invariants: { current: { authority: "source_reviewed", value: "the HouseholdSettings upsert key and create data use the selected context householdId", sourceReferences: [{ kind: "symbol", file: "src/server/services/appearance.ts", exportName: "updateHouseholdAppearance" }] }, target: { authority: "deferred", gateId: "gate.tenant_relationship_invariants" } },
    model_reads_writes_effects: { current: { authority: "source_reviewed", value: "the source calls prisma.householdSettings.upsert and then writeAudit with settings.appearance.update", sourceReferences: [{ kind: "symbol", file: "src/server/services/appearance.ts", exportName: "updateHouseholdAppearance" }] }, target: { authority: "deferred", gateId: "gate.model_and_effects" } },
    variant_specific_outcomes: { current: { authority: "not_applicable", rationale: "updateHouseholdAppearance has no declared semantic variant", sourceReferences: [{ kind: "symbol", file: "src/server/services/appearance.ts", exportName: "updateHouseholdAppearance" }] }, target: { authority: "deferred", gateId: "gate.variant_outcomes" } },
    worker_loop_claim_failure_containment: { current: { authority: "not_applicable", rationale: "updateHouseholdAppearance does not contain a worker loop", sourceReferences: [{ kind: "symbol", file: "src/server/services/appearance.ts", exportName: "updateHouseholdAppearance" }] }, target: { authority: "deferred", gateId: "gate.worker_containment" } },
    browser_immutable_binding_stale_behavior: { current: { authority: "deferred", gateId: "gate.browser_binding_staleness" }, target: { authority: "deferred", gateId: "gate.browser_binding_staleness" } },
    executable_evidence_strength: { current: { authority: "deferred", gateId: "gate.executable_evidence" }, target: { authority: "deferred", gateId: "gate.executable_evidence" } }
  }
}] as const satisfies readonly SemanticServiceOperationDeclaration[];
