import type { SemanticServiceOperationDeclaration } from "@/server/operation-registry/schema";

export const semantic = [{ kind: "service", id: "household.accent.update", ownerModule: "src/server/services/appearance.ts", exportName: "submitHouseholdAppearanceBrowserOperation", axes: {
  carrier_authority_guard: { current: { authority: "source_reviewed", value: "Uses the validated effective household member episode.", sourceReferences: [{ kind: "symbol", file: "src/server/services/appearance.ts", exportName: "submitHouseholdAppearanceBrowserOperation" }] }, target: { authority: "deferred", gateId: "gate.carrier_authority_guard" } },
  caller_controlled_scope: { current: { authority: "source_reviewed", value: "Does not accept a household ID from request payload.", sourceReferences: [{ kind: "symbol", file: "src/server/services/appearance.ts", exportName: "submitHouseholdAppearanceBrowserOperation" }] }, target: { authority: "deferred", gateId: "gate.caller_controlled_scope" } },
  service_operation_linkage: { current: { authority: "source_reviewed", value: "Submits household.accent.update.", sourceReferences: [{ kind: "symbol", file: "src/server/services/appearance.ts", exportName: "submitHouseholdAppearanceBrowserOperation" }] }, target: { authority: "deferred", gateId: "gate.service_operation_linkage" } },
  permission_commit_reauthorization: { current: { authority: "source_reviewed", value: "Reauthorizes household.manage in the browser operation transaction.", sourceReferences: [{ kind: "symbol", file: "src/server/services/appearance.ts", exportName: "submitHouseholdAppearanceBrowserOperation" }] }, target: { authority: "deferred", gateId: "gate.permission_commit_reauthorization" } },
  tenant_relationship_invariants: { current: { authority: "source_reviewed", value: "Writes only the locked effective household settings row.", sourceReferences: [{ kind: "symbol", file: "src/server/services/appearance.ts", exportName: "submitHouseholdAppearanceBrowserOperation" }] }, target: { authority: "deferred", gateId: "gate.tenant_relationship_invariants" } },
  model_reads_writes_effects: { current: { authority: "source_reviewed", value: "Writes HouseholdSettings and audit state with the durable result.", sourceReferences: [{ kind: "symbol", file: "src/server/services/appearance.ts", exportName: "submitHouseholdAppearanceBrowserOperation" }] }, target: { authority: "deferred", gateId: "gate.model_and_effects" } },
  variant_specific_outcomes: { current: { authority: "source_reviewed", value: "Returns allowlisted operation outcomes.", sourceReferences: [{ kind: "symbol", file: "src/server/services/appearance.ts", exportName: "submitHouseholdAppearanceBrowserOperation" }] }, target: { authority: "deferred", gateId: "gate.variant_outcomes" } },
  worker_loop_claim_failure_containment: { current: { authority: "not_applicable", rationale: "No worker loop.", sourceReferences: [{ kind: "symbol", file: "src/server/services/appearance.ts", exportName: "submitHouseholdAppearanceBrowserOperation" }] }, target: { authority: "deferred", gateId: "gate.worker_containment" } },
  browser_immutable_binding_stale_behavior: { current: { authority: "deferred", gateId: "gate.browser_binding_staleness" }, target: { authority: "deferred", gateId: "gate.browser_binding_staleness" } },
  executable_evidence_strength: { current: { authority: "deferred", gateId: "gate.executable_evidence" }, target: { authority: "deferred", gateId: "gate.executable_evidence" } }
} }] as const satisfies readonly SemanticServiceOperationDeclaration[];
