import type { SemanticServiceOperationDeclaration } from "@/server/operation-registry/schema";

export const semantic = [{
  kind: "service", id: "calendar_event.create", ownerModule: "src/server/services/calendar.ts", exportName: "submitCalendarEventBrowserOperation",
  axes: {
    carrier_authority_guard: { current: { authority: "source_reviewed", value: "submitCalendarEventBrowserOperation resolves the browser-operation context from the submitted selected baby", sourceReferences: [{ kind: "symbol", file: "src/server/services/calendar.ts", exportName: "submitCalendarEventBrowserOperation" }] }, target: { authority: "deferred", gateId: "gate.carrier_authority_guard" } },
    caller_controlled_scope: { current: { authority: "source_reviewed", value: "submitCalendarEventBrowserOperation parses raw input with calendarEventSchema and derives event instants from that parsed intent", sourceReferences: [{ kind: "symbol", file: "src/server/services/calendar.ts", exportName: "submitCalendarEventBrowserOperation" }] }, target: { authority: "deferred", gateId: "gate.caller_controlled_scope" } },
    service_operation_linkage: { current: { authority: "source_reviewed", value: "submitCalendarEventBrowserOperation is the calendar browser-operation execution adapter", sourceReferences: [{ kind: "symbol", file: "src/server/services/calendar.ts", exportName: "submitCalendarEventBrowserOperation" }] }, target: { authority: "deferred", gateId: "gate.service_operation_linkage" } },
    permission_commit_reauthorization: { current: { authority: "source_reviewed", value: "submitCalendarEventBrowserOperation delegates permission and selected-baby reauthorization to executeBrowserOperation", sourceReferences: [{ kind: "symbol", file: "src/server/services/calendar.ts", exportName: "submitCalendarEventBrowserOperation" }] }, target: { authority: "deferred", gateId: "gate.permission_commit_reauthorization" } },
    tenant_relationship_invariants: { current: { authority: "source_reviewed", value: "submitCalendarEventBrowserOperation supplies the parsed selected baby and immutable intent to executeBrowserOperation", sourceReferences: [{ kind: "symbol", file: "src/server/services/calendar.ts", exportName: "submitCalendarEventBrowserOperation" }] }, target: { authority: "deferred", gateId: "gate.tenant_relationship_invariants" } },
    model_reads_writes_effects: { current: { authority: "source_reviewed", value: "submitCalendarEventBrowserOperation creates the calendar event and audit only through the browser-operation transaction callback", sourceReferences: [{ kind: "symbol", file: "src/server/services/calendar.ts", exportName: "submitCalendarEventBrowserOperation" }] }, target: { authority: "deferred", gateId: "gate.model_and_effects" } },
    variant_specific_outcomes: { current: { authority: "not_applicable", rationale: "submitCalendarEventBrowserOperation has no declared semantic variant", sourceReferences: [{ kind: "symbol", file: "src/server/services/calendar.ts", exportName: "submitCalendarEventBrowserOperation" }] }, target: { authority: "deferred", gateId: "gate.variant_outcomes" } },
    worker_loop_claim_failure_containment: { current: { authority: "not_applicable", rationale: "submitCalendarEventBrowserOperation does not contain a worker loop", sourceReferences: [{ kind: "symbol", file: "src/server/services/calendar.ts", exportName: "submitCalendarEventBrowserOperation" }] }, target: { authority: "deferred", gateId: "gate.worker_containment" } },
    browser_immutable_binding_stale_behavior: { current: { authority: "deferred", gateId: "gate.browser_binding_staleness" }, target: { authority: "deferred", gateId: "gate.browser_binding_staleness" } },
    executable_evidence_strength: { current: { authority: "deferred", gateId: "gate.executable_evidence" }, target: { authority: "deferred", gateId: "gate.executable_evidence" } }
  }
}] as const satisfies readonly SemanticServiceOperationDeclaration[];
