import type { SemanticServiceOperationDeclaration } from "@/server/operation-registry/schema";

export const semantic = [{
  kind: "service", id: "calendar_event.create", ownerModule: "src/server/services/calendar.ts", exportName: "createCalendarEvent",
  axes: {
    carrier_authority_guard: { current: { authority: "source_reviewed", value: "createCalendarEvent calls getHouseholdContext() without a household id, so the helper's current first active membership ordered by joinedAt ascending is selected", sourceReferences: [{ kind: "symbol", file: "src/server/services/calendar.ts", exportName: "createCalendarEvent" }] }, target: { authority: "deferred", gateId: "gate.carrier_authority_guard" } },
    caller_controlled_scope: { current: { authority: "source_reviewed", value: "createCalendarEvent parses raw input with calendarEventSchema and derives start and end instants from submitted fields", sourceReferences: [{ kind: "symbol", file: "src/server/services/calendar.ts", exportName: "createCalendarEvent" }] }, target: { authority: "deferred", gateId: "gate.caller_controlled_scope" } },
    service_operation_linkage: { current: { authority: "source_reviewed", value: "createCalendarEvent is the exported calendar event creation service", sourceReferences: [{ kind: "symbol", file: "src/server/services/calendar.ts", exportName: "createCalendarEvent" }] }, target: { authority: "deferred", gateId: "gate.service_operation_linkage" } },
    permission_commit_reauthorization: { current: { authority: "source_reviewed", value: "createCalendarEvent requires activity.create before its transaction and again after locking the actor and baby, then rejects an inactive baby", sourceReferences: [{ kind: "symbol", file: "src/server/services/calendar.ts", exportName: "createCalendarEvent" }] }, target: { authority: "deferred", gateId: "gate.permission_commit_reauthorization" } },
    tenant_relationship_invariants: { current: { authority: "source_reviewed", value: "createCalendarEvent obtains the submitted baby through lockActorAndBabyForWrite and supplies the locked householdId on event creation", sourceReferences: [{ kind: "symbol", file: "src/server/services/calendar.ts", exportName: "createCalendarEvent" }] }, target: { authority: "deferred", gateId: "gate.tenant_relationship_invariants" } },
    model_reads_writes_effects: { current: { authority: "source_reviewed", value: "the source calls tx.calendarEvent.create with a baby relation and writes a calendar_event.create audit in the transaction", sourceReferences: [{ kind: "symbol", file: "src/server/services/calendar.ts", exportName: "createCalendarEvent" }] }, target: { authority: "deferred", gateId: "gate.model_and_effects" } },
    variant_specific_outcomes: { current: { authority: "not_applicable", rationale: "createCalendarEvent has no declared semantic variant", sourceReferences: [{ kind: "symbol", file: "src/server/services/calendar.ts", exportName: "createCalendarEvent" }] }, target: { authority: "deferred", gateId: "gate.variant_outcomes" } },
    worker_loop_claim_failure_containment: { current: { authority: "not_applicable", rationale: "createCalendarEvent does not contain a worker loop", sourceReferences: [{ kind: "symbol", file: "src/server/services/calendar.ts", exportName: "createCalendarEvent" }] }, target: { authority: "deferred", gateId: "gate.worker_containment" } },
    browser_immutable_binding_stale_behavior: { current: { authority: "deferred", gateId: "gate.browser_binding_staleness" }, target: { authority: "deferred", gateId: "gate.browser_binding_staleness" } },
    executable_evidence_strength: { current: { authority: "deferred", gateId: "gate.executable_evidence" }, target: { authority: "deferred", gateId: "gate.executable_evidence" } }
  }
}] as const satisfies readonly SemanticServiceOperationDeclaration[];
