import type { SemanticServiceOperationDeclaration } from "@/server/operation-registry/schema";

export const semantic = [{
  kind: "service", id: "dashboard.warning.dismiss", ownerModule: "src/server/services/dashboard.ts", exportName: "dismissDashboardWarning",
  axes: {
    carrier_authority_guard: { current: { authority: "source_reviewed", value: "dismissDashboardWarning calls getHouseholdContext() without a household id, so the helper's current first active membership ordered by joinedAt ascending is selected", sourceReferences: [{ kind: "symbol", file: "src/server/services/dashboard.ts", exportName: "dismissDashboardWarning" }] }, target: { authority: "deferred", gateId: "gate.carrier_authority_guard" } },
    caller_controlled_scope: { current: { authority: "source_reviewed", value: "dismissDashboardWarning parses raw input with dismissWarningSchema", sourceReferences: [{ kind: "symbol", file: "src/server/services/dashboard.ts", exportName: "dismissDashboardWarning" }] }, target: { authority: "deferred", gateId: "gate.caller_controlled_scope" } },
    service_operation_linkage: { current: { authority: "source_reviewed", value: "dismissDashboardWarning is the exported dashboard warning dismissal service", sourceReferences: [{ kind: "symbol", file: "src/server/services/dashboard.ts", exportName: "dismissDashboardWarning" }] }, target: { authority: "deferred", gateId: "gate.service_operation_linkage" } },
    permission_commit_reauthorization: { current: { authority: "source_reviewed", value: "dismissDashboardWarning requires activity.read before its baby lookup and upsert and contains no transaction-local membership recheck", sourceReferences: [{ kind: "symbol", file: "src/server/services/dashboard.ts", exportName: "dismissDashboardWarning" }] }, target: { authority: "deferred", gateId: "gate.permission_commit_reauthorization" } },
    tenant_relationship_invariants: { current: { authority: "source_reviewed", value: "the source checks the submitted baby id with the selected household id and keys the dismissal upsert by that household and baby", sourceReferences: [{ kind: "symbol", file: "src/server/services/dashboard.ts", exportName: "dismissDashboardWarning" }] }, target: { authority: "deferred", gateId: "gate.tenant_relationship_invariants" } },
    model_reads_writes_effects: { current: { authority: "source_reviewed", value: "the source calls prisma.baby.findFirst and prisma.dashboardWarningDismissal.upsert", sourceReferences: [{ kind: "symbol", file: "src/server/services/dashboard.ts", exportName: "dismissDashboardWarning" }] }, target: { authority: "deferred", gateId: "gate.model_and_effects" } },
    variant_specific_outcomes: { current: { authority: "not_applicable", rationale: "dismissDashboardWarning has no declared semantic variant", sourceReferences: [{ kind: "symbol", file: "src/server/services/dashboard.ts", exportName: "dismissDashboardWarning" }] }, target: { authority: "deferred", gateId: "gate.variant_outcomes" } },
    worker_loop_claim_failure_containment: { current: { authority: "not_applicable", rationale: "dismissDashboardWarning does not contain a worker loop", sourceReferences: [{ kind: "symbol", file: "src/server/services/dashboard.ts", exportName: "dismissDashboardWarning" }] }, target: { authority: "deferred", gateId: "gate.worker_containment" } },
    browser_immutable_binding_stale_behavior: { current: { authority: "deferred", gateId: "gate.browser_binding_staleness" }, target: { authority: "deferred", gateId: "gate.browser_binding_staleness" } },
    executable_evidence_strength: { current: { authority: "deferred", gateId: "gate.executable_evidence" }, target: { authority: "deferred", gateId: "gate.executable_evidence" } }
  }
}] as const satisfies readonly SemanticServiceOperationDeclaration[];
