import type { SemanticServiceOperationDeclaration } from "@/server/operation-registry/schema";

export const semantic = [{
  kind: "service", id: "dashboard.warning.dismiss", ownerModule: "src/server/services/dashboard.ts", exportName: "dismissDashboardWarningBrowserOperation",
  axes: {
    carrier_authority_guard: { current: { authority: "source_reviewed", value: "dismissDashboardWarningBrowserOperation resolves the browser-operation context from the submitted selected baby", sourceReferences: [{ kind: "symbol", file: "src/server/services/dashboard.ts", exportName: "dismissDashboardWarningBrowserOperation" }] }, target: { authority: "deferred", gateId: "gate.carrier_authority_guard" } },
    caller_controlled_scope: { current: { authority: "source_reviewed", value: "dismissDashboardWarningBrowserOperation parses raw input with dismissWarningSchema", sourceReferences: [{ kind: "symbol", file: "src/server/services/dashboard.ts", exportName: "dismissDashboardWarningBrowserOperation" }] }, target: { authority: "deferred", gateId: "gate.caller_controlled_scope" } },
    service_operation_linkage: { current: { authority: "source_reviewed", value: "dismissDashboardWarningBrowserOperation is the dashboard warning browser-operation execution adapter", sourceReferences: [{ kind: "symbol", file: "src/server/services/dashboard.ts", exportName: "dismissDashboardWarningBrowserOperation" }] }, target: { authority: "deferred", gateId: "gate.service_operation_linkage" } },
    permission_commit_reauthorization: { current: { authority: "source_reviewed", value: "dismissDashboardWarningBrowserOperation delegates permission and selected-baby reauthorization to executeBrowserOperation", sourceReferences: [{ kind: "symbol", file: "src/server/services/dashboard.ts", exportName: "dismissDashboardWarningBrowserOperation" }] }, target: { authority: "deferred", gateId: "gate.permission_commit_reauthorization" } },
    tenant_relationship_invariants: { current: { authority: "source_reviewed", value: "dismissDashboardWarningBrowserOperation supplies the parsed selected baby and immutable warning intent to executeBrowserOperation", sourceReferences: [{ kind: "symbol", file: "src/server/services/dashboard.ts", exportName: "dismissDashboardWarningBrowserOperation" }] }, target: { authority: "deferred", gateId: "gate.tenant_relationship_invariants" } },
    model_reads_writes_effects: { current: { authority: "source_reviewed", value: "dismissDashboardWarningBrowserOperation rederives the warning and writes the dismissal only through the browser-operation transaction callback", sourceReferences: [{ kind: "symbol", file: "src/server/services/dashboard.ts", exportName: "dismissDashboardWarningBrowserOperation" }] }, target: { authority: "deferred", gateId: "gate.model_and_effects" } },
    variant_specific_outcomes: { current: { authority: "not_applicable", rationale: "dismissDashboardWarningBrowserOperation has no declared semantic variant", sourceReferences: [{ kind: "symbol", file: "src/server/services/dashboard.ts", exportName: "dismissDashboardWarningBrowserOperation" }] }, target: { authority: "deferred", gateId: "gate.variant_outcomes" } },
    worker_loop_claim_failure_containment: { current: { authority: "not_applicable", rationale: "dismissDashboardWarningBrowserOperation does not contain a worker loop", sourceReferences: [{ kind: "symbol", file: "src/server/services/dashboard.ts", exportName: "dismissDashboardWarningBrowserOperation" }] }, target: { authority: "deferred", gateId: "gate.worker_containment" } },
    browser_immutable_binding_stale_behavior: { current: { authority: "deferred", gateId: "gate.browser_binding_staleness" }, target: { authority: "deferred", gateId: "gate.browser_binding_staleness" } },
    executable_evidence_strength: { current: { authority: "deferred", gateId: "gate.executable_evidence" }, target: { authority: "deferred", gateId: "gate.executable_evidence" } }
  }
}] as const satisfies readonly SemanticServiceOperationDeclaration[];
