import { existsSync, readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { describe, expect, it } from "vitest";

const schemaPath = fileURLToPath(new URL("../../../prisma/schema.prisma", import.meta.url));
const migrationPath = fileURLToPath(new URL("../../../prisma/migrations/20260824140000_global_security_foundation/migration.sql", import.meta.url));
const phase8MigrationPath = fileURLToPath(new URL("../../../prisma/migrations/20260829120000_global_security_throttle_core/migration.sql", import.meta.url));
const phase8CarrierMigrationPath = fileURLToPath(new URL("../../../prisma/migrations/20260829170000_global_security_phase8_carriers/migration.sql", import.meta.url));
const acceptancePath = fileURLToPath(new URL("../../../scripts/p1-3-global-security-phase1.acceptance-rehearsal.ts", import.meta.url));
const globalSecurityServicePath = fileURLToPath(new URL("global-security.ts", import.meta.url));
const recoveryServicePath = fileURLToPath(new URL("recovery-lifecycle.ts", import.meta.url));
const inviteServicePath = fileURLToPath(new URL("invites.ts", import.meta.url));
const models = [
  "AccountSecurityState", "FreshAuthGrant", "RecoveryCodeSet", "RecoveryCode", "RecoverySession",
  "GlobalSecurityOperationBinding", "GlobalSecurityOperation", "GlobalSecurityOperationTombstone",
  "GlobalSecurityOperationReservationTombstone",
  "GlobalSecurityEvent", "GlobalSecurityIncident", "EmailChange", "SessionSecurityActivity"
];

describe("global security persistence foundation", () => {
  it("adds the Phase 8 append-only sequence, incident binding, and owner-only throttle-key persistence", () => {
    const schema = readFileSync(schemaPath, "utf8");
    expect(existsSync(phase8MigrationPath)).toBe(true);
    const migration = readFileSync(phase8MigrationPath, "utf8");

    expect(schema).toMatch(/model GlobalSecurityEvent \{[\s\S]*sequence\s+BigInt\s+@default\(autoincrement\(\)\)\s+@unique[\s\S]*incidentId\s+String\?\s+@unique/);
    expect(schema).toMatch(/model GlobalSecurityIncident \{[\s\S]*events\s+GlobalSecurityEvent\[\]/);
    expect(schema).toMatch(/model GlobalSecurityThrottleKey \{[\s\S]*singletonId\s+Int\s+@id[\s\S]*keyDigest\s+Bytes/);
    expect(migration).toContain('ADD COLUMN "sequence" BIGINT GENERATED BY DEFAULT AS IDENTITY');
    expect(migration).toContain('ADD COLUMN "incidentId" TEXT');
    expect(migration).toContain('GlobalSecurityEvent_incidentId_fkey');
    expect(migration).toContain('CREATE UNIQUE INDEX "GlobalSecurityEvent_incidentId_key"');
    expect(migration).toContain('CREATE INDEX "GlobalSecurityEvent_userId_sequence_idx"');
    expect(migration).toContain('CREATE TABLE "GlobalSecurityThrottleKey"');
    expect(migration).toContain('GlobalSecurityThrottleKey_singleton_check');
    expect(migration).toContain('GlobalSecurityThrottleKey_digest_check');
  });

  it("keeps Phase 8 throttling database-clock, locked, neutral, and inaccessible except through definer procedures", () => {
    const migration = readFileSync(phase8MigrationPath, "utf8");
    for (const procedure of ["global_security_throttle_precheck", "global_security_throttle_failure"]) {
      expect(migration).toContain(`CREATE OR REPLACE FUNCTION "${procedure}"`);
      expect(migration).toContain('SECURITY DEFINER SET search_path=pg_catalog,public');
    }
    expect(migration).toContain("hashtextextended('global-security-transition:v1', 0)");
    expect(migration).toContain("global-security-incident:v1:");
    expect(migration).toContain("extract(epoch FROM clock_timestamp())/900");
    expect(migration).toContain('"failureCount"=LEAST(255,"failureCount"+1)');
    expect(migration).toContain("EXCEPTION WHEN unique_violation THEN");
    expect(migration).toContain('"quietUntil"=now_time+INTERVAL \'15 minutes\'');
    expect(migration).toContain('"quietUntil" IS DISTINCT FROM OLD."quietUntil"');
    expect(migration).toContain("layer_name='account_identifier'");
    expect(migration).toContain("'throttle','quiet_started'");
    expect(migration).toContain('REVOKE ALL ON TABLE "GlobalSecurityEvent","GlobalSecurityIncident","GlobalSecurityThrottleKey" FROM cubby_runtime');
    expect(migration).toContain('GRANT EXECUTE ON FUNCTION "global_security_throttle_precheck"');
    const writer = migration.slice(migration.indexOf('CREATE OR REPLACE FUNCTION "write_global_security_event"'));
    expect(writer).not.toContain('UPDATE public."GlobalSecurityIncident"');
  });

  it("keeps Phase 8 class events at their authoritative transition owners with guarded operation cardinality", () => {
    expect(existsSync(phase8CarrierMigrationPath)).toBe(true);
    const migration = readFileSync(phase8CarrierMigrationPath, "utf8");

    expect(migration).toContain('CREATE OR REPLACE FUNCTION "guard_global_security_phase8_carrier_event"()');
    expect(migration).toContain("'current_password_verified'");
    expect(migration).toContain('"EmailChange_phase8_class_events"');
    expect(migration).toContain('AFTER INSERT OR UPDATE OF "state" ON public."EmailChange"');
    expect(migration).toContain('"GlobalSecurityOperation_phase8_session_events"');
    expect(migration).toContain('"SessionSecurityActivity_phase8_expired_event"');
    expect(migration).toContain('ON CONFLICT ("userId","operationId","eventType","outcome")');
    expect(migration).toContain('SECURITY DEFINER SET search_path=pg_catalog,public');
    expect(migration).not.toContain('GRANT EXECUTE');
  });

  it("backfills live sessions and makes ordinary session activity issuance idempotent at the database clock", () => {
    const migration = readFileSync(migrationPath, "utf8");

    expect(migration).toContain('INSERT INTO public."AccountSecurityState" ("userId","credentialVersion","sessionSecurityVersion","securityUpdatedAt") SELECT DISTINCT "userId",1,1,clock_timestamp() FROM public."Session" WHERE "expiresAt">clock_timestamp()');
    expect(migration).toContain('INSERT INTO public."SessionSecurityActivity" ("sessionId","userId","issuanceSessionSecurityVersion","originalCreatedAt","lastQualifyingAt","state","updatedAt") SELECT session_row."id",session_row."userId",state_row."sessionSecurityVersion",session_row."createdAt",session_row."createdAt",\'active\',clock_timestamp() FROM public."Session" session_row JOIN public."AccountSecurityState" state_row ON state_row."userId"=session_row."userId" WHERE session_row."expiresAt">clock_timestamp()');
    expect(migration).toContain('CREATE FUNCTION "initialize_global_session_security_activity"(scope_user_id TEXT, scope_session_id TEXT)');
    expect(migration).toContain('ON CONFLICT ("sessionId") DO NOTHING');
    expect(migration).toContain('INSERT INTO public."AccountSecurityState" ("userId","credentialVersion","sessionSecurityVersion","securityUpdatedAt") SELECT scope_user_id,1,1,clock_timestamp() WHERE EXISTS (SELECT 1 FROM public."User" WHERE "id"=scope_user_id)');
    expect(migration).toContain('VALUES (session_row."id",session_row."userId",state_row."sessionSecurityVersion",session_row."createdAt",session_row."createdAt",NULL,\'active\',clock_timestamp())');
    expect(migration).toContain('session_row."expiresAt" <= clock_timestamp()');
    expect(migration).toContain('NEW."originalCreatedAt" IS DISTINCT FROM session_row."createdAt"');
  });

  it("binds every session activity to an immutable issuance vector and only permits the email-cutover successor exception", () => {
    const schema = readFileSync(schemaPath, "utf8");
    const migration = readFileSync(migrationPath, "utf8");

    expect(schema).toMatch(/model SessionSecurityActivity \{[\s\S]*issuanceSessionSecurityVersion\s+Int[\s\S]*originalCreatedAt/);
    expect(migration).toContain('"issuanceSessionSecurityVersion" INTEGER NOT NULL');
    expect(migration).toContain('NEW."issuanceSessionSecurityVersion" IS DISTINCT FROM state_row."sessionSecurityVersion"');
    expect(migration).toContain('NEW."issuanceSessionSecurityVersion" IS DISTINCT FROM change_row."sessionSecurityVersion"+1');
    expect(migration).toContain("session_security_activity_issuance_version_invalid");
    expect(migration).toContain('NEW."issuanceSessionSecurityVersion" IS DISTINCT FROM OLD."issuanceSessionSecurityVersion"');
    expect(migration).toContain('old_activity."issuanceSessionSecurityVersion" IS DISTINCT FROM change_row."sessionSecurityVersion"');
    expect(migration).toContain('VALUES (successor_session_id,scope_user_id,change_row."sessionSecurityVersion"+1,old_activity."originalCreatedAt",now_time,\'active\',now_time)');
  });

  it("authorizes global sessions through one fixed-search-path procedure that expires, warns, and only accepts classified qualifying use", () => {
    const migration = readFileSync(migrationPath, "utf8");

    expect(migration).toContain('CREATE FUNCTION "authorize_global_session_security"(scope_user_id TEXT, scope_session_id TEXT, qualifying_use TEXT)');
    expect(migration).toContain('SECURITY DEFINER SET search_path=pg_catalog,public');
    expect(migration).toContain("hashtextextended('global-security-transition:v1', 0)");
    expect(migration).toContain('clock_timestamp() >= effective_expiry');
    expect(migration).toContain("'expired'::public.\"SessionSecurityActivityState\"");
    expect(migration).toContain('DELETE FROM public."Session" WHERE "id"=session_row."id" AND "userId"=scope_user_id');
    const authorization = migration.slice(migration.indexOf('CREATE FUNCTION "authorize_global_session_security"'));
    expect(authorization.indexOf('SELECT * INTO state_row FROM public."AccountSecurityState" WHERE "userId"=scope_user_id FOR UPDATE;')).toBeLessThan(authorization.indexOf('SELECT * INTO session_row FROM public."Session" WHERE "id"=scope_session_id AND "userId"=scope_user_id FOR UPDATE;'));
    expect(authorization).toContain('activity_row."issuanceSessionSecurityVersion" IS DISTINCT FROM state_row."sessionSecurityVersion"');
    expect(authorization).toContain('UPDATE public."SessionSecurityActivity" SET "state"=\'revoked\',"updatedAt"=now_time WHERE "sessionId"=scope_session_id AND "state"=\'active\';');
    expect(migration).toContain("qualifying_use NOT IN ('foreground_document_navigation','cubby_owned_non_get_mutation','private_security_action')");
    expect(migration).toContain('activity_row."warningAt" IS NULL AND now_time >= effective_expiry - INTERVAL \'7 days\'');
    expect(migration).toContain('REVOKE ALL ON FUNCTION "authorize_global_session_security"(TEXT,TEXT,TEXT) FROM PUBLIC');
  });

  it("adds the complete user-owned security model and SQL guard foundation before user-facing flows", () => {
    const schema = readFileSync(schemaPath, "utf8");
    expect(existsSync(migrationPath)).toBe(true);
    const migration = readFileSync(migrationPath, "utf8");

    for (const model of models) expect(schema).toContain(`model ${model} {`);
    expect(schema).toMatch(/securityState\s+AccountSecurityState\?/);
    expect(schema).toMatch(/globalSecurityEvents\s+GlobalSecurityEvent\[\]/);
    expect(migration).toContain("lock_global_security_operation_identity_v1");
    expect(migration).toContain("GlobalSecurityEvent_append_only");
    expect(migration).toContain("REVOKE ALL ON FUNCTION");

    expect(migration).toContain("AccountSecurityState_versions_check");
    expect(migration).toContain("FreshAuthGrant_one_live_purpose");
    expect(migration).toContain("EmailChange_one_live_change");
    expect(migration).toContain("GlobalSecurityBinding_identity_insert_guard");

    expect(migration).toContain("GlobalSecurityOperation_binding_claim_guard");
    expect(migration).toContain("global_security_binding_initial_state_invalid");
    expect(migration).toContain("global_security_operation_initial_state_invalid");
    expect(migration).toContain("global_security_binding_current_authorization_required");
    expect(migration).toContain("global_security_binding_expired_before_deadline");
    expect(migration).toContain("global_security_reservation_tombstone_terminal_invalid");
    expect(migration).toContain("global_security_terminal_outcome_invalid");
    expect(migration).toContain("global_security_binding_claim_after_expiry");
    expect(migration).toContain("fresh_auth_grant_initially_expired");
    expect(migration).toContain("fresh_auth_grant_current_authorization_required");
    expect(migration).toContain("fresh_auth_grant_operation_binding_mismatch");
    expect(migration).toContain("recovery_session_initially_expired");
    expect(migration).toContain("recovery_session_consumed_after_expiry");
    expect(migration).toContain("GlobalSecurityOperationBinding_recovery_session_shape");
    expect(migration).toContain("global_security_recovery_binding_authorization_required");
    expect(schema).toMatch(/recoverySessionId\s+String\?/);
    expect(migration).toContain("current_password_invalid");
    expect(migration).toContain("reset_completed");
    expect(migration).toContain("fresh_auth_grant_session_or_version_invalid");
    expect(migration).toContain("GlobalSecurityTombstone_insert_guard");
    expect(migration).toContain("GlobalSecurityBinding_write_once");
    expect(migration).toContain("GlobalSecurityOperation_terminal_write_once");
    expect(migration).toContain("GlobalSecurityReservationTombstone_insert_guard");
    expect(migration).toContain("GlobalSecurityOperationTombstone_write_once");
    expect(migration).toContain("FreshAuthGrant_state_guard");
    expect(migration).toContain("RecoveryCode_single_consume");
    expect(migration).toContain("RecoverySession_state_guard");
    expect(migration).toContain("EmailChange_state_guard");
    expect(migration).toContain("AccountSecurityState_version_guard");
  });

  it("rejects every direct lifecycle bypass while permitting only user-deletion cascades", () => {
    const migration = readFileSync(migrationPath, "utf8");

    expect(migration).not.toContain("cubby.global_security_account_deletion_user_id");
    expect(migration).not.toContain("global_security_account_deletion_authorized");
    expect(migration).toContain('NOT EXISTS (SELECT 1 FROM "User" WHERE "id" = OLD."userId")');
    const deleteGuardPrefixes = ["BEFORE INSERT OR UPDATE OR DELETE", "BEFORE UPDATE OR DELETE", "BEFORE DELETE"];
    for (const table of [
      "AccountSecurityState", "FreshAuthGrant", "RecoveryCode", "RecoverySession",
      "GlobalSecurityOperationBinding", "GlobalSecurityOperation", "GlobalSecurityOperationTombstone",
      "GlobalSecurityOperationReservationTombstone", "GlobalSecurityEvent", "GlobalSecurityIncident",
      "EmailChange", "SessionSecurityActivity"
    ]) {
      expect(deleteGuardPrefixes.some((prefix) => migration.includes(`${prefix} ON "${table}"`))).toBe(true);
    }

    expect(migration).toContain('operation_row."bindingId" IS DISTINCT FROM OLD."id"');
    expect(migration).toContain('bound."state" <> \'submitted\'');
    expect(migration).toContain("global_security_operation_missing_submitted_binding");
    expect(migration).toContain('OLD."status" = \'pending\' AND NEW."status" = \'unknown\'');
    expect(migration).toContain('"outcomeVersion" = 1');
    expect(migration).toContain("FreshAuthGrant_initial_state_guard");
    expect(migration).toContain("RecoveryCode_initial_state_guard");
    expect(migration).toContain("RecoverySession_initial_state_guard");
    expect(migration).toContain("EmailChange_initial_state_guard");
    expect(migration).toContain("email_change_fresh_grant_operation_mismatch");
    expect(migration).toContain('grant_row."purpose" <> \'email_change\'');
    expect(migration).toContain('operation_row."operationKey" <> \'email_change\'');
    expect(migration).toContain('grant_row."credentialVersion" IS DISTINCT FROM NEW."securityVersion"');
    expect(migration).toContain('bound."state" <> \'submitted\'');
    expect(migration).toContain('session_row."expiresAt" <= clock_timestamp()');
    expect(migration).toContain('grant_row."state" NOT IN (\'issued\', \'expired\')');
    expect(migration).toContain("fresh_auth_grant_consumed_after_expiry");
    expect(migration).toContain("fresh_auth_grant_expired_before_deadline");
    expect(migration).toContain('OLD."state" IN (\'pending\',\'verified\') AND NEW."state"=\'expired\'');
    expect(migration).toContain("email_change_deadline_passed");
    expect(migration).toContain('OLD."state" = \'verified\' AND NEW."state" = \'completed\'');
    expect(migration).toContain('NEW."state" = \'cancelled\' AND NEW."cancelledAt" IS NOT NULL');
  });

  it("makes retention and cross-record security bindings database-enforced rather than session-configurable", () => {
    const schema = readFileSync(schemaPath, "utf8");
    const migration = readFileSync(migrationPath, "utf8");

    expect(migration).not.toContain("pg_trigger_depth()");
    for (const table of models) {
      expect(migration).toContain(`BEFORE TRUNCATE ON "${table}"`);
    }
    expect(migration).toContain("GlobalSecurityOperationTombstone_terminal_status_mismatch");
    expect(migration).toContain('NEW."terminalStatus" IS DISTINCT FROM operation_row."status"');
    expect(migration).toContain('grant_row."operationId" IS DISTINCT FROM NEW."operationId"');
    expect(migration).toContain("assert_email_change_current_authorization");
    expect(migration).toContain('state_row."userId" IS NULL');
    expect(migration).toContain('grant_row."id" IS NULL');
    expect(migration).toContain('grant_row."purpose" <> \'email_change\'');
    expect(migration).toContain('operation_row."bindingId" IS NULL');
    expect(migration).toContain('operation_row."status" NOT IN (\'pending\', \'unknown\')');
    expect(migration).toContain('bound."id" IS NULL');
    expect(migration).toContain('bound."state" <> \'submitted\'');
    expect(migration).toContain('bound."sessionId" IS DISTINCT FROM grant_row."sessionId"');
    expect(migration).toContain('session_row."id" IS NULL');
    expect(migration).toContain('session_row."userId" IS DISTINCT FROM scope_user_id');
    expect(migration).toContain('IF NEW."state" = \'expired\' THEN');
    expect(migration).toContain('IF NEW."expiresAt" > clock_timestamp() THEN RAISE EXCEPTION \'email_change_not_expired\'');
    expect(migration).toContain("recovery_session_recovery_code_not_consumed");
    expect(migration).toContain("RecoveryCodeSet_exact_ten_guard");
    expect(migration).toContain("recovery_code_security_state_missing");
    expect(migration).toContain('NEW."purpose" IS DISTINCT FROM OLD."purpose"');
    expect(migration).toContain("SessionSecurityActivity_write_once");
    expect(migration).toContain("SessionSecurityActivity_initial_state_guard");
    expect(migration).toContain("session_security_activity_session_mismatch");
    expect(migration).toContain('NEW."originalCreatedAt" IS DISTINCT FROM session_row."createdAt"');
    expect(migration).toContain("session_security_activity_qualifying_time_invalid");
    expect(migration).toContain("session_security_activity_warning_invalid");
    expect(migration).toContain("session_security_activity_transition_invalid");
    expect(schema).toMatch(/state\s+SessionSecurityActivityState\s+@default\(active\)/);
    expect(migration).toContain("GlobalSecurityIncident_initial_state_guard");
    expect(migration).toContain("GlobalSecurityIncident_state_guard");
    expect(migration).toContain("global_security_incident_identity_immutable");
    expect(migration).toContain("global_security_incident_counter_regression");
    expect(migration).toContain("global_security_incident_transition_invalid");
    expect(migration).not.toContain("FreshAuthGrant_userId_sessionId_fkey");
    expect(migration).not.toContain("GlobalSecurityOperationBinding_userId_sessionId_fkey");
    expect(migration).not.toContain("SessionSecurityActivity_userId_sessionId_fkey");
    expect(migration).not.toContain("RecoverySession_userId_recoveryCodeId_fkey");
    expect(migration).toContain('GlobalSecurityOperation_bindingId_fkey" FOREIGN KEY ("bindingId") REFERENCES "GlobalSecurityOperationBinding"("id") ON DELETE CASCADE');
    expect(migration).toContain('EmailChange_freshAuthGrantId_fkey" FOREIGN KEY ("freshAuthGrantId") REFERENCES "FreshAuthGrant"("id") ON DELETE CASCADE');
    expect(schema).toMatch(/binding\s+GlobalSecurityOperationBinding\s+@relation\(fields: \[bindingId\], references: \[id\], onDelete: Cascade\)/);
    expect(schema).toMatch(/freshAuthGrant\s+FreshAuthGrant\s+@relation\(fields: \[freshAuthGrantId\], references: \[id\], onDelete: Cascade\)/);
    expect(schema).toMatch(/model RecoverySession \{[\s\S]*purpose\s+String\s+@default\("recovery_reset"\)/);
  });

  it("closes operation lifecycle authorization over exactly one ordinary or restricted recovery carrier", () => {
    const schema = readFileSync(schemaPath, "utf8");
    const migration = readFileSync(migrationPath, "utf8");
    const acceptance = readFileSync(acceptancePath, "utf8");

    expect(migration).toContain("scope_operation_key \"GlobalSecurityOperationKey\"");
    expect(migration).toContain("IF scope_operation_key = 'recovery_reset' THEN");
    expect(migration).toContain("scope_session_id IS NOT NULL OR scope_recovery_session_id IS NULL");
    expect(migration).toContain("scope_session_id IS NULL OR scope_recovery_session_id IS NOT NULL");
    expect(migration.match(/assert_global_security_binding_current_authorization/g)).toHaveLength(5);
    expect(migration).toContain('bound."operationKey", bound."securityVersion"');
    expect(migration).toContain('OLD."operationKey", OLD."securityVersion"');
    expect(migration).toContain('NEW."recoverySessionId" IS DISTINCT FROM OLD."recoverySessionId"');

    expect(schema).toMatch(/model GlobalSecurityOperationReservationTombstone \{[\s\S]*sessionId\s+String\?[\s\S]*recoverySessionId\s+String\?/);
    expect(migration).toContain("GlobalSecurityOperationReservationTombstone_recovery_session_shape");
    expect(migration).toContain('bound."recoverySessionId" IS DISTINCT FROM NEW."recoverySessionId"');
    expect(migration).toContain("recovery_session_successful_reset_required");

    for (const marker of [
      "recovery_carrier_valid_replay",
      "recovery_carrier_missing",
      "recovery_carrier_foreign_user",
      "recovery_carrier_operation_mismatch",
      "recovery_carrier_wrong_purpose",
      "recovery_carrier_consumed",
      "recovery_carrier_closed",
      "recovery_carrier_expired",
      "recovery_carrier_non_recovery_operation",
      "ordinary_session_recovery_reset"
    ]) expect(acceptance).toContain(marker);
  });

  it("permits only identity-matched stale-version terminalization without protected mutation", () => {
    const migration = readFileSync(migrationPath, "utf8");
    const acceptance = readFileSync(acceptancePath, "utf8");

    expect(migration).toContain("assert_global_security_stale_finalization");
    expect(migration).toContain("expected_version IS NOT DISTINCT FROM state_row.\"credentialVersion\"");
    expect(migration).toContain("NEW.\"status\" = 'stale' AND NEW.\"outcomeCode\" = 'stale_security_version'");
    expect(migration).toContain("operation_row.\"status\" = 'stale' AND operation_row.\"outcomeCode\" = 'stale_security_version'");
    expect(migration).toContain("global_security_stale_finalization_invalid");

    for (const marker of [
      "stale_security_version_password_finalization",
      "stale_security_version_recovery_finalization",
      "session_security_version_only_stale_finalization",
      "stale_security_version_nonmatching_outcome_rejected",
      "stale_security_version_current_version_rejected",
      "stale_security_version_protected_state_unchanged"
    ]) expect(acceptance).toContain(marker);
  });

  it("applies the complete foundation atomically and rehearses injected rollback", () => {
    const migration = readFileSync(migrationPath, "utf8").trim();
    const acceptance = readFileSync(acceptancePath, "utf8");

    expect(migration.startsWith("BEGIN;\n")).toBe(true);
    expect(migration.endsWith("\nCOMMIT;")).toBe(true);
    expect(acceptance).toContain("P1_3_GLOBAL_SECURITY_PHASE1_ROLLBACK_PASS");
    expect(acceptance).toContain("p1_3_phase1_injected_migration_failure");
    expect(acceptance).toContain("p1_3_phase1_rollback_left_objects");
  });

  it("runs acceptance from a tracked-only temporary Prisma tree and an environment allowlist", () => {
    const acceptance = readFileSync(acceptancePath, "utf8");

    expect(acceptance).not.toContain("...process.env");
    expect(acceptance).not.toContain('cpSync(resolve(root, "prisma")');
    expect(acceptance).toContain('["ls-files", "-z", "--", "prisma/schema.prisma", "prisma/migrations"]');
    expect(acceptance).toContain("copyTrackedPrisma");
    expect(acceptance).toContain("cwd: temporaryRoot");
    expect(acceptance).toContain("p1_3_phase1_tracked_prisma_inventory_invalid");
  });

  it("reserves success finalization and attributes version changes before allowing stale results", () => {
    const schema = readFileSync(schemaPath, "utf8");
    const migration = readFileSync(migrationPath, "utf8");
    const acceptance = readFileSync(acceptancePath, "utf8");

    expect(schema).toMatch(/lastCredentialOperationId\s+String\?/);
    expect(schema).toMatch(/lastSessionSecurityOperationId\s+String\?/);
    expect(migration).toContain("account_security_version_attribution_required");
    expect(migration).toContain('state_row."lastCredentialOperationId" IS NOT DISTINCT FROM scope_operation_id');
    expect(migration).toContain('state_row."lastSessionSecurityOperationId" IS NOT DISTINCT FROM scope_operation_id');
    expect(migration).toContain("global_security_success_finalization_not_enabled");
    expect(acceptance).toContain("phase1_forged_success_rejected");
    expect(acceptance).toContain("phase1_mutate_then_stale_rejected");
  });

  it("serializes every cross-record transition before row locks can invert", () => {
    const migration = readFileSync(migrationPath, "utf8");
    const acceptance = readFileSync(acceptancePath, "utf8");

    expect(migration).toContain("lock_global_security_transition_v1");
    for (const table of ["GlobalSecurityOperation", "GlobalSecurityOperationBinding", "FreshAuthGrant", "EmailChange"]) {
      expect(migration).toContain(`BEFORE INSERT OR UPDATE ON "${table}" FOR EACH STATEMENT EXECUTE FUNCTION "lock_global_security_transition_v1"()`);
    }
    expect(acceptance).toContain("global_security_transition_wait_observed");
    expect(acceptance).toContain("pg_blocking_pids");
  });

  it("admits only content-free operation-bound private events during Phase 1", () => {
    const migration = readFileSync(migrationPath, "utf8");
    const acceptance = readFileSync(acceptancePath, "utf8");

    expect(migration).toContain("GlobalSecurityEvent_insert_guard");
    expect(migration).toContain("global_security_event_insert_invalid");
    expect(migration).toContain("NEW.\"safeProjection\" <> '{}'::jsonb");
    expect(migration).toContain("operation_row.\"status\" = 'rejected'");
    expect(migration).toContain("operation_row.\"status\" = 'stale'");
    expect(acceptance).toContain("private_event_secret_projection_rejected");
    expect(acceptance).toContain("private_event_unknown_type_rejected");
  });

  it("binds account incidents to users and keeps client/deployment incidents account-neutral", () => {
    const migration = readFileSync(migrationPath, "utf8");
    const acceptance = readFileSync(acceptancePath, "utf8");

    expect(migration).toContain("global_security_incident_layer_owner_invalid");
    expect(migration).toContain("NEW.\"layer\"='account_identifier' AND NEW.\"userId\" IS NULL");
    expect(migration).toContain("NEW.\"layer\" IN ('client','deployment') AND NEW.\"userId\" IS NOT NULL");
    expect(acceptance).toContain("account_incident_without_user_rejected");
    expect(acceptance).toContain("neutral_incident_with_user_rejected");
  });

  it("enforces a closed fresh-auth purpose-by-operation matrix", () => {
    const migration = readFileSync(migrationPath, "utf8");
    const acceptance = readFileSync(acceptancePath, "utf8");

    for (const pair of ["password_change|password_change", "recovery_enrollment|recovery_enrollment", "email_change|email_change", "session_revoke|session_revoke"]) expect(migration).toContain(pair);
    expect(migration).toContain("fresh_auth_grant_purpose_operation_mismatch");
    expect(acceptance).toContain("fresh_auth_cross_purpose_rejected");
  });

  it("requires a server-verifiable session-revoke attestation bound to the canonical target snapshot", () => {
    const migration = readFileSync(migrationPath, "utf8");

    expect(migration).toContain('CREATE FUNCTION "verify_session_revoke_attestation"');
    expect(migration).toContain("session-revoke-attestation-v1");
    expect(migration).toContain("'absent_target_handle'");
    expect(migration).toContain("'absent_target_session_id'");
    expect(migration).toContain("fresh_auth_session_revoke_attestation_invalid");
    expect(migration).toContain('"rotatedAt">clock_timestamp()-INTERVAL \'10 minutes\'');
  });

  it("limits scoped session revocation to its guarded SECURITY DEFINER completion procedure", () => {
    const migration = readFileSync(migrationPath, "utf8");
    const completion = migration.slice(migration.indexOf('CREATE FUNCTION "complete_session_revoke"'));

    expect(completion).toContain('SECURITY DEFINER SET search_path=pg_catalog,public');
    expect(completion).toContain("hashtextextended('global-security-transition:v1',0)");
    expect(completion).toContain('UPDATE public."SessionSecurityActivity" SET "state"=\'revoked\'');
    expect(completion).toContain('DELETE FROM public."Session"');
    expect(completion).toContain('"lastSessionSecurityOperationId"=scope_operation_id');
    expect(completion).toContain("'revoked'");
    expect(completion).toContain("'already_revoked'");
    expect(migration).toContain('"complete_session_revoke"(TEXT,TEXT,TEXT,TEXT,TEXT),"get_session_revoke_status"(TEXT,TEXT,TEXT,TEXT,TEXT),"get_session_revoke_retry_target"(TEXT,TEXT,TEXT,TEXT,TEXT) TO cubby_runtime');
  });

  it("rejects fresh-auth consumption after a session-security-vector change or unknown operation outcome", () => {
    const migration = readFileSync(migrationPath, "utf8");
    const acceptance = readFileSync(acceptancePath, "utf8");
    expect(migration).toContain("fresh_auth_grant_session_security_version_invalid");
    expect(migration).toContain("fresh_auth_grant_operation_not_consumable");
    expect(migration).toContain('state_row."sessionSecurityVersion" IS DISTINCT FROM bound."sessionSecurityVersion"');
    expect(migration).toContain('operation_row."status" <> \'pending\'');
    expect(acceptance).toContain("fresh_auth_session_security_version_rejected");
  });

  it("requires one credential account and a submitted current-vector binding before a fresh-auth grant can commit", () => {
    const migration = readFileSync(migrationPath, "utf8");
    const acceptance = readFileSync(acceptancePath, "utf8");
    expect(migration).toContain('CREATE UNIQUE INDEX "Account_one_credential_per_user" ON "Account"("userId") WHERE "providerId" = \'credential\'');
    expect(migration).toContain("enforce_fresh_auth_grant_issuance_finalization");
    expect(migration).toContain("FreshAuthGrant_issuance_guard");
    expect(migration).toContain('bound."state" <> \'submitted\'');
    expect(acceptance).toContain("duplicate_credential_account_rejected");
  });

  it("reserves password-change success for one deferred atomic password-transition finalization", () => {
    const migration = readFileSync(migrationPath, "utf8");
    expect(migration).toContain("enforce_password_change_success_finalization");
    expect(migration).toContain("password_change_success_finalization_required");
    expect(migration).toContain("NEW.\"operationKey\" <> 'password_change'");
    expect(migration).toContain("PasswordChangeCredentialMutation");
    expect(migration).toContain("apply_password_change_credential_mutation");
  });

  it("binds every operation to the credential and session-security version vector", () => {
    const schema = readFileSync(schemaPath, "utf8");
    const migration = readFileSync(migrationPath, "utf8");
    const acceptance = readFileSync(acceptancePath, "utf8");

    expect(schema).toMatch(/model GlobalSecurityOperationBinding \{[\s\S]*securityVersion\s+Int[\s\S]*sessionSecurityVersion\s+Int/);
    expect(schema).toMatch(/model EmailChange \{[\s\S]*securityVersion\s+Int[\s\S]*sessionSecurityVersion\s+Int/);
    expect(migration).toContain('state_row."sessionSecurityVersion" IS DISTINCT FROM expected_session_version');
    expect(migration).toContain('expected_session_version IS NOT DISTINCT FROM state_row."sessionSecurityVersion"');
    expect(acceptance).toContain("session_security_version_only_stale_finalization");
  });

  it("keeps tombstone schemas inactive until an atomic compaction gate is delivered", () => {
    const migration = readFileSync(migrationPath, "utf8");
    const acceptance = readFileSync(acceptancePath, "utf8");

    expect(migration).toContain("global_security_tombstone_insert_not_enabled");
    expect(migration).toContain("global_security_reservation_tombstone_insert_not_enabled");
    expect(acceptance).toContain("phase1_terminal_tombstone_insert_rejected");
    expect(acceptance).toContain("phase1_reservation_tombstone_insert_rejected");
    expect(acceptance).toContain("tombstone_retention_fixture_only");
  });

  it("freezes an exact ten-code recovery-set aggregate with a ten-minute restricted carrier", () => {
    const schema = readFileSync(schemaPath, "utf8");
    const migration = readFileSync(migrationPath, "utf8");

    expect(schema).toContain("enum RecoveryCodeSetState");
    expect(schema).toContain("enum RecoveryCodeConsumptionPurpose");
    expect(schema).toMatch(/model RecoveryCodeSet \{[\s\S]*expectedCodeCount\s+Int\s+@default\(10\)[\s\S]*saveAcknowledgedAt\s+DateTime\?[\s\S]*rehearsedAt\s+DateTime\?/);
    expect(schema).toMatch(/model RecoveryCode \{[\s\S]*ordinal\s+Int[\s\S]*salt\s+Bytes[\s\S]*derivedKey\s+Bytes[\s\S]*consumedPurpose\s+RecoveryCodeConsumptionPurpose\?/);
    expect(migration).toContain("RecoveryCodeSet_exact_ten_guard");
    expect(migration).toContain("recovery_session_ttl_invalid");
    expect(migration).toContain("INTERVAL '10 minutes'");
  });

  it("requires a rehearsed recovery set and purpose-bound operation for a restricted recovery session", () => {
    const migration = readFileSync(migrationPath, "utf8");

    expect(migration).toContain("recovery_code_set_invalid_transition");
    expect(migration).toContain("recovery_code_set_rehearsal_required");
    expect(migration).toContain("recovery_code_consumption_operation_mismatch");
    expect(migration).toContain("recovery_session_rehearsed_set_required");
    expect(migration).toContain("recovery_session_consumption_binding_mismatch");
    expect(migration).toContain("RecoverySession_consumption_binding_guard");
  });

  it("rehearses generated-set, purpose, and exact-TTL recovery rejection probes against PostgreSQL", () => {
    const acceptance = readFileSync(acceptancePath, "utf8");

    expect(acceptance).toContain("recovery_generated_set_reset_rejected");
    expect(acceptance).toContain("recovery_ttl_mismatch_rejected");
    expect(acceptance).toContain("recovery_wrong_purpose_rejected");
  });

  it("proves a recovery-set contender is blocked on the authoritative transition lock", () => {
    const acceptance = readFileSync(acceptancePath, "utf8");

    expect(acceptance).toContain("recovery_transition_wait_observed");
    expect(acceptance).toContain("recovery_contender_probe");
    expect(acceptance).toContain('SELECT ${recoveryControllerPid}::integer = ANY(pg_blocking_pids(${recoveryContenderPid}::integer))');
    expect(acceptance).toContain('await observeTransitionWait("recovery_session_insert"');
  });

  it("keeps the recovery-code composite identity declared by Prisma in the physical migration", () => {
    const migration = readFileSync(migrationPath, "utf8");
    expect(migration).toContain('CREATE UNIQUE INDEX "RecoveryCode_userId_id_key" ON "RecoveryCode"("userId", "id")');
  });

  it("binds recovery-set issuance to one current recovery-enrollment grant and submitted operation", () => {
    const schema = readFileSync(schemaPath, "utf8");
    const migration = readFileSync(migrationPath, "utf8");

    expect(schema).toMatch(/model RecoveryCodeSet \{[\s\S]*issuanceOperationId\s+String[\s\S]*freshAuthGrantId\s+String\s+@unique[\s\S]*issuanceSecurityVersion\s+Int[\s\S]*issuanceSessionSecurityVersion\s+Int/);
    expect(migration).toContain('"issuanceOperationId" TEXT NOT NULL');
    expect(migration).toContain('"freshAuthGrantId" TEXT NOT NULL');
    expect(migration).toContain('RecoveryCodeSet_freshAuthGrantId_fkey');
    expect(migration).toContain('RecoveryCodeSet_userId_issuanceOperationId_fkey');
    expect(migration).toContain("recovery_code_set_issuance_authorization_required");
    expect(migration).toContain("RecoveryCodeSet_issuance_guard");
  });

  it("rehearses wrong-purpose and reused issuance-grant rejection against PostgreSQL", () => {
    const acceptance = readFileSync(acceptancePath, "utf8");
    expect(acceptance).toContain("recovery_set_wrong_grant_rejected");
    expect(acceptance).toContain("recovery_set_reused_grant_rejected");
  });

  it("revalidates the complete issuance authorization at transaction end before retaining a recovery set", () => {
    const migration = readFileSync(migrationPath, "utf8");
    const acceptance = readFileSync(acceptancePath, "utf8");
    expect(migration).toContain("assert_recovery_code_set_issuance_authorization");
    expect(migration).toContain("'consumed'::\"FreshAuthGrantState\"");
    expect(acceptance).toContain("recovery_set_terminalized_operation_rejected");
    expect(migration).toContain('grant_row."expiresAt" <= clock_timestamp()');
    expect(acceptance).toContain("recovery_grant_database_clock_normalized");
  });

  it("opens a restricted recovery session without a circular code-operation dependency and requires the consumed code at commit", () => {
    const migration = readFileSync(migrationPath, "utf8");
    expect(migration).toContain('code_row."state" <> \'active\'');
    expect(migration).toContain('code_row."state" <> \'consumed\' OR code_row."consumedPurpose" <> \'recovery_reset\'');
    expect(migration).toContain('code_row."consumedOperationId" IS DISTINCT FROM NEW."operationId"');
    expect(migration).toContain('RecoverySession_consumption_binding_guard');
  });

  it("requires complete nine-code rehearsal readiness before terminal enrollment success", () => {
    const migration = readFileSync(migrationPath, "utf8");
    expect(migration).toContain("enforce_recovery_enrollment_success_finalization");
    expect(migration).toContain("recovery_enrollment_success_finalization_required");
    expect(migration).toContain("GlobalSecurityOperation_recovery_enrollment_success_guard");
  });

  it("proves rollback removes every recovery enum created by the migration", () => {
    const acceptance = readFileSync(acceptancePath, "utf8");
    expect(acceptance).toContain("RecoveryCodeSetState");
    expect(acceptance).toContain("RecoveryCodeConsumptionPurpose");
    expect(acceptance).toContain("Session_userId_id_key");
  });

  it("requires every recovery-code consumption to close over its matching operation and carrier at commit", () => {
    const migration = readFileSync(migrationPath, "utf8");
    const acceptance = readFileSync(acceptancePath, "utf8");

    expect(migration).toContain("RecoveryCode_consumption_guard");
    expect(migration).toContain("recovery_code_consumption_binding_mismatch");
    expect(acceptance).toContain("recovery_consumption_missing_operation_rejected");
    expect(acceptance).toContain("recovery_consumption_missing_carrier_rejected");
  });

  it("takes the declared per-operation identity lock in binding and operation transition writers", () => {
    const migration = readFileSync(migrationPath, "utf8");
    const operationWriter = migration.slice(migration.indexOf('CREATE OR REPLACE FUNCTION "enforce_global_security_operation_write_once"()'));
    const bindingWriter = migration.slice(migration.indexOf('CREATE OR REPLACE FUNCTION "enforce_global_security_binding_write_once"()'));

    expect(operationWriter).toContain('PERFORM "lock_global_security_operation_identity_v1"(OLD."userId", OLD."operationId")');
    expect(bindingWriter).toContain('PERFORM "lock_global_security_operation_identity_v1"(OLD."userId", OLD."operationId")');
  });

  it("proves a transaction begun before session expiry rejects authorization after its session-row lock wait", () => {
    const acceptance = readFileSync(acceptancePath, "utf8");

    expect(acceptance).toContain("phase2_session_expiry_after_lock_wait_rejected");
    expect(acceptance).toContain('"expiresAt" > clock_timestamp()');
  });

  it("takes the deployment-wide transition lock before every lifecycle row guard", () => {
    const migration = readFileSync(migrationPath, "utf8");
    const acceptance = readFileSync(acceptancePath, "utf8");

    for (const trigger of [
      "00_GlobalSecurityOperation_transition_lock",
      "00_GlobalSecurityOperationBinding_transition_lock",
      "00_FreshAuthGrant_transition_lock",
      "00_RecoveryCodeSet_transition_lock",
      "00_RecoveryCode_transition_lock",
      "00_RecoverySession_transition_lock",
      "00_EmailChange_transition_lock"
    ]) expect(migration).toContain(`CREATE TRIGGER "${trigger}"`);
    for (const trigger of [
      "00_GlobalSecurityOperation_transition_lock\" BEFORE INSERT OR UPDATE",
      "00_GlobalSecurityOperationBinding_transition_lock\" BEFORE INSERT OR UPDATE",
      "00_FreshAuthGrant_transition_lock\" BEFORE INSERT OR UPDATE",
      "00_EmailChange_transition_lock\" BEFORE INSERT OR UPDATE"
    ]) expect(migration).toContain(trigger);
    for (const lifecycle of ["global_security_operation", "fresh_auth_grant", "recovery_code_set", "recovery_code", "recovery_session", "email_change"]) {
      expect(acceptance).toContain(`await observeTransitionWait("${lifecycle}"`);
    }
    for (const lifecycle of ["global_security_operation_insert", "global_security_binding_insert", "fresh_auth_grant_insert", "email_change_insert"]) {
      expect(acceptance).toContain(`await observeTransitionWait("${lifecycle}"`);
    }
  });

  it("closes an expired submitted recovery-reset operation atomically with a durable non-success outcome", () => {
    const migration = readFileSync(migrationPath, "utf8");
    const acceptance = readFileSync(acceptancePath, "utf8");

    expect(migration).toContain('"expire_recovery_session_finalization"');
    expect(migration).toContain('"GlobalSecurityOperation_recovery_expiry_finalization_guard"');
    expect(migration).toContain("recovery_session_expired");
    expect(migration).toContain("recovery_session_expiry_event_required");
    expect(acceptance).toContain("recovery_submitted_expiry_finalized");
    expect(acceptance).toContain("recovery_submitted_expiry_partial_rejected");
  });

  it("requires a protected one-time password-verification attestation before password grants", () => {
    const migration = readFileSync(migrationPath, "utf8");
    const acceptance = readFileSync(acceptancePath, "utf8");
    expect(migration).toContain("FreshAuthAttestationKey");
    expect(migration).toContain("verify_password_fresh_auth_attestation");
    expect(migration).toContain("fresh_auth_attestation_invalid");
    expect(migration).toContain("replacement_password_hash_attestation_mismatch");
    expect(migration).toContain('REVOKE ALL ON TABLE "FreshAuthAttestationKey" FROM cubby_runtime');
    expect(acceptance).toContain("phase4_runtime_forged_password_authority_chain_rejected");
    expect(acceptance).toContain("phase4_runtime_attested_hash_substitution_rejected");
    expect(acceptance).toContain("phase4_attested_password_service_lifecycle_pass");
    expect(migration).toContain("verify_recovery_reset_attestation");
    expect(migration).toContain("recovery_reset_attestation_invalid");
    expect(acceptance).toContain("phase5_runtime_forged_recovery_authority_chain_rejected");
    expect(acceptance).toContain("phase5_runtime_attested_recovery_hash_substitution_rejected");
  });

  it("defines the complete durable Phase 6 email-change persistence universe", () => {
    const schema = readFileSync(schemaPath, "utf8");
    const migration = readFileSync(migrationPath, "utf8");
    for (const model of ["EmailChangeDelivery", "EmailChangeIdentityMutation", "EmailChangeSessionRotation", "EmailDeliveryEncryptionKey"]) {
      expect(schema).toContain(`model ${model} {`);
      expect(migration).toContain(`CREATE TABLE "${model}"`);
    }
    expect(migration).toContain("EmailChangeDelivery_transition_guard");
    expect(migration).toContain("EmailDeliveryEncryptionKey_ciphertext_reference_guard");
    expect(migration).toContain("User_email_normalized_unique");
  });

  it("retains the successor rotation receipt while preserving the original activity anchor and allowing failed-cookie revocation", () => {
    const migration = readFileSync(migrationPath, "utf8");
    expect(migration).not.toContain('CONSTRAINT "EmailChangeSessionRotation_successorSessionId_fkey"');
    expect(migration).toContain("email_change_rotation_successor_session_required");
    expect(migration).toContain('old_activity."originalCreatedAt"');
    expect(migration).toContain('DELETE FROM public."Session" WHERE "id"=receipt."successorSessionId"');
  });

  it("rechecks and atomically rotates every pending old-address invitation during cutover", () => {
    const migration = readFileSync(migrationPath, "utf8");
    expect(migration).toContain("email_change_invitation_set_mismatch");
    expect(migration).toContain('ORDER BY invite."id" FOR UPDATE');
    expect(migration).toContain("^sha256:[0-9a-f]{64}$");
    expect(migration).toContain("prepared_invitations JSONB, prepared_deliveries JSONB");
    expect(migration).toContain("'invitation_reissue','inviter_notice'");
    const revoke = migration.indexOf('UPDATE public."Invite" SET "status"=\'revoked\'');
    const identity = migration.indexOf('UPDATE public."User" SET "email"=change_row."normalizedNewEmail"');
    expect(revoke).toBeGreaterThan(0);
    expect(identity).toBeGreaterThan(revoke);
  });

  it("keeps disposable acceptance artifacts inside the authorized Cubby project root", () => {
    const acceptance = readFileSync(acceptancePath, "utf8");
    expect(acceptance).not.toContain("tmpdir()");
    expect(acceptance).toContain('"worker-runtime"');
  });

  it("requires the exact original live session for cancellation and closes stale email changes", () => {
    const migration = readFileSync(migrationPath, "utf8");
    expect(migration).toContain('CREATE FUNCTION "cancel_email_change"(scope_user_id TEXT, scope_operation_id TEXT, scope_session_id TEXT)');
    expect(migration).toContain("email_change_cancellation_authorization_required");
    expect(migration).toContain('CREATE FUNCTION "stale_email_change"');
    expect(migration).toContain("email_change_stale_finalization_required");
    expect(migration).toContain("stale_security_version'::TEXT");
  });

  it("keeps delivery claims and receipts unavailable to cubby_runtime", () => {
    const migration = readFileSync(migrationPath, "utf8");
    expect(migration).toContain('REVOKE ALL ON FUNCTION "claim_email_change_delivery"(TEXT),"accept_email_change_delivery"(TEXT,TEXT,INTEGER,BYTEA),"fail_email_change_delivery"(TEXT,TEXT,TEXT) FROM PUBLIC');
    expect(migration).toContain('REVOKE ALL ON FUNCTION "claim_email_change_delivery"(TEXT),"accept_email_change_delivery"(TEXT,TEXT,INTEGER,BYTEA),"fail_email_change_delivery"(TEXT,TEXT,TEXT) FROM cubby_runtime');
    expect(migration).toContain('GRANT EXECUTE ON FUNCTION "claim_email_change_delivery"(TEXT),"accept_email_change_delivery"(TEXT,TEXT,INTEGER,BYTEA),"fail_email_change_delivery"(TEXT,TEXT,TEXT) TO cubby_email_delivery');
    expect(migration).not.toContain('GRANT EXECUTE ON FUNCTION "claim_email_change_delivery"(TEXT),"accept_email_change_delivery"(TEXT,TEXT,INTEGER,BYTEA),"fail_email_change_delivery"(TEXT,TEXT,TEXT) TO cubby_runtime');
  });

  it("isolates Better Auth session DML to cubby_auth while runtime uses only fixed-search-path session-security procedures", () => {
    const migration = readFileSync(migrationPath, "utf8");

    expect(migration).toContain("GRANT CONNECT ON DATABASE %I TO cubby_auth");
    expect(migration).toContain("GRANT USAGE ON SCHEMA public TO cubby_auth");
    expect(migration).toContain('GRANT SELECT ON TABLE "User","Account","Verification","Session" TO cubby_auth');
    expect(migration).toContain('GRANT INSERT, UPDATE, DELETE ON TABLE "Session" TO cubby_auth');
    expect(migration).toContain('REVOKE ALL ON ALL TABLES IN SCHEMA public FROM cubby_auth');
    expect(migration).toContain('REVOKE INSERT, UPDATE, DELETE ON "Session","SessionSecurityActivity" FROM cubby_runtime');
    expect(migration).toMatch(/GRANT EXECUTE ON FUNCTION[^;]*"initialize_global_session_security_activity"\(TEXT,TEXT\)[^;]*"authorize_global_session_security"\(TEXT,TEXT,TEXT\)[^;]*"list_global_session_security"\(TEXT,TEXT\)[^;]* TO cubby_runtime/);
    expect(migration).toMatch(/CREATE FUNCTION "list_global_session_security"[\s\S]*?authorize_global_session_security[\s\S]*?RETURN QUERY SELECT[\s\S]*?issuanceSessionSecurityVersion/);
    expect(migration).toContain('SECURITY DEFINER SET search_path=pg_catalog,public');
  });

  it("keeps accepted password recovery and suspension session closure working after runtime Session DML denial", () => {
    const migration = readFileSync(migrationPath, "utf8");
    const globalSecurityService = readFileSync(globalSecurityServicePath, "utf8");
    const recoveryService = readFileSync(recoveryServicePath, "utf8");
    const inviteService = readFileSync(inviteServicePath, "utf8");

    expect(migration).toContain('CREATE FUNCTION "revoke_sessions_for_global_security_operation"(scope_user_id TEXT, scope_operation_id TEXT)');
    expect(migration).toContain('CREATE FUNCTION "revoke_sessions_for_suspended_member"(scope_household_id TEXT, scope_member_id TEXT, scope_user_id TEXT)');
    expect(migration).toMatch(/GRANT EXECUTE ON FUNCTION[^;]*"revoke_sessions_for_global_security_operation"\(TEXT,TEXT\)[^;]*"revoke_sessions_for_suspended_member"\(TEXT,TEXT,TEXT\)[^;]* TO cubby_runtime/);
    expect(globalSecurityService).toContain('SELECT "revoke_sessions_for_global_security_operation"');
    expect(recoveryService).toContain('SELECT "revoke_sessions_for_global_security_operation"');
    expect(inviteService).toContain('SELECT "revoke_sessions_for_suspended_member"');
    for (const service of [globalSecurityService, recoveryService, inviteService]) expect(service).not.toContain('.session.deleteMany');
  });

  it("terminalizes a racing stale session revoke and keeps status globally serialized", () => {
    const migration = readFileSync(migrationPath, "utf8");
    expect(migration).toContain("session_revoke_stale_finalization");
    expect(migration).toContain("operation_row.\"status\"='stale'");
    expect(migration).toMatch(/CREATE FUNCTION \"get_session_revoke_status\"[\s\S]*?pg_advisory_xact_lock\(hashtextextended\('global-security-transition:v1',0\)\)/);
    expect(migration).toContain('\"securityUpdatedAt\"=now_time');
  });

  it("rehearses the complete Phase 7 role, lifetime, revocation, and replay contract", () => {
    const acceptance = readFileSync(acceptancePath, "utf8");

    for (const marker of [
      "phase7_auth_role_least_privilege_pass",
      "phase7_runtime_session_dml_denied",
      "phase7_safe_list_atomic_authorization_pass",
      "phase7_session_scope_current_pass",
      "phase7_session_scope_one_pass",
      "phase7_session_scope_others_pass",
      "phase7_session_scope_all_pass",
      "phase7_pending_status_retry_pass",
      "phase7_lost_response_status_pass",
      "phase7_session_replay_conflict_pass",
      "phase7_already_revoked_pass",
      "phase7_session_event_content_free_pass",
      "phase7_idle_lifetime_pass",
      "phase7_absolute_lifetime_pass",
      "phase7_issuance_version_stale_pass",
      "phase7_warning_non_extension_pass",
      "phase7_qualifying_use_classification_pass",
      "phase7_email_rotation_anchor_retained",
      "phase7_session_lock_wait_observed"
    ]) expect(acceptance).toContain(marker);
    expect(acceptance).toContain("revokeGlobalSessionSecurityWithCurrentPassword");
    expect(acceptance).toContain("getGlobalSessionRevokeStatus");
    expect(acceptance).toContain("initializeGlobalSessionSecurityActivity");
    expect(acceptance).toContain("recordQualifyingGlobalSessionUseAfterSuccess");
  });

  it("runs bounded database-clock email-change and cookie-expiry closure from the runtime role", () => {
    const migration = readFileSync(migrationPath, "utf8");
    expect(migration).toContain('CREATE FUNCTION "run_email_change_lifecycle_batch"(batch_limit INTEGER)');
    expect(migration).toContain('FOR UPDATE SKIP LOCKED');
    expect(migration).toContain('"expiresAt"<=clock_timestamp()');
    expect(migration).toContain('"issuedAt"+INTERVAL \'5 minutes\'<=clock_timestamp()');
    expect(migration).toContain('GRANT EXECUTE ON FUNCTION "run_email_change_lifecycle_batch"(INTEGER) TO cubby_runtime');
    expect(migration).not.toContain('GRANT EXECUTE ON FUNCTION "run_email_change_lifecycle_batch"(INTEGER) TO cubby_email_delivery');
  });

  it("closes an email change when an expired eighth verification-delivery lease is recovered", () => {
    const migration = readFileSync(migrationPath, "utf8");
    expect(migration).toContain("expired_delivery public.\"EmailChangeDelivery\"%ROWTYPE");
    expect(migration).toContain("expired_delivery.\"kind\"='new_verification'");
    expect(migration).toContain("PERFORM public.\"terminalize_email_change\"(expired_delivery.\"userId\",expired_delivery.\"operationId\",'failed','delivery_failed')");
  });

  it("reacquires and rechecks the canonical target-email reservation at cutover", () => {
    const migration = readFileSync(migrationPath, "utf8");
    expect(migration).toContain("'email-identity:v1:' || change_row.\"normalizedNewEmail\"");
    expect(migration).toContain('other_change."id"<>change_row."id"');
    expect(migration).toContain("email_change_target_reservation_lost");
  });

  it("keeps every email-change closure code inside the database terminal-outcome registry", () => {
    const migration = readFileSync(migrationPath, "utf8");
    for (const triple of [
      "email_change'::\"GlobalSecurityOperationKey\", 'rejected'::\"GlobalSecurityOperationStatus\", 'verification_expired",
      "email_change'::\"GlobalSecurityOperationKey\", 'rejected'::\"GlobalSecurityOperationStatus\", 'delivery_failed",
      "email_change'::\"GlobalSecurityOperationKey\", 'rejected'::\"GlobalSecurityOperationStatus\", 'abandoned"
    ]) expect(migration).toContain(triple);
    expect(migration).toContain("CASE WHEN terminal_code='verification_expired' THEN 'expired' ELSE terminal_code END");
  });
});
