import { readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { describe, expect, it } from "vitest";

const design = JSON.parse(readFileSync(fileURLToPath(new URL("../../../docs/design/p1-3-global-security-protocol.json", import.meta.url)), "utf8"));

describe("P1-3 Phase 8 private security design gate", () => {
  it("freezes layered throttling, private history, export, retention, and operator boundaries", () => {
    const phase8 = design.phase8PrivateHistoryThrottlingAddendum;
    expect(phase8.release).toEqual({ state: "complete_program_unreleased_until_phase9", forbids: ["partial_history_release", "better_auth_rate_limit_as_authority", "household_audit_carrier", "household_backup_carrier", "ordinary_runtime_operator_reader"] });
    expect(phase8.persistenceTarget).toEqual({
      models: ["GlobalSecurityEvent", "GlobalSecurityIncident", "GlobalSecurityThrottleKey"],
      GlobalSecurityEvent: { fields: ["id", "sequence_bigserial_unique", "userId", "eventType", "outcome", "operationId_nullable", "incidentId_nullable_unique", "safeProjection_empty_json", "createdAt_database_default"], relations: ["user_cascade", "incident_cascade"], indexes: ["userId_sequence", "unique_user_operation_eventType_outcome_when_operation_present", "unique_incidentId"], guards: ["closed_event_outcome_matrix", "operation_incident_exclusive_shape", "append_only_update_forbidden", "direct_delete_forbidden_while_user_exists", "delete_allowed_only_after_user_fk_cascade", "truncate_forbidden"] },
      GlobalSecurityIncident: { fields: ["id", "userId_nullable", "layer", "normalizedKey", "windowStartedAt", "failureCount", "quietUntil_nullable", "state", "lastOutcomeAt", "createdAt"], identity: "unique_layer_normalizedKey_windowStartedAt", relations: ["optional_user_cascade", "events"], guards: ["layer_user_ownership", "deterministic_transition", "monotonic_count_time_quiet", "direct_delete_forbidden", "truncate_forbidden"] },
      GlobalSecurityThrottleKey: { fields: ["singletonId_1", "keyDigest_sha256_32_bytes", "createdAt", "verifiedAt"], authority: "migrator_owner_provisioner_only", guards: ["singleton", "immutable_digest", "no_runtime_auth_or_operator_access"] },
      migrationOrder: ["create_or_alter_models", "install_constraints_indexes", "install_guards", "revoke_table_dml", "grant_procedures", "post_migration_key_provision"]
    });
    expect(phase8.keys).toEqual({
      algorithm: "hmac_sha256_base64url_32_bytes",
      key: "CUBBY_THROTTLE_KEY_base64url_exactly_32_bytes",
      derivation: { identityFrame: "uint32be_utf8_domain_length_domain_uint32be_utf8_value_length_value", accountDomain: "cubby:phase8:account-identifier:v1", clientDomain: "cubby:phase8:client:v1", deploymentDomain: "cubby:phase8:deployment:v1", historyHandleDomain: "cubby:phase8:history-handle:v1", cursorDomain: "cubby:phase8:history-cursor:v1", digest: "hmac_sha256_full_32_bytes_base64url_no_padding" },
      lifecycle: { rotation: "forbidden_until_separate_maintenance_gate", startupDigest: "owner_table_sha256_digest_must_match_configured_key", backup: "excluded", logging: "forbidden", ownerTable: "GlobalSecurityThrottleKey_singletonId_1_keyDigest_sha256_createdAt_verifiedAt", bootstrap: { migration: "create_empty_owner_only_table_before_key_provisioner", freshVolume: "post_migration_provisioner_inserts_singleton_digest", existingVolume: "post_migration_provisioner_locks_row_requires_exact_digest_and_updates_verifiedAt", restoreMismatch: "fail_before_server_start_without_replacing_digest", writes: "migrator_owner_provisioner_only" } },
      account_identifier: { normalize: "normalize_security_email_v1", frame: "account_identifier_v1_nul_normalized", userId: "privately_resolve_when_existing_otherwise_absent", persistedRawIdentifier: false },
      client: { source: "configured_trusted_proxy_single_hop_address_else_unknown_client", trustedProxyConfig: "CUBBY_TRUSTED_PROXY_HOPS_integer_zero_or_one", forwardingHeader: "x_forwarded_for_exactly_one_canonical_address_only_when_hops_one", fallback: "unknown_client", frame: "client_v1_nul_canonical_or_unknown", persistedAddress: false, grammar: { hops0: "ignore_all_forwarding_headers_use_unknown_client", hops1: "x_forwarded_for_must_have_exactly_one_trimmed_token", multipleEmptyMalformed: "unknown_client", ipv4: "node_net_isIP_4_then_exact_four_base10_octets_0_to_255_no_leading_plus_or_zeros_except_zero", ipv6: "node_net_isIP_6_then_whatwg_url_hostname_lowercase_rfc5952_strip_brackets" } },
      deployment: { value: "deployment_v1", userId: "forbidden" },
      normalizationVersion: 1
    });
    expect(phase8.throttle).toEqual({
      layers: ["account_identifier", "client", "deployment"], layerOrder: ["account_identifier", "client", "deployment"], failures: 5, windowMinutes: 15, quietMinutes: 15, databaseClockOnly: true, windowStart: "floor_database_epoch_seconds_divided_by_900_times_900", maxCount: 255,
      states: ["active", "quiet", "closed"], transitions: ["missing_to_active_on_failure", "active_increment_1_to_4", "active_to_quiet_on_5", "quiet_increment_without_deadline_extension", "active_or_quiet_to_closed_after_deadline", "closed_immutable"],
      precheck: "deny_when_any_applicable_layer_quiet_before_secret_verification", afterQuiet: "close_prior_and_start_new_window_on_next_failure", success: "append_success_evidence_without_mutating_incidents", uncertainty: "neutral_deny_with_fixed_15_minute_retry_deadline", externalResponse: "account_existence_neutral_invalid_or_retry_later", replay: "never_increment_status_or_identical_replay", applicability: { account_identifier: "only_when_user_privately_resolves", client: "always", deployment: "always" },
      transaction: { isolation: "serializable", globalLock: "global-security-transition:v1", incidentLock: "pg_advisory_xact_lock_hashtextextended_global-security-incident:v1_layer_normalizedKey", order: ["account_identifier", "client", "deployment"], precheckAndFailure: "one_transaction_lock_all_applicable_identities_and_rows", uniqueConflict: "refetch_same_identity_for_update_and_reapply_transition" },
      deadlines: { windowEnd: "windowStartedAt_plus_15_minutes", quietUntil: "fifth_failure_database_time_plus_15_minutes_immutable", denyPredicate: "state_quiet_and_database_time_strictly_less_than_quietUntil", expiryPredicate: "active_expires_when_database_time_greater_than_or_equal_to_windowEnd_quiet_expires_only_when_database_time_greater_than_or_equal_to_quietUntil", precedence: "quiet_deny_precedes_fixed_window_rollover_until_quietUntil", closeBeforeNew: "close_expired_active_or_quiet_row_then_lock_or_insert_current_fixed_window", existingCurrentWindow: "lock_and_apply_same_transition", maxCount: "least_255_failureCount_plus_one" },
      neutrality: { status: 401, bodyCode: "INVALID_EMAIL_OR_PASSWORD", headers: "identical_no_retry_after_for_invalid_or_any_quiet_layer", quietWork: "one_fixed_dummy_password_verification_and_same_response_serialization_without_real_secret_verification", nonexistentWork: "better_auth_dummy_password_verification_plus_same_client_deployment_precheck", accountOnlyQuiet: "indistinguishable_from_nonexistent_identifier", retryGuidance: "generic_private_history_only_after_later_successful_sign_in" }
    });
    expect(phase8.carriers).toEqual([
      "sign_in_email", "session_revoke_current_password", "password_change_current_password", "recovery_enrollment_current_password", "email_change_current_password", "recovery_code_rehearsal", "recovery_reset_opening"
    ]);
    expect(phase8.carrierMatrix).toEqual({
      sign_in_email: { accountKeyInput: "submitted_email_normalized_before_lookup", failure: "invalid_email_password_only", success: "session_created" },
      current_password: { accountKeyInput: "locked_current_user_email", purposes: ["session_revoke", "password_change", "recovery_enrollment", "email_change"], failure: "current_password_invalid_only", success: "fresh_grant_issued_or_identical_replay" },
      recovery_code_rehearsal: { accountKeyInput: "locked_current_user_email", failure: "recovery_code_invalid_only", success: "rehearsal_completed" },
      recovery_reset_opening: { accountKeyInput: "locked_target_user_email_from_internal_user_id_before_code_verification", failure: "neutral_absent_invalid_consumed_or_changed_code", success: "restricted_recovery_session_issued_or_identical_replay" },
      excluded: ["stale_security_version", "idempotency_conflict", "operation_unknown", "expired_binding", "collision", "delivery_failure", "status_read", "terminal_replay"]
    });
    expect(phase8.events).toEqual({
      classes: ["credential", "grant", "recovery", "email_change", "session", "throttle", "operation_outcome"], safeProjection: "empty_object_only", appendOnly: true,
      incidentBinding: { field: "incidentId_nullable_unique", throttle: "required_matching_account_incident_and_user", nonThrottle: "forbidden" },
      neutralLayerDisposition: "client_and_deployment_quiet_transitions_emit_no_private_event_and_are_operator_aggregate_only",
      operationBinding: { operation_outcome: "required", throttle: "forbidden" },
      signIn: ["credential|sign_in_failed", "credential|sign_in_succeeded"], proof: ["grant|current_password_failed", "grant|current_password_verified"], throttle: ["throttle|quiet_started"],
      projectionMatrix: { credential: ["sign_in_failed", "sign_in_succeeded", "password_changed"], grant: ["current_password_failed", "current_password_verified", "grant_expired"], recovery: ["code_set_generated", "rehearsed", "rehearsal_failed", "reset_started", "reset_completed", "reset_failed"], email_change: ["requested", "verified", "completed", "cancelled", "expired", "failed"], session: ["revoked", "already_revoked", "stale_security_version", "expired"], throttle: ["quiet_started"], operation_outcome: ["completed", "rejected", "stale_security_version"] },
      cardinality: { signInAttempt: "one_credential_event_per_delivered_200_or_401_when_user_privately_resolves", signInEvidenceUnavailable: "fixed_neutral_503_after_atomic_evidence_transaction_rollback_with_zero_event_and_no_session", operationBound: "unique_user_operation_eventType_outcome", throttle: "unique_incidentId_one_quiet_started_event_for_account_layer_only", neutralThrottle: "zero_private_events", atomicity: "sign_in_success_same_transaction_as_cubby_auth_session_insert_sign_in_failure_same_transaction_as_incident_other_classes_same_authoritative_transition", excluded: "zero_events_and_zero_counter_increment_for_status_terminal_replay_or_protocol_conflict" },
      duplicate: "same_transition_exactly_once"
    });
    expect(phase8.reader).toEqual({
      authority: "same_global_user_active_ordinary_session", household: "forbidden", order: ["sequence_desc"], defaultLimit: 50, minLimit: 1, maxLimit: 100, fetch: "limit_plus_one",
      cursor: "hmac_authenticated_user_snapshot_max_sequence_last_sequence_schema_v1", handle: "base64url_first_22_bytes_hmac_historyHandleDomain_over_length_framed_userId_and_eventId",
      cursorCodec: { payload: "version_u8_1_snapshotMaxSequence_u64be_lastSequence_u64be_userIdLength_u16be_userId_utf8", token: "base64url_payload_dot_base64url_full_hmac_sha256_cursorDomain", verification: "constant_time_mac_exact_length_version_utf8_and_same_user", invalid: "422_security_history_cursor_invalid_for_malformed_or_foreign_user", predicate: "sequence_less_than_lastSequence_and_sequence_less_than_or_equal_to_snapshotMaxSequence" },
      concurrency: "database_sequence_is_strictly_increasing_snapshotMaxSequence_captured_on_first_page_excludes_all_later_inserts",
      fields: ["handle", "eventClass", "action", "outcome", "occurredAt", "operationKey", "incident"], forbidden: ["operationId", "incidentId", "databaseId", "normalizedKey", "accountIdentifier", "ip", "location", "fullUserAgent", "household", "baby", "credential"],
      incidentProjection: { windowStartedAt: "incident_windowStartedAt", windowEndedAt: "quietUntil_else_windowStartedAt_plus_15_minutes", approximateFailures: ["5-9", "10-19", "20-49", "50+"], guidance: ["change_password", "review_sessions"], keys: "forbidden" }
    });
    expect(phase8.export).toEqual({ schemaVersion: 1, exportType: "cubby_global_security_history", format: "json", order: "oldest_first_repeatable_read", projection: "same_as_reader", filename: "cubby-global-security-history-v1-UTC.json", householdBackup: "excluded", carrier: "POST_api_account_security-history_export_application_json_confirmed_true", authority: "same_global_user_active_ordinary_session_and_database_recheck", snapshot: "repeatable_read_database_time_upper_bound_all_user_events", result: "200_application_json_content_disposition_attachment_or_stable_4xx", maximumEvents: 100000, tooLarge: "413_security_history_export_too_large" });
    expect(phase8.retention).toEqual({ userBound: "until_user_fk_cascade_only", accountNeutralIncidents: "until_separate_maintenance_gate", directDelete: "forbidden", truncate: "forbidden", accountDeletionRoute: "disabled", acceptance: ["user_cascade_removes_user_bound", "neutral_incidents_survive", "household_backup_excludes_all"] });
    expect(phase8.operator).toEqual({ carrier: "host_local_packaged_cli", databaseRole: "cubby_security_operator", authority: "execute_fixed_search_path_content_free_aggregate_only", fields: ["layer", "state", "coarseTimeBucket", "incidentCount"], forbidden: ["web_endpoint", "user", "normalizedKey", "rawIdentifier", "address", "perKeyCount", "drillDown", "ordinaryRuntimeTableRead"], coarseTimeBucket: "UTC_calendar_day", range: "from_inclusive_to_exclusive_maximum_31_days", function: "read_global_security_operator_aggregate(date,date)", cli: "dist/security-operator.mjs aggregate --from YYYY-MM-DD --to YYYY-MM-DD", output: "stdout_json_schema_v1_stderr_sanitized_nonzero_on_failure" });
    expect(phase8.privileges).toEqual({ cubby_migrator: ["owner", "migrate", "provision_roles"], cubby_runtime: ["execute_throttle_precheck", "execute_throttle_failure", "execute_security_event_writer", "execute_private_history_reader", "no_direct_incident_or_event_dml"], cubby_auth: ["better_auth_identity_and_session_only", "no_incident_or_event_access"], cubby_security_operator: ["execute_operator_aggregate_only", "no_table_privileges", "no_user_rows", "no_runtime_inheritance"] });
    expect(phase8.deployment).toEqual({ requiredSecrets: ["CUBBY_THROTTLE_KEY", "CUBBY_SECURITY_OPERATOR_DB_PASSWORD"], configuration: { CUBBY_TRUSTED_PROXY_HOPS: [0, 1], default: 0 }, operatorUrl: "SECURITY_OPERATOR_DATABASE_URL_host_only_never_retained_by_server", startup: "provision_roles_migrate_provision_or_verify_throttle_key_then_unset_owner_and_operator_passwords_retain_throttle_key_as_runtime_secret_and_exec_server", runtimeKeyBoundary: "CUBBY_THROTTLE_KEY_retained_only_in_server_process_environment_never_child_cli_worker_logs_or_backups", failClosed: ["missing_or_malformed_key", "key_digest_mismatch", "invalid_proxy_hops", "operator_role_elevated_member_or_owner_objects"], backups: "exclude_key_operator_credentials_incidents_events_and_all_global_security_state" });
    expect(phase8.acceptance).toEqual({ unit: ["key_framing", "client_canonicalization", "neutral_response", "cursor_codec", "safe_projection", "carrier_event_matrix"], postgresql: ["concurrent_fifth_failure_exactly_once", "quiet_equality_nonextension", "unique_conflict_recovery", "success_nonclear", "recovery_equivalence", "runtime_direct_dml_denial", "event_cardinality", "reader_user_isolation", "cursor_keyset", "repeatable_export", "user_cascade", "neutral_survival"], browser: ["existing_nonexisting_neutrality", "quiet_neutrality", "history_pagination", "export_confirmation", "responsive_accessibility", "no_secret_dom_network_storage"], operator: ["packaged_cli_role_only", "31_day_bound", "aggregate_content_free", "sanitized_failure"], deployment: ["fresh_and_existing_volume_role_provision", "key_digest_restore_mismatch", "startup_owner_operator_secret_scrub_and_runtime_throttle_key_retention", "verified_disposable_cleanup"] });
  });
});
