import type { SemanticServiceOperationDeclaration } from "@/server/operation-registry/schema";

export const semantic = [{
  kind: "service", id: "baby.create", ownerModule: "src/server/services/households.ts", exportName: "addBaby",
  axes: {
    carrier_authority_guard: { current: { authority: "source_reviewed", value: "addBaby calls getEffectiveHouseholdContext(), which requires the request's validated membership-episode cookie candidate and does not fall back to another membership", sourceReferences: [{ kind: "symbol", file: "src/server/services/households.ts", exportName: "addBaby" }] }, target: { authority: "deferred", gateId: "gate.carrier_authority_guard" } },
    caller_controlled_scope: { current: { authority: "source_reviewed", value: "addBaby parses raw input with babySchema", sourceReferences: [{ kind: "symbol", file: "src/server/services/households.ts", exportName: "addBaby" }] }, target: { authority: "deferred", gateId: "gate.caller_controlled_scope" } },
    service_operation_linkage: { current: { authority: "source_reviewed", value: "addBaby is the exported baby creation service", sourceReferences: [{ kind: "symbol", file: "src/server/services/households.ts", exportName: "addBaby" }] }, target: { authority: "deferred", gateId: "gate.service_operation_linkage" } },
    permission_commit_reauthorization: { current: { authority: "source_reviewed", value: "addBaby requires baby.manage before its Prisma create and contains no transaction-local membership recheck", sourceReferences: [{ kind: "symbol", file: "src/server/services/households.ts", exportName: "addBaby" }] }, target: { authority: "deferred", gateId: "gate.permission_commit_reauthorization" } },
    tenant_relationship_invariants: { current: { authority: "source_reviewed", value: "addBaby supplies the selected context householdId on the Baby create call", sourceReferences: [{ kind: "symbol", file: "src/server/services/households.ts", exportName: "addBaby" }] }, target: { authority: "deferred", gateId: "gate.tenant_relationship_invariants" } },
    model_reads_writes_effects: { current: { authority: "source_reviewed", value: "the source calls prisma.baby.create and then writeAudit with baby.create", sourceReferences: [{ kind: "symbol", file: "src/server/services/households.ts", exportName: "addBaby" }] }, target: { authority: "deferred", gateId: "gate.model_and_effects" } },
    variant_specific_outcomes: { current: { authority: "not_applicable", rationale: "addBaby has no declared semantic variant", sourceReferences: [{ kind: "symbol", file: "src/server/services/households.ts", exportName: "addBaby" }] }, target: { authority: "deferred", gateId: "gate.variant_outcomes" } },
    worker_loop_claim_failure_containment: { current: { authority: "not_applicable", rationale: "addBaby does not contain a worker loop", sourceReferences: [{ kind: "symbol", file: "src/server/services/households.ts", exportName: "addBaby" }] }, target: { authority: "deferred", gateId: "gate.worker_containment" } },
    browser_immutable_binding_stale_behavior: { current: { authority: "deferred", gateId: "gate.browser_binding_staleness" }, target: { authority: "deferred", gateId: "gate.browser_binding_staleness" } },
    executable_evidence_strength: { current: { authority: "deferred", gateId: "gate.executable_evidence" }, target: { authority: "deferred", gateId: "gate.executable_evidence" } }
  }
}, {
  kind: "service", id: "baby.deactivate", ownerModule: "src/server/services/households.ts", exportName: "submitDeactivateBabyBrowserOperation",
  axes: {
    carrier_authority_guard: { current: { authority: "source_reviewed", value: "submitDeactivateBabyBrowserOperation resolves its browser-operation context from the submitted selected baby", sourceReferences: [{ kind: "symbol", file: "src/server/services/households.ts", exportName: "submitDeactivateBabyBrowserOperation" }] }, target: { authority: "deferred", gateId: "gate.carrier_authority_guard" } },
    caller_controlled_scope: { current: { authority: "source_reviewed", value: "submitDeactivateBabyBrowserOperation parses the submitted babyId and binds its immutable browser intent", sourceReferences: [{ kind: "symbol", file: "src/server/services/households.ts", exportName: "submitDeactivateBabyBrowserOperation" }] }, target: { authority: "deferred", gateId: "gate.caller_controlled_scope" } },
    service_operation_linkage: { current: { authority: "source_reviewed", value: "submitDeactivateBabyBrowserOperation is the browser-operation execution adapter for baby.deactivate", sourceReferences: [{ kind: "symbol", file: "src/server/services/households.ts", exportName: "submitDeactivateBabyBrowserOperation" }] }, target: { authority: "deferred", gateId: "gate.service_operation_linkage" } },
    permission_commit_reauthorization: { current: { authority: "source_reviewed", value: "submitDeactivateBabyBrowserOperation delegates transaction-local permission reauthorization to executeBrowserOperation", sourceReferences: [{ kind: "symbol", file: "src/server/services/households.ts", exportName: "submitDeactivateBabyBrowserOperation" }] }, target: { authority: "deferred", gateId: "gate.permission_commit_reauthorization" } },
    tenant_relationship_invariants: { current: { authority: "source_reviewed", value: "submitDeactivateBabyBrowserOperation validates the locked selected baby against its bound lifecycle snapshot", sourceReferences: [{ kind: "symbol", file: "src/server/services/households.ts", exportName: "submitDeactivateBabyBrowserOperation" }] }, target: { authority: "deferred", gateId: "gate.tenant_relationship_invariants" } },
    model_reads_writes_effects: { current: { authority: "source_reviewed", value: "submitDeactivateBabyBrowserOperation checks active timers and writes the baby lifecycle transition and audit only in the browser-operation transaction callback", sourceReferences: [{ kind: "symbol", file: "src/server/services/households.ts", exportName: "submitDeactivateBabyBrowserOperation" }] }, target: { authority: "deferred", gateId: "gate.model_and_effects" } },
    variant_specific_outcomes: { current: { authority: "not_applicable", rationale: "submitDeactivateBabyBrowserOperation has no declared semantic variant", sourceReferences: [{ kind: "symbol", file: "src/server/services/households.ts", exportName: "submitDeactivateBabyBrowserOperation" }] }, target: { authority: "deferred", gateId: "gate.variant_outcomes" } },
    worker_loop_claim_failure_containment: { current: { authority: "not_applicable", rationale: "submitDeactivateBabyBrowserOperation does not contain a worker loop", sourceReferences: [{ kind: "symbol", file: "src/server/services/households.ts", exportName: "submitDeactivateBabyBrowserOperation" }] }, target: { authority: "deferred", gateId: "gate.worker_containment" } },
    browser_immutable_binding_stale_behavior: { current: { authority: "deferred", gateId: "gate.browser_binding_staleness" }, target: { authority: "deferred", gateId: "gate.browser_binding_staleness" } },
    executable_evidence_strength: { current: { authority: "deferred", gateId: "gate.executable_evidence" }, target: { authority: "deferred", gateId: "gate.executable_evidence" } }
  }
}, {
  kind: "service", id: "baby.reactivate", ownerModule: "src/server/services/households.ts", exportName: "submitReactivateBabyBrowserOperation",
  axes: {
    carrier_authority_guard: { current: { authority: "source_reviewed", value: "submitReactivateBabyBrowserOperation resolves its browser-operation context from the submitted selected baby", sourceReferences: [{ kind: "symbol", file: "src/server/services/households.ts", exportName: "submitReactivateBabyBrowserOperation" }] }, target: { authority: "deferred", gateId: "gate.carrier_authority_guard" } },
    caller_controlled_scope: { current: { authority: "source_reviewed", value: "submitReactivateBabyBrowserOperation parses the submitted babyId and binds its immutable browser intent", sourceReferences: [{ kind: "symbol", file: "src/server/services/households.ts", exportName: "submitReactivateBabyBrowserOperation" }] }, target: { authority: "deferred", gateId: "gate.caller_controlled_scope" } },
    service_operation_linkage: { current: { authority: "source_reviewed", value: "submitReactivateBabyBrowserOperation is the browser-operation execution adapter for baby.reactivate", sourceReferences: [{ kind: "symbol", file: "src/server/services/households.ts", exportName: "submitReactivateBabyBrowserOperation" }] }, target: { authority: "deferred", gateId: "gate.service_operation_linkage" } },
    permission_commit_reauthorization: { current: { authority: "source_reviewed", value: "submitReactivateBabyBrowserOperation delegates transaction-local permission reauthorization to executeBrowserOperation", sourceReferences: [{ kind: "symbol", file: "src/server/services/households.ts", exportName: "submitReactivateBabyBrowserOperation" }] }, target: { authority: "deferred", gateId: "gate.permission_commit_reauthorization" } },
    tenant_relationship_invariants: { current: { authority: "source_reviewed", value: "submitReactivateBabyBrowserOperation validates the locked selected baby against its bound lifecycle snapshot", sourceReferences: [{ kind: "symbol", file: "src/server/services/households.ts", exportName: "submitReactivateBabyBrowserOperation" }] }, target: { authority: "deferred", gateId: "gate.tenant_relationship_invariants" } },
    model_reads_writes_effects: { current: { authority: "source_reviewed", value: "submitReactivateBabyBrowserOperation writes the lifecycle transition and audit only in the browser-operation transaction callback", sourceReferences: [{ kind: "symbol", file: "src/server/services/households.ts", exportName: "submitReactivateBabyBrowserOperation" }] }, target: { authority: "deferred", gateId: "gate.model_and_effects" } },
    variant_specific_outcomes: { current: { authority: "not_applicable", rationale: "submitReactivateBabyBrowserOperation has no declared semantic variant", sourceReferences: [{ kind: "symbol", file: "src/server/services/households.ts", exportName: "submitReactivateBabyBrowserOperation" }] }, target: { authority: "deferred", gateId: "gate.variant_outcomes" } },
    worker_loop_claim_failure_containment: { current: { authority: "not_applicable", rationale: "submitReactivateBabyBrowserOperation does not contain a worker loop", sourceReferences: [{ kind: "symbol", file: "src/server/services/households.ts", exportName: "submitReactivateBabyBrowserOperation" }] }, target: { authority: "deferred", gateId: "gate.worker_containment" } },
    browser_immutable_binding_stale_behavior: { current: { authority: "deferred", gateId: "gate.browser_binding_staleness" }, target: { authority: "deferred", gateId: "gate.browser_binding_staleness" } },
    executable_evidence_strength: { current: { authority: "deferred", gateId: "gate.executable_evidence" }, target: { authority: "deferred", gateId: "gate.executable_evidence" } }
  }
}] as const satisfies readonly SemanticServiceOperationDeclaration[];
