import type { SemanticServiceOperationDeclaration } from "@/server/operation-registry/schema";

export const semantic = [{
  kind: "service", id: "baby.create", ownerModule: "src/server/services/households.ts", exportName: "addBaby",
  axes: {
    carrier_authority_guard: { current: { authority: "source_reviewed", value: "addBaby calls getHouseholdContext() without a household id, so the helper's current first active membership ordered by joinedAt ascending is selected", sourceReferences: [{ kind: "symbol", file: "src/server/services/households.ts", exportName: "addBaby" }] }, target: { authority: "deferred", gateId: "gate.carrier_authority_guard" } },
    caller_controlled_scope: { current: { authority: "source_reviewed", value: "addBaby parses raw input with babySchema", sourceReferences: [{ kind: "symbol", file: "src/server/services/households.ts", exportName: "addBaby" }] }, target: { authority: "deferred", gateId: "gate.caller_controlled_scope" } },
    service_operation_linkage: { current: { authority: "source_reviewed", value: "addBaby is the exported baby creation service", sourceReferences: [{ kind: "symbol", file: "src/server/services/households.ts", exportName: "addBaby" }] }, target: { authority: "deferred", gateId: "gate.service_operation_linkage" } },
    permission_commit_reauthorization: { current: { authority: "source_reviewed", value: "addBaby requires baby.manage before its Prisma create and contains no transaction-local membership recheck", sourceReferences: [{ kind: "symbol", file: "src/server/services/households.ts", exportName: "addBaby" }] }, target: { authority: "deferred", gateId: "gate.permission_commit_reauthorization" } },
    tenant_relationship_invariants: { current: { authority: "source_reviewed", value: "addBaby supplies the selected context householdId on the Baby create call", sourceReferences: [{ kind: "symbol", file: "src/server/services/households.ts", exportName: "addBaby" }] }, target: { authority: "deferred", gateId: "gate.tenant_relationship_invariants" } },
    model_reads_writes_effects: { current: { authority: "source_reviewed", value: "the source calls prisma.baby.create and then writeAudit with baby.create", sourceReferences: [{ kind: "symbol", file: "src/server/services/households.ts", exportName: "addBaby" }] }, target: { authority: "deferred", gateId: "gate.model_and_effects" } },
    variant_specific_outcomes: { current: { authority: "not_applicable", rationale: "addBaby has no declared semantic variant", sourceReferences: [{ kind: "symbol", file: "src/server/services/households.ts", exportName: "addBaby" }] }, target: { authority: "deferred", gateId: "gate.variant_outcomes" } },
    worker_loop_claim_failure_containment: { current: { authority: "not_applicable", rationale: "addBaby does not contain a worker loop", sourceReferences: [{ kind: "symbol", file: "src/server/services/households.ts", exportName: "addBaby" }] }, target: { authority: "deferred", gateId: "gate.worker_containment" } },
    browser_immutable_binding_stale_behavior: { current: { authority: "deferred", gateId: "gate.browser_binding_staleness" }, target: { authority: "deferred", gateId: "gate.browser_binding_staleness" } },
    executable_evidence_strength: { current: { authority: "deferred", gateId: "gate.executable_evidence" }, target: { authority: "deferred", gateId: "gate.executable_evidence" } }
  }
}, {
  kind: "service", id: "baby.deactivate", ownerModule: "src/server/services/households.ts", exportName: "deactivateBaby",
  axes: {
    carrier_authority_guard: { current: { authority: "source_reviewed", value: "deactivateBaby calls getHouseholdContext() without a household id, so the helper's current first active membership ordered by joinedAt ascending is selected", sourceReferences: [{ kind: "symbol", file: "src/server/services/households.ts", exportName: "deactivateBaby" }] }, target: { authority: "deferred", gateId: "gate.carrier_authority_guard" } },
    caller_controlled_scope: { current: { authority: "source_reviewed", value: "deactivateBaby accepts a baby id and an optional inactiveAt value", sourceReferences: [{ kind: "symbol", file: "src/server/services/households.ts", exportName: "deactivateBaby" }] }, target: { authority: "deferred", gateId: "gate.caller_controlled_scope" } },
    service_operation_linkage: { current: { authority: "source_reviewed", value: "deactivateBaby is the exported baby deactivation service", sourceReferences: [{ kind: "symbol", file: "src/server/services/households.ts", exportName: "deactivateBaby" }] }, target: { authority: "deferred", gateId: "gate.service_operation_linkage" } },
    permission_commit_reauthorization: { current: { authority: "source_reviewed", value: "deactivateBaby requires baby.manage before its transaction and again after lockActorAndBabyForWrite", sourceReferences: [{ kind: "symbol", file: "src/server/services/households.ts", exportName: "deactivateBaby" }] }, target: { authority: "deferred", gateId: "gate.permission_commit_reauthorization" } },
    tenant_relationship_invariants: { current: { authority: "source_reviewed", value: "deactivateBaby uses lockActorAndBabyForWrite and scopes its active-timer lookup to the locked household and baby", sourceReferences: [{ kind: "symbol", file: "src/server/services/households.ts", exportName: "deactivateBaby" }] }, target: { authority: "deferred", gateId: "gate.tenant_relationship_invariants" } },
    model_reads_writes_effects: { current: { authority: "source_reviewed", value: "the source checks for a running or paused ActivityLog, calls tx.baby.update for inactiveAt, and writes a baby.deactivate audit", sourceReferences: [{ kind: "symbol", file: "src/server/services/households.ts", exportName: "deactivateBaby" }] }, target: { authority: "deferred", gateId: "gate.model_and_effects" } },
    variant_specific_outcomes: { current: { authority: "not_applicable", rationale: "deactivateBaby has no declared semantic variant", sourceReferences: [{ kind: "symbol", file: "src/server/services/households.ts", exportName: "deactivateBaby" }] }, target: { authority: "deferred", gateId: "gate.variant_outcomes" } },
    worker_loop_claim_failure_containment: { current: { authority: "not_applicable", rationale: "deactivateBaby does not contain a worker loop", sourceReferences: [{ kind: "symbol", file: "src/server/services/households.ts", exportName: "deactivateBaby" }] }, target: { authority: "deferred", gateId: "gate.worker_containment" } },
    browser_immutable_binding_stale_behavior: { current: { authority: "deferred", gateId: "gate.browser_binding_staleness" }, target: { authority: "deferred", gateId: "gate.browser_binding_staleness" } },
    executable_evidence_strength: { current: { authority: "deferred", gateId: "gate.executable_evidence" }, target: { authority: "deferred", gateId: "gate.executable_evidence" } }
  }
}, {
  kind: "service", id: "baby.reactivate", ownerModule: "src/server/services/households.ts", exportName: "reactivateBaby",
  axes: {
    carrier_authority_guard: { current: { authority: "source_reviewed", value: "reactivateBaby calls getHouseholdContext() without a household id, so the helper's current first active membership ordered by joinedAt ascending is selected", sourceReferences: [{ kind: "symbol", file: "src/server/services/households.ts", exportName: "reactivateBaby" }] }, target: { authority: "deferred", gateId: "gate.carrier_authority_guard" } },
    caller_controlled_scope: { current: { authority: "source_reviewed", value: "reactivateBaby accepts a baby id", sourceReferences: [{ kind: "symbol", file: "src/server/services/households.ts", exportName: "reactivateBaby" }] }, target: { authority: "deferred", gateId: "gate.caller_controlled_scope" } },
    service_operation_linkage: { current: { authority: "source_reviewed", value: "reactivateBaby is the exported baby reactivation service", sourceReferences: [{ kind: "symbol", file: "src/server/services/households.ts", exportName: "reactivateBaby" }] }, target: { authority: "deferred", gateId: "gate.service_operation_linkage" } },
    permission_commit_reauthorization: { current: { authority: "source_reviewed", value: "reactivateBaby requires baby.manage before its transaction and again after lockActorAndBabyForWrite", sourceReferences: [{ kind: "symbol", file: "src/server/services/households.ts", exportName: "reactivateBaby" }] }, target: { authority: "deferred", gateId: "gate.permission_commit_reauthorization" } },
    tenant_relationship_invariants: { current: { authority: "source_reviewed", value: "reactivateBaby obtains the target through lockActorAndBabyForWrite with the selected context and baby id", sourceReferences: [{ kind: "symbol", file: "src/server/services/households.ts", exportName: "reactivateBaby" }] }, target: { authority: "deferred", gateId: "gate.tenant_relationship_invariants" } },
    model_reads_writes_effects: { current: { authority: "source_reviewed", value: "the source calls tx.baby.update to clear inactiveAt and writes a baby.reactivate audit", sourceReferences: [{ kind: "symbol", file: "src/server/services/households.ts", exportName: "reactivateBaby" }] }, target: { authority: "deferred", gateId: "gate.model_and_effects" } },
    variant_specific_outcomes: { current: { authority: "not_applicable", rationale: "reactivateBaby has no declared semantic variant", sourceReferences: [{ kind: "symbol", file: "src/server/services/households.ts", exportName: "reactivateBaby" }] }, target: { authority: "deferred", gateId: "gate.variant_outcomes" } },
    worker_loop_claim_failure_containment: { current: { authority: "not_applicable", rationale: "reactivateBaby does not contain a worker loop", sourceReferences: [{ kind: "symbol", file: "src/server/services/households.ts", exportName: "reactivateBaby" }] }, target: { authority: "deferred", gateId: "gate.worker_containment" } },
    browser_immutable_binding_stale_behavior: { current: { authority: "deferred", gateId: "gate.browser_binding_staleness" }, target: { authority: "deferred", gateId: "gate.browser_binding_staleness" } },
    executable_evidence_strength: { current: { authority: "deferred", gateId: "gate.executable_evidence" }, target: { authority: "deferred", gateId: "gate.executable_evidence" } }
  }
}] as const satisfies readonly SemanticServiceOperationDeclaration[];
