import type { SemanticServiceOperationDeclaration } from "@/server/operation-registry/schema";

export const semantic = [{
  kind: "service", id: "notification.preference.save", ownerModule: "src/server/services/integrations.ts", exportName: "saveNotificationPreference",
  axes: {
    carrier_authority_guard: { current: { authority: "source_reviewed", value: "saveNotificationPreference calls getHouseholdContext() without a household id, so the helper's current first active membership ordered by joinedAt ascending is selected", sourceReferences: [{ kind: "symbol", file: "src/server/services/integrations.ts", exportName: "saveNotificationPreference" }] }, target: { authority: "deferred", gateId: "gate.carrier_authority_guard" } },
    caller_controlled_scope: { current: { authority: "source_reviewed", value: "saveNotificationPreference parses raw input with preferencesSchema, including caller-supplied babyId and preference fields", sourceReferences: [{ kind: "symbol", file: "src/server/services/integrations.ts", exportName: "saveNotificationPreference" }] }, target: { authority: "deferred", gateId: "gate.caller_controlled_scope" } },
    service_operation_linkage: { current: { authority: "source_reviewed", value: "saveNotificationPreference is the exported notification preference creation service", sourceReferences: [{ kind: "symbol", file: "src/server/services/integrations.ts", exportName: "saveNotificationPreference" }] }, target: { authority: "deferred", gateId: "gate.service_operation_linkage" } },
    permission_commit_reauthorization: { current: { authority: "source_reviewed", value: "saveNotificationPreference requires notification.manage before its transaction, locks the actor, and requires the permission again before create", sourceReferences: [{ kind: "symbol", file: "src/server/services/integrations.ts", exportName: "saveNotificationPreference" }] }, target: { authority: "deferred", gateId: "gate.permission_commit_reauthorization" } },
    tenant_relationship_invariants: { current: { authority: "source_reviewed", value: "the create data uses the locked household and user ids with the caller-supplied babyId; this export contains no explicit baby-household lookup", sourceReferences: [{ kind: "symbol", file: "src/server/services/integrations.ts", exportName: "saveNotificationPreference" }] }, target: { authority: "deferred", gateId: "gate.tenant_relationship_invariants" } },
    model_reads_writes_effects: { current: { authority: "source_reviewed", value: "the source calls tx.notificationPreference.create inside the actor-lock transaction", sourceReferences: [{ kind: "symbol", file: "src/server/services/integrations.ts", exportName: "saveNotificationPreference" }] }, target: { authority: "deferred", gateId: "gate.model_and_effects" } },
    variant_specific_outcomes: { current: { authority: "not_applicable", rationale: "saveNotificationPreference has no declared semantic variant", sourceReferences: [{ kind: "symbol", file: "src/server/services/integrations.ts", exportName: "saveNotificationPreference" }] }, target: { authority: "deferred", gateId: "gate.variant_outcomes" } },
    worker_loop_claim_failure_containment: { current: { authority: "not_applicable", rationale: "saveNotificationPreference does not contain a worker loop", sourceReferences: [{ kind: "symbol", file: "src/server/services/integrations.ts", exportName: "saveNotificationPreference" }] }, target: { authority: "deferred", gateId: "gate.worker_containment" } },
    browser_immutable_binding_stale_behavior: { current: { authority: "deferred", gateId: "gate.browser_binding_staleness" }, target: { authority: "deferred", gateId: "gate.browser_binding_staleness" } },
    executable_evidence_strength: { current: { authority: "deferred", gateId: "gate.executable_evidence" }, target: { authority: "deferred", gateId: "gate.executable_evidence" } }
  }
}] as const satisfies readonly SemanticServiceOperationDeclaration[];
