import type { SemanticServiceOperationDeclaration } from "@/server/operation-registry/schema";

export const semantic = [{
  kind: "service", id: "invite.create", ownerModule: "src/server/services/invites.ts", exportName: "createInvite",
  axes: {
    carrier_authority_guard: { current: { authority: "source_reviewed", value: "createInvite calls getEffectiveHouseholdContext(), which requires the request's validated membership-episode cookie candidate and does not fall back to another membership", sourceReferences: [{ kind: "symbol", file: "src/server/services/invites.ts", exportName: "createInvite" }] }, target: { authority: "deferred", gateId: "gate.carrier_authority_guard" } },
    caller_controlled_scope: { current: { authority: "source_reviewed", value: "createInvite parses raw email, role, and expiry input with inviteSchema", sourceReferences: [{ kind: "symbol", file: "src/server/services/invites.ts", exportName: "createInvite" }] }, target: { authority: "deferred", gateId: "gate.caller_controlled_scope" } },
    service_operation_linkage: { current: { authority: "source_reviewed", value: "createInvite is the exported invitation creation service", sourceReferences: [{ kind: "symbol", file: "src/server/services/invites.ts", exportName: "createInvite" }] }, target: { authority: "deferred", gateId: "gate.service_operation_linkage" } },
    permission_commit_reauthorization: { current: { authority: "source_reviewed", value: "createInvite checks invite.create before its transaction, re-reads the actor with lockMemberMutation, checks permission and role assignment, and revalidates a fresh session for admin invites", sourceReferences: [{ kind: "symbol", file: "src/server/services/invites.ts", exportName: "createInvite" }] }, target: { authority: "deferred", gateId: "gate.permission_commit_reauthorization" } },
    tenant_relationship_invariants: { current: { authority: "source_reviewed", value: "the source locks pending invites by the locked actor household id and supplies that household id on the new Invite", sourceReferences: [{ kind: "symbol", file: "src/server/services/invites.ts", exportName: "createInvite" }] }, target: { authority: "deferred", gateId: "gate.tenant_relationship_invariants" } },
    model_reads_writes_effects: { current: { authority: "source_reviewed", value: "the source revokes matching pending invites, calls tx.invite.create, and writes invite.rotate and invite.create audits", sourceReferences: [{ kind: "symbol", file: "src/server/services/invites.ts", exportName: "createInvite" }] }, target: { authority: "deferred", gateId: "gate.model_and_effects" } },
    variant_specific_outcomes: { current: { authority: "not_applicable", rationale: "createInvite has no declared semantic variant", sourceReferences: [{ kind: "symbol", file: "src/server/services/invites.ts", exportName: "createInvite" }] }, target: { authority: "deferred", gateId: "gate.variant_outcomes" } },
    worker_loop_claim_failure_containment: { current: { authority: "not_applicable", rationale: "createInvite does not contain a worker loop", sourceReferences: [{ kind: "symbol", file: "src/server/services/invites.ts", exportName: "createInvite" }] }, target: { authority: "deferred", gateId: "gate.worker_containment" } },
    browser_immutable_binding_stale_behavior: { current: { authority: "deferred", gateId: "gate.browser_binding_staleness" }, target: { authority: "deferred", gateId: "gate.browser_binding_staleness" } },
    executable_evidence_strength: { current: { authority: "deferred", gateId: "gate.executable_evidence" }, target: { authority: "deferred", gateId: "gate.executable_evidence" } }
  }
}, {
  kind: "service", id: "invite.revoke", ownerModule: "src/server/services/invites.ts", exportName: "submitInviteRevokeBrowserOperation",
  axes: {
    carrier_authority_guard: { current: { authority: "source_reviewed", value: "submitInviteRevokeBrowserOperation calls getEffectiveHouseholdContext(), which requires the request's validated membership-episode cookie candidate and does not fall back to another membership", sourceReferences: [{ kind: "symbol", file: "src/server/services/invites.ts", exportName: "submitInviteRevokeBrowserOperation" }] }, target: { authority: "deferred", gateId: "gate.carrier_authority_guard" } },
    caller_controlled_scope: { current: { authority: "source_reviewed", value: "submitInviteRevokeBrowserOperation accepts one invite ID from the linked route path", sourceReferences: [{ kind: "symbol", file: "src/server/services/invites.ts", exportName: "submitInviteRevokeBrowserOperation" }] }, target: { authority: "deferred", gateId: "gate.caller_controlled_scope" } },
    service_operation_linkage: { current: { authority: "source_reviewed", value: "submitInviteRevokeBrowserOperation is the exported single-invitation revocation service", sourceReferences: [{ kind: "symbol", file: "src/server/services/invites.ts", exportName: "submitInviteRevokeBrowserOperation" }] }, target: { authority: "deferred", gateId: "gate.service_operation_linkage" } },
    permission_commit_reauthorization: { current: { authority: "source_reviewed", value: "submitInviteRevokeBrowserOperation locks and rereads the acting member inside its transaction before rechecking member.manage and the target-role boundary", sourceReferences: [{ kind: "symbol", file: "src/server/services/invites.ts", exportName: "submitInviteRevokeBrowserOperation" }] }, target: { authority: "deferred", gateId: "gate.permission_commit_reauthorization" } },
    tenant_relationship_invariants: { current: { authority: "source_reviewed", value: "submitInviteRevokeBrowserOperation locks the target Invite and rejects an invite outside the locked actor household", sourceReferences: [{ kind: "symbol", file: "src/server/services/invites.ts", exportName: "submitInviteRevokeBrowserOperation" }] }, target: { authority: "deferred", gateId: "gate.tenant_relationship_invariants" } },
    model_reads_writes_effects: { current: { authority: "source_reviewed", value: "submitInviteRevokeBrowserOperation updates one pending Invite to revoked and writes an invite.revoke audit", sourceReferences: [{ kind: "symbol", file: "src/server/services/invites.ts", exportName: "submitInviteRevokeBrowserOperation" }] }, target: { authority: "deferred", gateId: "gate.model_and_effects" } },
    variant_specific_outcomes: { current: { authority: "not_applicable", rationale: "submitInviteRevokeBrowserOperation has no declared semantic variant", sourceReferences: [{ kind: "symbol", file: "src/server/services/invites.ts", exportName: "submitInviteRevokeBrowserOperation" }] }, target: { authority: "deferred", gateId: "gate.variant_outcomes" } },
    worker_loop_claim_failure_containment: { current: { authority: "not_applicable", rationale: "submitInviteRevokeBrowserOperation does not contain a worker loop", sourceReferences: [{ kind: "symbol", file: "src/server/services/invites.ts", exportName: "submitInviteRevokeBrowserOperation" }] }, target: { authority: "deferred", gateId: "gate.worker_containment" } },
    browser_immutable_binding_stale_behavior: { current: { authority: "deferred", gateId: "gate.browser_binding_staleness" }, target: { authority: "deferred", gateId: "gate.browser_binding_staleness" } },
    executable_evidence_strength: { current: { authority: "deferred", gateId: "gate.executable_evidence" }, target: { authority: "deferred", gateId: "gate.executable_evidence" } }
  }
}, {
  kind: "service", id: "invite.revoke_all", ownerModule: "src/server/services/invites.ts", exportName: "revokeAllPendingInvites",
  axes: {
    carrier_authority_guard: { current: { authority: "source_reviewed", value: "revokeAllPendingInvites calls getEffectiveHouseholdContext(), which requires the request's validated membership-episode cookie candidate and does not fall back to another membership", sourceReferences: [{ kind: "symbol", file: "src/server/services/invites.ts", exportName: "revokeAllPendingInvites" }] }, target: { authority: "deferred", gateId: "gate.carrier_authority_guard" } },
    caller_controlled_scope: { current: { authority: "source_reviewed", value: "revokeAllPendingInvites parses raw input and requires the exact bulk-revoke acknowledgement", sourceReferences: [{ kind: "symbol", file: "src/server/services/invites.ts", exportName: "revokeAllPendingInvites" }] }, target: { authority: "deferred", gateId: "gate.caller_controlled_scope" } },
    service_operation_linkage: { current: { authority: "source_reviewed", value: "revokeAllPendingInvites is the exported bulk invitation revocation service", sourceReferences: [{ kind: "symbol", file: "src/server/services/invites.ts", exportName: "revokeAllPendingInvites" }] }, target: { authority: "deferred", gateId: "gate.service_operation_linkage" } },
    permission_commit_reauthorization: { current: { authority: "source_reviewed", value: "inside its transaction revokeAllPendingInvites re-reads the actor with lockMemberMutation, requires the owner role, and revalidates the fresh session", sourceReferences: [{ kind: "symbol", file: "src/server/services/invites.ts", exportName: "revokeAllPendingInvites" }] }, target: { authority: "deferred", gateId: "gate.permission_commit_reauthorization" } },
    tenant_relationship_invariants: { current: { authority: "source_reviewed", value: "the source locks and reads only pending Invite rows whose householdId equals the locked actor household id", sourceReferences: [{ kind: "symbol", file: "src/server/services/invites.ts", exportName: "revokeAllPendingInvites" }] }, target: { authority: "deferred", gateId: "gate.tenant_relationship_invariants" } },
    model_reads_writes_effects: { current: { authority: "source_reviewed", value: "the source updates each locked pending Invite to revoked and writes per-invite and household bulk-revoke audits", sourceReferences: [{ kind: "symbol", file: "src/server/services/invites.ts", exportName: "revokeAllPendingInvites" }] }, target: { authority: "deferred", gateId: "gate.model_and_effects" } },
    variant_specific_outcomes: { current: { authority: "not_applicable", rationale: "revokeAllPendingInvites has no declared semantic variant", sourceReferences: [{ kind: "symbol", file: "src/server/services/invites.ts", exportName: "revokeAllPendingInvites" }] }, target: { authority: "deferred", gateId: "gate.variant_outcomes" } },
    worker_loop_claim_failure_containment: { current: { authority: "not_applicable", rationale: "revokeAllPendingInvites does not contain a worker loop", sourceReferences: [{ kind: "symbol", file: "src/server/services/invites.ts", exportName: "revokeAllPendingInvites" }] }, target: { authority: "deferred", gateId: "gate.worker_containment" } },
    browser_immutable_binding_stale_behavior: { current: { authority: "deferred", gateId: "gate.browser_binding_staleness" }, target: { authority: "deferred", gateId: "gate.browser_binding_staleness" } },
    executable_evidence_strength: { current: { authority: "deferred", gateId: "gate.executable_evidence" }, target: { authority: "deferred", gateId: "gate.executable_evidence" } }
  }
}, {
  kind: "service", id: "member.restore", ownerModule: "src/server/services/invites.ts", exportName: "restoreMember",
  axes: {
    carrier_authority_guard: { current: { authority: "source_reviewed", value: "restoreMember calls getEffectiveHouseholdContext(), which requires the request's validated membership-episode cookie candidate and does not fall back to another membership", sourceReferences: [{ kind: "symbol", file: "src/server/services/invites.ts", exportName: "restoreMember" }] }, target: { authority: "deferred", gateId: "gate.carrier_authority_guard" } },
    caller_controlled_scope: { current: { authority: "source_reviewed", value: "restoreMember accepts a target member id", sourceReferences: [{ kind: "symbol", file: "src/server/services/invites.ts", exportName: "restoreMember" }] }, target: { authority: "deferred", gateId: "gate.caller_controlled_scope" } },
    service_operation_linkage: { current: { authority: "source_reviewed", value: "restoreMember is the exported member restoration service", sourceReferences: [{ kind: "symbol", file: "src/server/services/invites.ts", exportName: "restoreMember" }] }, target: { authority: "deferred", gateId: "gate.service_operation_linkage" } },
    permission_commit_reauthorization: { current: { authority: "source_reviewed", value: "restoreMember checks member.manage before its transaction, then lockMemberMutation re-reads actor and target before permission, self-target, and role hierarchy checks", sourceReferences: [{ kind: "symbol", file: "src/server/services/invites.ts", exportName: "restoreMember" }] }, target: { authority: "deferred", gateId: "gate.permission_commit_reauthorization" } },
    tenant_relationship_invariants: { current: { authority: "source_reviewed", value: "lockMemberMutation rejects a target whose household differs from the re-read actor household", sourceReferences: [{ kind: "symbol", file: "src/server/services/invites.ts", exportName: "restoreMember" }] }, target: { authority: "deferred", gateId: "gate.tenant_relationship_invariants" } },
    model_reads_writes_effects: { current: { authority: "source_reviewed", value: "the source calls tx.householdMember.update to clear disabledAt and writes a member.restore audit", sourceReferences: [{ kind: "symbol", file: "src/server/services/invites.ts", exportName: "restoreMember" }] }, target: { authority: "deferred", gateId: "gate.model_and_effects" } },
    variant_specific_outcomes: { current: { authority: "not_applicable", rationale: "restoreMember has no declared semantic variant", sourceReferences: [{ kind: "symbol", file: "src/server/services/invites.ts", exportName: "restoreMember" }] }, target: { authority: "deferred", gateId: "gate.variant_outcomes" } },
    worker_loop_claim_failure_containment: { current: { authority: "not_applicable", rationale: "restoreMember does not contain a worker loop", sourceReferences: [{ kind: "symbol", file: "src/server/services/invites.ts", exportName: "restoreMember" }] }, target: { authority: "deferred", gateId: "gate.worker_containment" } },
    browser_immutable_binding_stale_behavior: { current: { authority: "deferred", gateId: "gate.browser_binding_staleness" }, target: { authority: "deferred", gateId: "gate.browser_binding_staleness" } },
    executable_evidence_strength: { current: { authority: "deferred", gateId: "gate.executable_evidence" }, target: { authority: "deferred", gateId: "gate.executable_evidence" } }
  }
}, {
  kind: "service", id: "member.remove", ownerModule: "src/server/services/invites.ts", exportName: "removeMember",
  axes: {
    carrier_authority_guard: { current: { authority: "source_reviewed", value: "removeMember calls getEffectiveHouseholdContext(), which requires the request's validated membership-episode cookie candidate and does not fall back to another membership", sourceReferences: [{ kind: "symbol", file: "src/server/services/invites.ts", exportName: "removeMember" }] }, target: { authority: "deferred", gateId: "gate.carrier_authority_guard" } },
    caller_controlled_scope: { current: { authority: "source_reviewed", value: "removeMember accepts a target member id", sourceReferences: [{ kind: "symbol", file: "src/server/services/invites.ts", exportName: "removeMember" }] }, target: { authority: "deferred", gateId: "gate.caller_controlled_scope" } },
    service_operation_linkage: { current: { authority: "source_reviewed", value: "removeMember is the exported member removal service", sourceReferences: [{ kind: "symbol", file: "src/server/services/invites.ts", exportName: "removeMember" }] }, target: { authority: "deferred", gateId: "gate.service_operation_linkage" } },
    permission_commit_reauthorization: { current: { authority: "source_reviewed", value: "removeMember checks member.manage before its transaction, then lockMemberMutation re-reads actor and target before permission and role hierarchy checks", sourceReferences: [{ kind: "symbol", file: "src/server/services/invites.ts", exportName: "removeMember" }] }, target: { authority: "deferred", gateId: "gate.permission_commit_reauthorization" } },
    tenant_relationship_invariants: { current: { authority: "source_reviewed", value: "lockMemberMutation rejects a target whose household differs from the re-read actor household", sourceReferences: [{ kind: "symbol", file: "src/server/services/invites.ts", exportName: "removeMember" }] }, target: { authority: "deferred", gateId: "gate.tenant_relationship_invariants" } },
    model_reads_writes_effects: { current: { authority: "source_reviewed", value: "the source sets HouseholdMember.deletedAt, retires delegated webhooks, contains member authority, and writes a member.remove audit", sourceReferences: [{ kind: "symbol", file: "src/server/services/invites.ts", exportName: "removeMember" }] }, target: { authority: "deferred", gateId: "gate.model_and_effects" } },
    variant_specific_outcomes: { current: { authority: "not_applicable", rationale: "removeMember has no declared semantic variant", sourceReferences: [{ kind: "symbol", file: "src/server/services/invites.ts", exportName: "removeMember" }] }, target: { authority: "deferred", gateId: "gate.variant_outcomes" } },
    worker_loop_claim_failure_containment: { current: { authority: "not_applicable", rationale: "removeMember does not contain a worker loop", sourceReferences: [{ kind: "symbol", file: "src/server/services/invites.ts", exportName: "removeMember" }] }, target: { authority: "deferred", gateId: "gate.worker_containment" } },
    browser_immutable_binding_stale_behavior: { current: { authority: "deferred", gateId: "gate.browser_binding_staleness" }, target: { authority: "deferred", gateId: "gate.browser_binding_staleness" } },
    executable_evidence_strength: { current: { authority: "deferred", gateId: "gate.executable_evidence" }, target: { authority: "deferred", gateId: "gate.executable_evidence" } }
  }
}, {
  kind: "service", id: "member.role.update", ownerModule: "src/server/services/invites.ts", exportName: "updateMemberRole",
  axes: {
    carrier_authority_guard: { current: { authority: "source_reviewed", value: "updateMemberRole calls getEffectiveHouseholdContext(), which requires the request's validated membership-episode cookie candidate and does not fall back to another membership", sourceReferences: [{ kind: "symbol", file: "src/server/services/invites.ts", exportName: "updateMemberRole" }] }, target: { authority: "deferred", gateId: "gate.carrier_authority_guard" } },
    caller_controlled_scope: { current: { authority: "source_reviewed", value: "updateMemberRole accepts a target member id and parses raw role input with memberRoleSchema", sourceReferences: [{ kind: "symbol", file: "src/server/services/invites.ts", exportName: "updateMemberRole" }] }, target: { authority: "deferred", gateId: "gate.caller_controlled_scope" } },
    service_operation_linkage: { current: { authority: "source_reviewed", value: "updateMemberRole is the exported member role update service", sourceReferences: [{ kind: "symbol", file: "src/server/services/invites.ts", exportName: "updateMemberRole" }] }, target: { authority: "deferred", gateId: "gate.service_operation_linkage" } },
    permission_commit_reauthorization: { current: { authority: "source_reviewed", value: "updateMemberRole checks member.manage before its transaction, then lockMemberMutation re-reads actor and target before permission, disabled-state, manage-role, and assign-role checks", sourceReferences: [{ kind: "symbol", file: "src/server/services/invites.ts", exportName: "updateMemberRole" }] }, target: { authority: "deferred", gateId: "gate.permission_commit_reauthorization" } },
    tenant_relationship_invariants: { current: { authority: "source_reviewed", value: "lockMemberMutation rejects a target whose household differs from the re-read actor household", sourceReferences: [{ kind: "symbol", file: "src/server/services/invites.ts", exportName: "updateMemberRole" }] }, target: { authority: "deferred", gateId: "gate.tenant_relationship_invariants" } },
    model_reads_writes_effects: { current: { authority: "source_reviewed", value: "the source calls tx.householdMember.update for role and writes the corresponding admin grant, admin revoke, or member.role.update audit", sourceReferences: [{ kind: "symbol", file: "src/server/services/invites.ts", exportName: "updateMemberRole" }] }, target: { authority: "deferred", gateId: "gate.model_and_effects" } },
    variant_specific_outcomes: { current: { authority: "not_applicable", rationale: "updateMemberRole has no declared semantic variant", sourceReferences: [{ kind: "symbol", file: "src/server/services/invites.ts", exportName: "updateMemberRole" }] }, target: { authority: "deferred", gateId: "gate.variant_outcomes" } },
    worker_loop_claim_failure_containment: { current: { authority: "not_applicable", rationale: "updateMemberRole does not contain a worker loop", sourceReferences: [{ kind: "symbol", file: "src/server/services/invites.ts", exportName: "updateMemberRole" }] }, target: { authority: "deferred", gateId: "gate.worker_containment" } },
    browser_immutable_binding_stale_behavior: { current: { authority: "deferred", gateId: "gate.browser_binding_staleness" }, target: { authority: "deferred", gateId: "gate.browser_binding_staleness" } },
    executable_evidence_strength: { current: { authority: "deferred", gateId: "gate.executable_evidence" }, target: { authority: "deferred", gateId: "gate.executable_evidence" } }
  }
}, {
  kind: "service", id: "member.suspend", ownerModule: "src/server/services/invites.ts", exportName: "suspendMember",
  axes: {
    carrier_authority_guard: { current: { authority: "source_reviewed", value: "suspendMember calls getEffectiveHouseholdContext(), which requires the request's validated membership-episode cookie candidate and does not fall back to another membership", sourceReferences: [{ kind: "symbol", file: "src/server/services/invites.ts", exportName: "suspendMember" }] }, target: { authority: "deferred", gateId: "gate.carrier_authority_guard" } },
    caller_controlled_scope: { current: { authority: "source_reviewed", value: "suspendMember accepts a target member id and an optional disabledAt value", sourceReferences: [{ kind: "symbol", file: "src/server/services/invites.ts", exportName: "suspendMember" }] }, target: { authority: "deferred", gateId: "gate.caller_controlled_scope" } },
    service_operation_linkage: { current: { authority: "source_reviewed", value: "suspendMember is the exported member suspension service", sourceReferences: [{ kind: "symbol", file: "src/server/services/invites.ts", exportName: "suspendMember" }] }, target: { authority: "deferred", gateId: "gate.service_operation_linkage" } },
    permission_commit_reauthorization: { current: { authority: "source_reviewed", value: "suspendMember checks member.manage before its transaction, then lockMemberMutation re-reads actor and target before permission, self-target, and role hierarchy checks", sourceReferences: [{ kind: "symbol", file: "src/server/services/invites.ts", exportName: "suspendMember" }] }, target: { authority: "deferred", gateId: "gate.permission_commit_reauthorization" } },
    tenant_relationship_invariants: { current: { authority: "source_reviewed", value: "lockMemberMutation rejects a target whose household differs from the re-read actor household", sourceReferences: [{ kind: "symbol", file: "src/server/services/invites.ts", exportName: "suspendMember" }] }, target: { authority: "deferred", gateId: "gate.tenant_relationship_invariants" } },
    model_reads_writes_effects: { current: { authority: "source_reviewed", value: "the source sets HouseholdMember.disabledAt, retires delegated webhooks, contains member authority, deletes the user's sessions, and writes a member.suspend audit", sourceReferences: [{ kind: "symbol", file: "src/server/services/invites.ts", exportName: "suspendMember" }] }, target: { authority: "deferred", gateId: "gate.model_and_effects" } },
    variant_specific_outcomes: { current: { authority: "not_applicable", rationale: "suspendMember has no declared semantic variant", sourceReferences: [{ kind: "symbol", file: "src/server/services/invites.ts", exportName: "suspendMember" }] }, target: { authority: "deferred", gateId: "gate.variant_outcomes" } },
    worker_loop_claim_failure_containment: { current: { authority: "not_applicable", rationale: "suspendMember does not contain a worker loop", sourceReferences: [{ kind: "symbol", file: "src/server/services/invites.ts", exportName: "suspendMember" }] }, target: { authority: "deferred", gateId: "gate.worker_containment" } },
    browser_immutable_binding_stale_behavior: { current: { authority: "deferred", gateId: "gate.browser_binding_staleness" }, target: { authority: "deferred", gateId: "gate.browser_binding_staleness" } },
    executable_evidence_strength: { current: { authority: "deferred", gateId: "gate.executable_evidence" }, target: { authority: "deferred", gateId: "gate.executable_evidence" } }
  }
}] as const satisfies readonly SemanticServiceOperationDeclaration[];
