import type { SemanticServiceOperationDeclaration } from "@/server/operation-registry/schema";

export const semantic = [{
  kind: "service", id: "notification.preference.save", ownerModule: "src/server/services/notification-preferences.ts", exportName: "submitNotificationPreferenceBrowserOperation",
  axes: {
    carrier_authority_guard: { current: { authority: "source_reviewed", value: "Uses the validated effective household membership episode from the browser-operation context.", sourceReferences: [{ kind: "symbol", file: "src/server/services/notification-preferences.ts", exportName: "submitNotificationPreferenceBrowserOperation" }] }, target: { authority: "deferred", gateId: "gate.carrier_authority_guard" } },
    caller_controlled_scope: { current: { authority: "source_reviewed", value: "Does not accept a household or member target from the payload; selected baby ids are validated inside the transaction against the locked household.", sourceReferences: [{ kind: "symbol", file: "src/server/services/notification-preferences.ts", exportName: "submitNotificationPreferenceBrowserOperation" }] }, target: { authority: "deferred", gateId: "gate.caller_controlled_scope" } },
    service_operation_linkage: { current: { authority: "source_reviewed", value: "Submits notification.preference.save through the household browser-operation adapter.", sourceReferences: [{ kind: "symbol", file: "src/server/services/notification-preferences.ts", exportName: "submitNotificationPreferenceBrowserOperation" }] }, target: { authority: "deferred", gateId: "gate.service_operation_linkage" } },
    permission_commit_reauthorization: { current: { authority: "source_reviewed", value: "Delegates notification.manage reauthorization and current-actor locking to executeHouseholdBrowserOperation.", sourceReferences: [{ kind: "symbol", file: "src/server/services/notification-preferences.ts", exportName: "submitNotificationPreferenceBrowserOperation" }] }, target: { authority: "deferred", gateId: "gate.permission_commit_reauthorization" } },
    tenant_relationship_invariants: { current: { authority: "source_reviewed", value: "Binds one document to the locked membership episode and validates each selected baby against the locked household before create or replacement.", sourceReferences: [{ kind: "symbol", file: "src/server/services/notification-preferences.ts", exportName: "submitNotificationPreferenceBrowserOperation" }] }, target: { authority: "deferred", gateId: "gate.tenant_relationship_invariants" } },
    model_reads_writes_effects: { current: { authority: "source_reviewed", value: "Locks and snapshots the membership-episode document, then writes its replacement and selected-baby joins transactionally with an audit record.", sourceReferences: [{ kind: "symbol", file: "src/server/services/notification-preferences.ts", exportName: "submitNotificationPreferenceBrowserOperation" }] }, target: { authority: "deferred", gateId: "gate.model_and_effects" } },
    variant_specific_outcomes: { current: { authority: "source_reviewed", value: "Returns the allowlisted active notification-preference outcome; stale targets are persisted by the browser-operation adapter.", sourceReferences: [{ kind: "symbol", file: "src/server/services/notification-preferences.ts", exportName: "submitNotificationPreferenceBrowserOperation" }] }, target: { authority: "deferred", gateId: "gate.variant_outcomes" } },
    worker_loop_claim_failure_containment: { current: { authority: "not_applicable", rationale: "No worker loop.", sourceReferences: [{ kind: "symbol", file: "src/server/services/notification-preferences.ts", exportName: "submitNotificationPreferenceBrowserOperation" }] }, target: { authority: "deferred", gateId: "gate.worker_containment" } },
    browser_immutable_binding_stale_behavior: { current: { authority: "deferred", gateId: "gate.browser_binding_staleness" }, target: { authority: "deferred", gateId: "gate.browser_binding_staleness" } },
    executable_evidence_strength: { current: { authority: "deferred", gateId: "gate.executable_evidence" }, target: { authority: "deferred", gateId: "gate.executable_evidence" } }
  }
}] as const satisfies readonly SemanticServiceOperationDeclaration[];
