import type { SemanticServiceOperationDeclaration } from "@/server/operation-registry/schema";

export const semantic = [{
  kind: "service",
  id: "platform.registration.allocate",
  ownerModule: "src/server/services/platform-authority.ts",
  exportName: "allocatePlatformRegistrationOperation",
  axes: {
    carrier_authority_guard: { current: { authority: "source_reviewed", value: "allocation requires the current user and reauthorizes the owner under the transaction lock", sourceReferences: [{ kind: "symbol", file: "src/server/services/platform-authority.ts", exportName: "allocatePlatformRegistrationOperation" }] }, target: { authority: "deferred", gateId: "gate.carrier_authority_guard" } },
    caller_controlled_scope: { current: { authority: "source_reviewed", value: "allocation parses the caller-supplied registration intent with the strict settings schema", sourceReferences: [{ kind: "symbol", file: "src/server/services/platform-authority.ts", exportName: "allocatePlatformRegistrationOperation" }] }, target: { authority: "deferred", gateId: "gate.caller_controlled_scope" } },
    service_operation_linkage: { current: { authority: "source_reviewed", value: "allocation creates a pending registration operation linked to the current owner and intent", sourceReferences: [{ kind: "symbol", file: "src/server/services/platform-authority.ts", exportName: "allocatePlatformRegistrationOperation" }] }, target: { authority: "deferred", gateId: "gate.service_operation_linkage" } },
    permission_commit_reauthorization: { current: { authority: "source_reviewed", value: "allocation reauthorizes the owner after entering the serializable transaction and before creating the operation", sourceReferences: [{ kind: "symbol", file: "src/server/services/platform-authority.ts", exportName: "allocatePlatformRegistrationOperation" }] }, target: { authority: "deferred", gateId: "gate.permission_commit_reauthorization" } },
    tenant_relationship_invariants: { current: { authority: "not_applicable", rationale: "allocation operates on the platform singleton rather than a tenant relationship", sourceReferences: [{ kind: "symbol", file: "src/server/services/platform-authority.ts", exportName: "allocatePlatformRegistrationOperation" }] }, target: { authority: "deferred", gateId: "gate.tenant_relationship_invariants" } },
    model_reads_writes_effects: { current: { authority: "source_reviewed", value: "allocation locks platform settings and creates a pending PlatformRegistrationOperation with the intent fingerprint and expected revision", sourceReferences: [{ kind: "symbol", file: "src/server/services/platform-authority.ts", exportName: "allocatePlatformRegistrationOperation" }] }, target: { authority: "deferred", gateId: "gate.model_and_effects" } },
    variant_specific_outcomes: { current: { authority: "not_applicable", rationale: "allocation has no semantic variant and returns a pending operation result", sourceReferences: [{ kind: "symbol", file: "src/server/services/platform-authority.ts", exportName: "allocatePlatformRegistrationOperation" }] }, target: { authority: "deferred", gateId: "gate.variant_outcomes" } },
    worker_loop_claim_failure_containment: { current: { authority: "not_applicable", rationale: "allocation does not run a worker loop", sourceReferences: [{ kind: "symbol", file: "src/server/services/platform-authority.ts", exportName: "allocatePlatformRegistrationOperation" }] }, target: { authority: "deferred", gateId: "gate.worker_containment" } },
    browser_immutable_binding_stale_behavior: { current: { authority: "deferred", gateId: "gate.browser_binding_staleness" }, target: { authority: "deferred", gateId: "gate.browser_binding_staleness" } },
    executable_evidence_strength: { current: { authority: "deferred", gateId: "gate.executable_evidence" }, target: { authority: "deferred", gateId: "gate.executable_evidence" } }
  }
}, {
  kind: "service",
  id: "platform.registration.complete",
  ownerModule: "src/server/services/platform-authority.ts",
  exportName: "completePlatformRegistrationOperation",
  axes: {
    carrier_authority_guard: { current: { authority: "source_reviewed", value: "completion requires the current user and reauthorizes the owner under the transaction lock", sourceReferences: [{ kind: "symbol", file: "src/server/services/platform-authority.ts", exportName: "completePlatformRegistrationOperation" }] }, target: { authority: "deferred", gateId: "gate.carrier_authority_guard" } },
    caller_controlled_scope: { current: { authority: "source_reviewed", value: "completion parses the caller-supplied operation ID and locks only that operation for the current user", sourceReferences: [{ kind: "symbol", file: "src/server/services/platform-authority.ts", exportName: "completePlatformRegistrationOperation" }] }, target: { authority: "deferred", gateId: "gate.caller_controlled_scope" } },
    service_operation_linkage: { current: { authority: "source_reviewed", value: "completion resolves the pending registration operation, applies its captured intent, and persists its outcome", sourceReferences: [{ kind: "symbol", file: "src/server/services/platform-authority.ts", exportName: "completePlatformRegistrationOperation" }] }, target: { authority: "deferred", gateId: "gate.service_operation_linkage" } },
    permission_commit_reauthorization: { current: { authority: "source_reviewed", value: "completion reauthorizes the owner after entering the serializable transaction and before settings or operation writes", sourceReferences: [{ kind: "symbol", file: "src/server/services/platform-authority.ts", exportName: "completePlatformRegistrationOperation" }] }, target: { authority: "deferred", gateId: "gate.permission_commit_reauthorization" } },
    tenant_relationship_invariants: { current: { authority: "not_applicable", rationale: "completion operates on the platform singleton rather than a tenant relationship", sourceReferences: [{ kind: "symbol", file: "src/server/services/platform-authority.ts", exportName: "completePlatformRegistrationOperation" }] }, target: { authority: "deferred", gateId: "gate.tenant_relationship_invariants" } },
    model_reads_writes_effects: { current: { authority: "source_reviewed", value: "completion conditionally updates PlatformSettings, records a PlatformAuditEvent, and persists completed or stale operation state", sourceReferences: [{ kind: "symbol", file: "src/server/services/platform-authority.ts", exportName: "completePlatformRegistrationOperation" }] }, target: { authority: "deferred", gateId: "gate.model_and_effects" } },
    variant_specific_outcomes: { current: { authority: "source_reviewed", value: "completion returns an existing non-pending result, a stale snapshot after revision loss, or a completed settings result", sourceReferences: [{ kind: "symbol", file: "src/server/services/platform-authority.ts", exportName: "completePlatformRegistrationOperation" }] }, target: { authority: "deferred", gateId: "gate.variant_outcomes" } },
    worker_loop_claim_failure_containment: { current: { authority: "not_applicable", rationale: "completion does not run a worker loop", sourceReferences: [{ kind: "symbol", file: "src/server/services/platform-authority.ts", exportName: "completePlatformRegistrationOperation" }] }, target: { authority: "deferred", gateId: "gate.worker_containment" } },
    browser_immutable_binding_stale_behavior: { current: { authority: "deferred", gateId: "gate.browser_binding_staleness" }, target: { authority: "deferred", gateId: "gate.browser_binding_staleness" } },
    executable_evidence_strength: { current: { authority: "deferred", gateId: "gate.executable_evidence" }, target: { authority: "deferred", gateId: "gate.executable_evidence" } }
  }
}, {
  kind: "service",
  id: "platform.registration.settings",
  ownerModule: "src/server/services/platform-authority.ts",
  exportName: "getPlatformRegistrationSettings",
  axes: {
    carrier_authority_guard: { current: { authority: "source_reviewed", value: "settings retrieval requires the platform owner context", sourceReferences: [{ kind: "symbol", file: "src/server/services/platform-authority.ts", exportName: "getPlatformRegistrationSettings" }] }, target: { authority: "deferred", gateId: "gate.carrier_authority_guard" } },
    caller_controlled_scope: { current: { authority: "not_applicable", rationale: "settings retrieval accepts no caller-controlled input", sourceReferences: [{ kind: "symbol", file: "src/server/services/platform-authority.ts", exportName: "getPlatformRegistrationSettings" }] }, target: { authority: "deferred", gateId: "gate.caller_controlled_scope" } },
    service_operation_linkage: { current: { authority: "source_reviewed", value: "settings retrieval returns the platform singleton settings record", sourceReferences: [{ kind: "symbol", file: "src/server/services/platform-authority.ts", exportName: "getPlatformRegistrationSettings" }] }, target: { authority: "deferred", gateId: "gate.service_operation_linkage" } },
    permission_commit_reauthorization: { current: { authority: "not_applicable", rationale: "settings retrieval does not commit a mutation", sourceReferences: [{ kind: "symbol", file: "src/server/services/platform-authority.ts", exportName: "getPlatformRegistrationSettings" }] }, target: { authority: "deferred", gateId: "gate.permission_commit_reauthorization" } },
    tenant_relationship_invariants: { current: { authority: "not_applicable", rationale: "settings retrieval operates on the platform singleton rather than a tenant relationship", sourceReferences: [{ kind: "symbol", file: "src/server/services/platform-authority.ts", exportName: "getPlatformRegistrationSettings" }] }, target: { authority: "deferred", gateId: "gate.tenant_relationship_invariants" } },
    model_reads_writes_effects: { current: { authority: "source_reviewed", value: "settings retrieval reads PlatformSettings by the platform singleton ID and has no write effect", sourceReferences: [{ kind: "symbol", file: "src/server/services/platform-authority.ts", exportName: "getPlatformRegistrationSettings" }] }, target: { authority: "deferred", gateId: "gate.model_and_effects" } },
    variant_specific_outcomes: { current: { authority: "not_applicable", rationale: "settings retrieval has no semantic variant", sourceReferences: [{ kind: "symbol", file: "src/server/services/platform-authority.ts", exportName: "getPlatformRegistrationSettings" }] }, target: { authority: "deferred", gateId: "gate.variant_outcomes" } },
    worker_loop_claim_failure_containment: { current: { authority: "not_applicable", rationale: "settings retrieval does not run a worker loop", sourceReferences: [{ kind: "symbol", file: "src/server/services/platform-authority.ts", exportName: "getPlatformRegistrationSettings" }] }, target: { authority: "deferred", gateId: "gate.worker_containment" } },
    browser_immutable_binding_stale_behavior: { current: { authority: "deferred", gateId: "gate.browser_binding_staleness" }, target: { authority: "deferred", gateId: "gate.browser_binding_staleness" } },
    executable_evidence_strength: { current: { authority: "deferred", gateId: "gate.executable_evidence" }, target: { authority: "deferred", gateId: "gate.executable_evidence" } }
  }
}, {
  kind: "service",
  id: "platform.registration.operation-status",
  ownerModule: "src/server/services/platform-authority.ts",
  exportName: "getPlatformRegistrationOperationStatus",
  axes: {
    carrier_authority_guard: { current: { authority: "source_reviewed", value: "status retrieval requires the current user and reauthorizes the owner under the transaction lock", sourceReferences: [{ kind: "symbol", file: "src/server/services/platform-authority.ts", exportName: "getPlatformRegistrationOperationStatus" }] }, target: { authority: "deferred", gateId: "gate.carrier_authority_guard" } },
    caller_controlled_scope: { current: { authority: "source_reviewed", value: "status retrieval parses the caller-supplied operation ID and queries it only for the current user", sourceReferences: [{ kind: "symbol", file: "src/server/services/platform-authority.ts", exportName: "getPlatformRegistrationOperationStatus" }] }, target: { authority: "deferred", gateId: "gate.caller_controlled_scope" } },
    service_operation_linkage: { current: { authority: "source_reviewed", value: "status retrieval finds the caller-owned registration operation and returns its operation result", sourceReferences: [{ kind: "symbol", file: "src/server/services/platform-authority.ts", exportName: "getPlatformRegistrationOperationStatus" }] }, target: { authority: "deferred", gateId: "gate.service_operation_linkage" } },
    permission_commit_reauthorization: { current: { authority: "not_applicable", rationale: "status retrieval does not commit a mutation", sourceReferences: [{ kind: "symbol", file: "src/server/services/platform-authority.ts", exportName: "getPlatformRegistrationOperationStatus" }] }, target: { authority: "deferred", gateId: "gate.permission_commit_reauthorization" } },
    tenant_relationship_invariants: { current: { authority: "not_applicable", rationale: "status retrieval operates on the platform singleton rather than a tenant relationship", sourceReferences: [{ kind: "symbol", file: "src/server/services/platform-authority.ts", exportName: "getPlatformRegistrationOperationStatus" }] }, target: { authority: "deferred", gateId: "gate.tenant_relationship_invariants" } },
    model_reads_writes_effects: { current: { authority: "source_reviewed", value: "status retrieval reads the caller-owned PlatformRegistrationOperation and has no write effect", sourceReferences: [{ kind: "symbol", file: "src/server/services/platform-authority.ts", exportName: "getPlatformRegistrationOperationStatus" }] }, target: { authority: "deferred", gateId: "gate.model_and_effects" } },
    variant_specific_outcomes: { current: { authority: "source_reviewed", value: "status retrieval returns the pending form or the persisted completed or stale operation result", sourceReferences: [{ kind: "symbol", file: "src/server/services/platform-authority.ts", exportName: "getPlatformRegistrationOperationStatus" }] }, target: { authority: "deferred", gateId: "gate.variant_outcomes" } },
    worker_loop_claim_failure_containment: { current: { authority: "not_applicable", rationale: "status retrieval does not run a worker loop", sourceReferences: [{ kind: "symbol", file: "src/server/services/platform-authority.ts", exportName: "getPlatformRegistrationOperationStatus" }] }, target: { authority: "deferred", gateId: "gate.worker_containment" } },
    browser_immutable_binding_stale_behavior: { current: { authority: "deferred", gateId: "gate.browser_binding_staleness" }, target: { authority: "deferred", gateId: "gate.browser_binding_staleness" } },
    executable_evidence_strength: { current: { authority: "deferred", gateId: "gate.executable_evidence" }, target: { authority: "deferred", gateId: "gate.executable_evidence" } }
  }
}] as const satisfies readonly SemanticServiceOperationDeclaration[];
