BEGIN;

ALTER TABLE "GlobalSecurityEvent"
  ADD COLUMN "sequence" BIGINT GENERATED BY DEFAULT AS IDENTITY;
ALTER TABLE "GlobalSecurityEvent" ALTER COLUMN "sequence" SET NOT NULL;
ALTER TABLE "GlobalSecurityEvent" ADD COLUMN "incidentId" TEXT;
ALTER TABLE "GlobalSecurityEvent" ADD CONSTRAINT "GlobalSecurityEvent_incidentId_fkey"
  FOREIGN KEY ("incidentId") REFERENCES "GlobalSecurityIncident"("id") ON DELETE CASCADE ON UPDATE CASCADE;
CREATE UNIQUE INDEX "GlobalSecurityEvent_sequence_key" ON "GlobalSecurityEvent"("sequence");
CREATE UNIQUE INDEX "GlobalSecurityEvent_incidentId_key" ON "GlobalSecurityEvent"("incidentId");
CREATE INDEX "GlobalSecurityEvent_userId_sequence_idx" ON "GlobalSecurityEvent"("userId","sequence");
DROP INDEX "GlobalSecurityEvent_one_operation_outcome";
CREATE UNIQUE INDEX "GlobalSecurityEvent_userId_operationId_eventType_outcome_key" ON "GlobalSecurityEvent"("userId","operationId","eventType","outcome")
  WHERE "operationId" IS NOT NULL;

CREATE TABLE "GlobalSecurityThrottleKey" (
  "singletonId" INTEGER NOT NULL,
  "keyDigest" BYTEA NOT NULL,
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "verifiedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "GlobalSecurityThrottleKey_pkey" PRIMARY KEY ("singletonId")
);
ALTER TABLE "GlobalSecurityThrottleKey" ADD CONSTRAINT "GlobalSecurityThrottleKey_singleton_check" CHECK ("singletonId"=1);
ALTER TABLE "GlobalSecurityThrottleKey" ADD CONSTRAINT "GlobalSecurityThrottleKey_digest_check" CHECK (octet_length("keyDigest")=32);

ALTER TABLE "GlobalSecurityEvent" ADD CONSTRAINT "GlobalSecurityEvent_operation_incident_shape"
  CHECK (("eventType"='operation_outcome' AND "operationId" IS NOT NULL AND "incidentId" IS NULL)
    OR ("eventType"='throttle' AND "outcome"='quiet_started' AND "operationId" IS NULL AND "incidentId" IS NOT NULL)
    OR ("eventType" NOT IN ('operation_outcome','throttle') AND "incidentId" IS NULL));
ALTER TABLE "GlobalSecurityIncident" ADD CONSTRAINT "GlobalSecurityIncident_failure_count_check"
  CHECK ("failureCount" BETWEEN 1 AND 255);

CREATE OR REPLACE FUNCTION "guard_global_security_event_insert"()
RETURNS TRIGGER LANGUAGE plpgsql AS $$
DECLARE operation_row "GlobalSecurityOperation"%ROWTYPE; bound "GlobalSecurityOperationBinding"%ROWTYPE; incident_row "GlobalSecurityIncident"%ROWTYPE;
BEGIN
  IF NEW."safeProjection" <> '{}'::jsonb OR (NEW."eventType"<>'operation_outcome' AND NOT (
    (NEW."eventType"='credential' AND NEW."outcome" IN ('sign_in_failed','sign_in_succeeded','password_changed')) OR
    (NEW."eventType"='grant' AND NEW."outcome" IN ('current_password_failed','current_password_verified','grant_expired')) OR
    (NEW."eventType"='recovery' AND NEW."outcome" IN ('code_set_generated','rehearsed','rehearsal_failed','reset_started','reset_completed','reset_failed')) OR
    (NEW."eventType"='email_change' AND NEW."outcome" IN ('requested','verified','completed','cancelled','expired','failed')) OR
    (NEW."eventType"='session' AND NEW."outcome" IN ('revoked','already_revoked','stale_security_version','expired')) OR
    (NEW."eventType"='throttle' AND NEW."outcome"='quiet_started')
  )) THEN RAISE EXCEPTION 'global_security_event_insert_invalid'; END IF;

  IF NEW."eventType"='operation_outcome' THEN
    SELECT * INTO operation_row FROM "GlobalSecurityOperation" WHERE "userId"=NEW."userId" AND "operationId"=NEW."operationId" FOR UPDATE;
    SELECT * INTO bound FROM "GlobalSecurityOperationBinding" WHERE "id"=operation_row."bindingId" FOR UPDATE;
    IF operation_row."operationId" IS NULL OR bound."state" <> 'terminal' OR NOT (
      (operation_row."status"='completed' AND operation_row."outcomeCode" IN ('changed','rehearsal_completed','reset_completed','email_changed','cutover_completed') AND NEW."outcome"='completed') OR
      (operation_row."operationKey"='session_revoke' AND operation_row."status"='completed' AND operation_row."outcomeCode" IN ('revoked','already_revoked') AND NEW."outcome"=operation_row."outcomeCode") OR
      (operation_row."status"='rejected' AND NEW."outcome"='rejected') OR
      (operation_row."status"='stale' AND operation_row."outcomeCode"='stale_security_version' AND NEW."outcome"='stale_security_version')
    ) THEN RAISE EXCEPTION 'global_security_event_insert_invalid'; END IF;
  ELSIF NEW."eventType"='throttle' THEN
    SELECT * INTO incident_row FROM "GlobalSecurityIncident" WHERE "id"=NEW."incidentId" FOR UPDATE;
    IF incident_row."id" IS NULL OR incident_row."layer"<>'account_identifier' OR incident_row."userId" IS DISTINCT FROM NEW."userId" OR incident_row."state"<>'quiet' THEN RAISE EXCEPTION 'global_security_event_incident_invalid'; END IF;
  ELSIF NEW."operationId" IS NOT NULL THEN
    SELECT * INTO operation_row FROM "GlobalSecurityOperation" WHERE "userId"=NEW."userId" AND "operationId"=NEW."operationId" FOR UPDATE;
    IF operation_row."operationId" IS NULL THEN RAISE EXCEPTION 'global_security_event_operation_invalid'; END IF;
  END IF;
  RETURN NEW;
END $$;

CREATE OR REPLACE FUNCTION "enforce_global_security_incident_initial_state"()
RETURNS TRIGGER LANGUAGE plpgsql AS $$
DECLARE state_row "AccountSecurityState"%ROWTYPE;
BEGIN
  IF (NEW."layer"='account_identifier' AND NEW."userId" IS NULL) OR (NEW."layer" IN ('client','deployment') AND NEW."userId" IS NOT NULL) THEN RAISE EXCEPTION 'global_security_incident_layer_owner_invalid'; END IF;
  IF NEW."userId" IS NOT NULL THEN SELECT * INTO state_row FROM "AccountSecurityState" WHERE "userId"=NEW."userId" FOR UPDATE; IF state_row."userId" IS NULL THEN RAISE EXCEPTION 'global_security_incident_user_state_missing'; END IF; END IF;
  IF NEW."layer" NOT IN ('account_identifier','client','deployment') OR NEW."normalizedKey" !~ '^[A-Za-z0-9_-]{43}$' OR NEW."failureCount" <> 1 OR NEW."state" <> 'active' OR NEW."quietUntil" IS NOT NULL OR NEW."windowStartedAt" > NEW."lastOutcomeAt" OR NEW."lastOutcomeAt" > clock_timestamp() + INTERVAL '1 millisecond' OR NEW."createdAt" > clock_timestamp() + INTERVAL '1 millisecond' THEN RAISE EXCEPTION 'global_security_incident_initial_state_invalid'; END IF;
  RETURN NEW;
END $$;

CREATE OR REPLACE FUNCTION "enforce_global_security_incident_transition"()
RETURNS TRIGGER LANGUAGE plpgsql AS $$
BEGIN
  IF NEW."id" IS DISTINCT FROM OLD."id" OR NEW."userId" IS DISTINCT FROM OLD."userId" OR NEW."layer" IS DISTINCT FROM OLD."layer" OR NEW."normalizedKey" IS DISTINCT FROM OLD."normalizedKey" OR NEW."windowStartedAt" IS DISTINCT FROM OLD."windowStartedAt" OR NEW."createdAt" IS DISTINCT FROM OLD."createdAt" THEN RAISE EXCEPTION 'global_security_incident_identity_immutable'; END IF;
  IF NEW."failureCount" < OLD."failureCount" THEN RAISE EXCEPTION 'global_security_incident_counter_regression'; END IF;
  IF OLD."quietUntil" IS NOT NULL AND (NEW."quietUntil" IS NULL OR NEW."quietUntil" < OLD."quietUntil" OR NEW."state"='active') THEN RAISE EXCEPTION 'global_security_incident_quiet_period_regression'; END IF;
  IF NEW."failureCount" NOT BETWEEN OLD."failureCount" AND 255 OR NEW."lastOutcomeAt" < OLD."lastOutcomeAt" OR NEW."lastOutcomeAt" > clock_timestamp() + INTERVAL '1 millisecond' THEN RAISE EXCEPTION 'global_security_incident_transition_invalid'; END IF;
  IF OLD."state"='closed' AND (NEW."state" IS DISTINCT FROM OLD."state" OR NEW."failureCount" IS DISTINCT FROM OLD."failureCount" OR NEW."lastOutcomeAt" IS DISTINCT FROM OLD."lastOutcomeAt" OR NEW."quietUntil" IS DISTINCT FROM OLD."quietUntil") THEN RAISE EXCEPTION 'global_security_incident_transition_invalid'; END IF;
  IF OLD."state"='active' AND NEW."state"='active' AND (NEW."quietUntil" IS NOT NULL OR NEW."failureCount" <> LEAST(255,OLD."failureCount"+1)) THEN RAISE EXCEPTION 'global_security_incident_transition_invalid'; END IF;
  IF OLD."state"='active' AND NEW."state"='quiet' AND (NEW."failureCount" <> LEAST(255,OLD."failureCount"+1) OR NEW."failureCount" < 5 OR NEW."quietUntil" IS DISTINCT FROM NEW."lastOutcomeAt" + INTERVAL '15 minutes') THEN RAISE EXCEPTION 'global_security_incident_transition_invalid'; END IF;
  IF OLD."state"='quiet' AND NEW."state"='quiet' AND (NEW."quietUntil" IS DISTINCT FROM OLD."quietUntil" OR NEW."failureCount" <> LEAST(255,OLD."failureCount"+1)) THEN RAISE EXCEPTION 'global_security_incident_quiet_period_regression'; END IF;
  IF NEW."state"='closed' AND (NEW."failureCount" IS DISTINCT FROM OLD."failureCount" OR NEW."lastOutcomeAt" IS DISTINCT FROM OLD."lastOutcomeAt" OR NEW."quietUntil" IS DISTINCT FROM OLD."quietUntil") THEN RAISE EXCEPTION 'global_security_incident_transition_invalid'; END IF;
  IF NOT ((OLD."state"='active' AND NEW."state" IN ('active','quiet','closed')) OR (OLD."state"='quiet' AND NEW."state" IN ('quiet','closed')) OR (OLD."state"='closed' AND NEW."state"='closed')) THEN RAISE EXCEPTION 'global_security_incident_transition_invalid'; END IF;
  RETURN NEW;
END $$;

CREATE OR REPLACE FUNCTION "global_security_throttle_lock"(scope_layer TEXT, scope_key TEXT)
RETURNS VOID LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog,public AS $$
BEGIN
  IF scope_layer NOT IN ('account_identifier','client','deployment') OR scope_key !~ '^[A-Za-z0-9_-]{43}$' THEN RAISE EXCEPTION 'global_security_throttle_input_invalid'; END IF;
  PERFORM pg_advisory_xact_lock(hashtextextended('global-security-incident:v1:' || scope_layer || ':' || scope_key, 0));
END $$;

CREATE OR REPLACE FUNCTION "global_security_throttle_precheck"(scope_account_user_id TEXT, scope_account_key TEXT, scope_client_key TEXT, scope_deployment_key TEXT)
RETURNS TABLE("quiet" BOOLEAN, "deadline" TIMESTAMP(3)) LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog,public AS $$
DECLARE now_time TIMESTAMP(3):=clock_timestamp(); current_deadline TIMESTAMP(3); layer_name TEXT; key_name TEXT; user_name TEXT;
BEGIN
  IF (scope_account_user_id IS NULL) <> (scope_account_key IS NULL) THEN RAISE EXCEPTION 'global_security_throttle_input_invalid'; END IF;
  "quiet":=false;
  "deadline":=NULL;
  PERFORM pg_advisory_xact_lock(hashtextextended('global-security-transition:v1', 0));
  FOR layer_name,key_name,user_name IN SELECT * FROM (VALUES ('account_identifier'::TEXT,scope_account_key,scope_account_user_id),('client',scope_client_key,NULL),('deployment',scope_deployment_key,NULL)) AS layers(layer_name,key_name,user_name) LOOP
    IF key_name IS NOT NULL THEN
      PERFORM public."global_security_throttle_lock"(layer_name,key_name);
      UPDATE public."GlobalSecurityIncident" SET "state"='closed' WHERE "layer"=layer_name AND "normalizedKey"=key_name AND "state"='active' AND now_time >= "windowStartedAt"+INTERVAL '15 minutes';
      UPDATE public."GlobalSecurityIncident" SET "state"='closed' WHERE "layer"=layer_name AND "normalizedKey"=key_name AND "state"='quiet' AND now_time >= "quietUntil";
      SELECT "quietUntil" INTO current_deadline FROM public."GlobalSecurityIncident" WHERE "layer"=layer_name AND "normalizedKey"=key_name AND "state"='quiet' AND now_time < "quietUntil" ORDER BY "quietUntil" DESC LIMIT 1 FOR UPDATE;
      IF current_deadline IS NOT NULL THEN "quiet":=true; "deadline":=GREATEST(COALESCE("deadline",current_deadline),current_deadline); END IF;
    END IF;
  END LOOP;
  RETURN NEXT;
END $$;

CREATE OR REPLACE FUNCTION "global_security_throttle_failure"(scope_account_user_id TEXT, scope_account_key TEXT, scope_client_key TEXT, scope_deployment_key TEXT)
RETURNS TABLE("quiet" BOOLEAN, "deadline" TIMESTAMP(3)) LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog,public AS $$
DECLARE now_time TIMESTAMP(3):=clock_timestamp(); window_start TIMESTAMP(3):=to_timestamp(floor(extract(epoch FROM clock_timestamp())/900)*900); incident_row public."GlobalSecurityIncident"%ROWTYPE; layer_name TEXT; key_name TEXT; user_name TEXT; started_quiet BOOLEAN; created_incident BOOLEAN;
BEGIN
  IF (scope_account_user_id IS NULL) <> (scope_account_key IS NULL) THEN RAISE EXCEPTION 'global_security_throttle_input_invalid'; END IF;
  "quiet":=false;
  "deadline":=NULL;
  PERFORM pg_advisory_xact_lock(hashtextextended('global-security-transition:v1', 0));
  IF scope_account_user_id IS NOT NULL THEN
    INSERT INTO public."AccountSecurityState" ("userId","credentialVersion","sessionSecurityVersion","securityUpdatedAt")
      SELECT scope_account_user_id,1,1,now_time WHERE EXISTS (SELECT 1 FROM public."User" WHERE "id"=scope_account_user_id)
      ON CONFLICT ("userId") DO NOTHING;
  END IF;
  FOR layer_name,key_name,user_name IN SELECT * FROM (VALUES ('account_identifier'::TEXT,scope_account_key,scope_account_user_id),('client',scope_client_key,NULL),('deployment',scope_deployment_key,NULL)) AS layers(layer_name,key_name,user_name) LOOP
    IF key_name IS NULL THEN CONTINUE; END IF;
    PERFORM public."global_security_throttle_lock"(layer_name,key_name);
    SELECT * INTO incident_row FROM public."GlobalSecurityIncident" WHERE "layer"=layer_name AND "normalizedKey"=key_name AND "state"='quiet' AND now_time < "quietUntil" ORDER BY "quietUntil" DESC LIMIT 1 FOR UPDATE;
    IF incident_row."id" IS NOT NULL THEN
      UPDATE public."GlobalSecurityIncident" SET "failureCount"=LEAST(255,"failureCount"+1),"lastOutcomeAt"=now_time WHERE "id"=incident_row."id" RETURNING * INTO incident_row;
      "quiet":=true;
      "deadline":=GREATEST(COALESCE("deadline",incident_row."quietUntil"),incident_row."quietUntil");
      CONTINUE;
    END IF;
    UPDATE public."GlobalSecurityIncident" SET "state"='closed' WHERE "layer"=layer_name AND "normalizedKey"=key_name AND (("state"='active' AND now_time >= "windowStartedAt"+INTERVAL '15 minutes') OR ("state"='quiet' AND now_time >= "quietUntil"));
    SELECT * INTO incident_row FROM public."GlobalSecurityIncident" WHERE "layer"=layer_name AND "normalizedKey"=key_name AND "windowStartedAt"=window_start FOR UPDATE;
    started_quiet:=false;
    created_incident:=false;
    IF incident_row."id" IS NULL THEN
      BEGIN
        INSERT INTO public."GlobalSecurityIncident" ("id","userId","layer","normalizedKey","windowStartedAt","failureCount","quietUntil","state","lastOutcomeAt","createdAt") VALUES ('gsi_'||encode(gen_random_bytes(16),'hex'),user_name,layer_name,key_name,window_start,1,NULL,'active',now_time,now_time) RETURNING * INTO incident_row;
        created_incident:=true;
      EXCEPTION WHEN unique_violation THEN
        SELECT * INTO incident_row FROM public."GlobalSecurityIncident" WHERE "layer"=layer_name AND "normalizedKey"=key_name AND "windowStartedAt"=window_start FOR UPDATE;
      END;
    END IF;
    IF NOT created_incident AND incident_row."state"='active' AND incident_row."failureCount">=4 THEN
      UPDATE public."GlobalSecurityIncident" SET "failureCount"=LEAST(255,"failureCount"+1),"lastOutcomeAt"=now_time,"state"='quiet',"quietUntil"=now_time+INTERVAL '15 minutes' WHERE "id"=incident_row."id" RETURNING * INTO incident_row;
      started_quiet:=true;
    ELSIF NOT created_incident AND incident_row."state"='active' THEN
      UPDATE public."GlobalSecurityIncident" SET "failureCount"=LEAST(255,"failureCount"+1),"lastOutcomeAt"=now_time WHERE "id"=incident_row."id" RETURNING * INTO incident_row;
    ELSIF NOT created_incident AND incident_row."state"='quiet' THEN
      UPDATE public."GlobalSecurityIncident" SET "failureCount"=LEAST(255,"failureCount"+1),"lastOutcomeAt"=now_time WHERE "id"=incident_row."id" RETURNING * INTO incident_row;
    END IF;
    IF started_quiet AND layer_name='account_identifier' THEN
      INSERT INTO public."GlobalSecurityEvent" ("id","userId","eventType","outcome","operationId","incidentId","safeProjection","createdAt") VALUES ('gse_'||encode(gen_random_bytes(16),'hex'),user_name,'throttle','quiet_started',NULL,incident_row."id",'{}',now_time);
    END IF;
    IF incident_row."state"='quiet' AND now_time < incident_row."quietUntil" THEN "quiet":=true; "deadline":=GREATEST(COALESCE("deadline",incident_row."quietUntil"),incident_row."quietUntil"); END IF;
  END LOOP;
  RETURN NEXT;
END $$;

CREATE OR REPLACE FUNCTION "write_global_security_event"(scope_user_id TEXT, scope_event_type TEXT, scope_outcome TEXT, scope_operation_id TEXT)
RETURNS VOID LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog,public AS $$
BEGIN
  IF scope_event_type='throttle' OR (scope_event_type='operation_outcome' AND scope_operation_id IS NULL) THEN RAISE EXCEPTION 'global_security_event_writer_input_invalid'; END IF;
  INSERT INTO public."GlobalSecurityEvent" ("id","userId","eventType","outcome","operationId","incidentId","safeProjection","createdAt") VALUES ('gse_'||encode(gen_random_bytes(16),'hex'),scope_user_id,scope_event_type,scope_outcome,scope_operation_id,NULL,'{}',clock_timestamp());
END $$;

ALTER FUNCTION public."enforce_recovery_session_expiry_finalization"() SECURITY DEFINER;
ALTER FUNCTION public."enforce_recovery_session_expiry_finalization"() SET search_path=pg_catalog,public;
ALTER FUNCTION public."enforce_password_change_success_finalization"() SECURITY DEFINER;
ALTER FUNCTION public."enforce_password_change_success_finalization"() SET search_path=pg_catalog,public;
ALTER FUNCTION public."enforce_recovery_enrollment_success_finalization"() SECURITY DEFINER;
ALTER FUNCTION public."enforce_recovery_enrollment_success_finalization"() SET search_path=pg_catalog,public;
ALTER FUNCTION public."enforce_recovery_enrollment_failure_finalization"() SECURITY DEFINER;
ALTER FUNCTION public."enforce_recovery_enrollment_failure_finalization"() SET search_path=pg_catalog,public;
ALTER FUNCTION public."enforce_recovery_reset_terminal_closure"() SECURITY DEFINER;
ALTER FUNCTION public."enforce_recovery_reset_terminal_closure"() SET search_path=pg_catalog,public;
ALTER FUNCTION public."enforce_recovery_reset_success_finalization"() SECURITY DEFINER;
ALTER FUNCTION public."enforce_recovery_reset_success_finalization"() SET search_path=pg_catalog,public;
ALTER FUNCTION public."enforce_password_change_stale_finalization"() SECURITY DEFINER;
ALTER FUNCTION public."enforce_password_change_stale_finalization"() SET search_path=pg_catalog,public;
ALTER FUNCTION public."enforce_email_change_cutover_finalization"() SECURITY DEFINER;
ALTER FUNCTION public."enforce_email_change_cutover_finalization"() SET search_path=pg_catalog,public;
ALTER FUNCTION public."enforce_email_change_stale_finalization"() SECURITY DEFINER;
ALTER FUNCTION public."enforce_email_change_stale_finalization"() SET search_path=pg_catalog,public;

REVOKE ALL ON TABLE "GlobalSecurityEvent","GlobalSecurityIncident","GlobalSecurityThrottleKey" FROM PUBLIC;
DO $$ BEGIN
  IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname='cubby_runtime') THEN
    REVOKE ALL ON TABLE "GlobalSecurityEvent","GlobalSecurityIncident","GlobalSecurityThrottleKey" FROM cubby_runtime;
    GRANT EXECUTE ON FUNCTION "global_security_throttle_precheck"(TEXT,TEXT,TEXT,TEXT),"global_security_throttle_failure"(TEXT,TEXT,TEXT,TEXT),"write_global_security_event"(TEXT,TEXT,TEXT,TEXT) TO cubby_runtime;
  END IF;
  IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname='cubby_auth') THEN REVOKE ALL ON TABLE "GlobalSecurityEvent","GlobalSecurityIncident","GlobalSecurityThrottleKey" FROM cubby_auth; END IF;
END $$;
REVOKE ALL ON FUNCTION "global_security_throttle_lock"(TEXT,TEXT),"global_security_throttle_precheck"(TEXT,TEXT,TEXT,TEXT),"global_security_throttle_failure"(TEXT,TEXT,TEXT,TEXT),"write_global_security_event"(TEXT,TEXT,TEXT,TEXT) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION "global_security_throttle_precheck"(TEXT,TEXT,TEXT,TEXT),"global_security_throttle_failure"(TEXT,TEXT,TEXT,TEXT),"write_global_security_event"(TEXT,TEXT,TEXT,TEXT) TO cubby_runtime;

COMMIT;
